---
title: "シロクマ　カフェー へようこそ"
---

シロクマ　カフェー へようこそ

<audio controls>
<source src="audio/01/001.mp3">
</audio><hr>

笹を食べながらのんびりするのは最高だなぁ

<audio controls>
<source src="audio/01/002.mp3">
</audio><hr>

ちょっと  またこの子は昼間からゴロゴロして

<audio controls>
<source src="audio/01/003.mp3">
</audio><hr>

掃除の邪魔よ  どきなさい



<audio controls>
<source src="audio/01/004.mp3">
</audio><hr>

はいー

お母さん  おかわり

<audio controls>
<source src="audio/01/005.mp3">
</audio><hr>

どうするの  あなた将来は

<audio controls>
<source src="audio/01/006.mp3">
</audio><hr>

もう  ゴロゴロしてるときに  将来の話なんかしないでよ

<audio controls>
<source src="audio/01/007.mp3">
</audio><hr>

暇があるなら  ちょっとはバイトでも探しなさい

<audio controls>
<source src="audio/01/008.mp3">
</audio><hr>

ええ  ゴロゴロするのに忙しいから  後にするよ

<audio controls>
<source src="audio/01/009.mp3">
</audio><hr>

ああー  吸わないで

<audio controls>
<source src="audio/01/010.mp3">
</audio><hr>

もう

どうしてお母さんはゴロゴロする忙しさが分かんないんだろな

<audio controls>
<source src="audio/01/011.mp3">
</audio><hr>

えーと  働かないでお金がもらえる仕事が載っているのはどれですか

<audio controls>
<source src="audio/01/012.mp3">
</audio><hr>

ないと思います

<audio controls>
<source src="audio/01/013.mp3">
</audio><hr>

え

どうせなら  お洒落なバイトがいいなぁ

あ  これいいな

<audio controls>
<source src="audio/01/014.mp3">
</audio><hr>

はい

あ  もしもし  パンダと申しますが

<audio controls>
<source src="audio/01/015.mp3">
</audio><hr>

そちらでデザインなー  デザイナーのアルバイト募集してますよね

<audio controls>
<source src="audio/01/016.mp3">
</audio><hr>

ええ  そうですよ  経験は？

<audio controls>
<source src="audio/01/017.mp3">
</audio><hr>

ありません

<audio controls>
<source src="audio/01/018.mp3">
</audio><hr>

パソコンのマウスは使えますか

<audio controls>
<source src="audio/01/019.mp3">
</audio><hr>

使えないです  あんまり細かい作業はできません

<audio controls>
<source src="audio/01/020.mp3">
</audio><hr>

そうですか  

得意なことはありますか

<audio controls>
<source src="audio/01/021.mp3">
</audio><hr>

あります

笹を食べたり  寝ながらぼんやりするのが得意です

<audio controls>
<source src="audio/01/022.mp3">
</audio><hr>

あれ  もしもーし

もしもし  そちらでインテリアコーディネーターも募集してますよね

はい

<audio controls>
<source src="audio/01/023.mp3">
</audio><hr>

インテリアコーディネーターって  なんですか

<audio controls>
<source src="audio/01/024.mp3">
</audio><hr>

またゴロゴロして

アルバイト見つかったの

<audio controls>
<source src="audio/01/025.mp3">
</audio><hr>

全然ないよ

<audio controls>
<source src="audio/01/026.mp3">
</audio><hr>

確かコンビニで募集してたでしょう

<audio controls>
<source src="audio/01/027.mp3">
</audio><hr>

コンビニ

品数多過ぎるよ  覚えられないよ

<audio controls>
<source src="audio/01/028.mp3">
</audio><hr>

あー  吸わないで

<audio controls>
<source src="audio/01/029.mp3">
</audio><hr>

もう  外でだらだらしようっと

<audio controls>
<source src="audio/01/030.mp3">
</audio><hr>

ははは  あら  糸屑

あ  取って

うん  取れた

ありがとう

<audio controls>
<source src="audio/01/031.mp3">
</audio><hr>

じっとしてて

あ  待って

<audio controls>
<source src="audio/01/032.mp3">
</audio><hr>


へぇー  こんな所にカフェがあったんだ

<audio controls>
<source src="audio/01/033.mp3">
</audio><hr>

いらっしゃいませ

ようこそ  しろくまカフェへ

<audio controls>
<source src="audio/01/034.mp3">
</audio><hr>

お客様  お一人様ですか

<audio controls>
<source src="audio/01/035.mp3">
</audio><hr>

あ  別に僕は

<audio controls>
<source src="audio/01/036.mp3">
</audio><hr>

お好きな席へどうぞ

<audio controls>
<source src="audio/01/037.mp3">
</audio><hr>


ご注文は

えーと  竹はありますか

<audio controls>
<source src="audio/01/038.mp3">
</audio><hr>

竹はないです

<audio controls>
<source src="audio/01/039.mp3">
</audio><hr>

じゃ  笹ください

笹もないです

じゃ  アイスコーヒー

はい

<audio controls>
<source src="audio/01/040.mp3">
</audio><hr>


ねえ  白熊くん

財布のポイントカードって増えすぎちゃわな

<audio controls>
<source src="audio/01/041.mp3">
</audio><hr>

ペンギンさん  ポイント貯める派

うん

あ  カフェモカお願い  おかわり

<audio controls>
<source src="audio/01/042.mp3">
</audio><hr>

それはひまわり

<audio controls>
<source src="audio/01/043.mp3">
</audio><hr>

それは日替わり

<audio controls>
<source src="audio/01/044.mp3">
</audio><hr>

それは薪割り

<audio controls>
<source src="audio/01/045.mp3">
</audio><hr>

それは西瓜割り

「おかわり」ね

<audio controls>
<source src="audio/01/046.mp3">
</audio><hr>

はい  カフェモカ

このカフェ  ダジャレがなければなぁ

<audio controls>
<source src="audio/01/047.mp3">
</audio><hr>

そういえば  アルバイト募集してるんだって

<audio controls>
<source src="audio/01/048.mp3">
</audio><hr>

うん  人手が足りなくて

ペンギンさん  どう

<audio controls>
<source src="audio/01/049.mp3">
</audio><hr>

え？僕お客とバイトの両立  できるかな

<audio controls>
<source src="audio/01/050.mp3">
</audio><hr>

ウーソ  これから四名ほど  面接に来るんだよ

<audio controls>
<source src="audio/01/051.mp3">
</audio><hr>


なんだ  ちょっと考えちゃったよ

<audio controls>
<source src="audio/01/052.mp3">
</audio><hr>

僕もいいですか

僕もアルバイトしたいと思って

<audio controls>
<source src="audio/01/053.mp3">
</audio><hr>

受けてみる  面接

あ

<audio controls>
<source src="audio/01/054.mp3">
</audio><hr>

では  最初の方  どうぞ

<audio controls>
<source src="audio/01/055.mp3">
</audio><hr>

はい

穴熊です

えーと  ホール係やれますか

<audio controls>
<source src="audio/01/056.mp3">
</audio><hr>

はい  ホールなら任せてください

穴を掘るの  得意なんです

<audio controls>
<source src="audio/01/057.mp3">
</audio><hr>

いや  そのホールは違うし

<audio controls>
<source src="audio/01/058.mp3">
</audio><hr>

次の方

はい

ゾ～ウ～ガ～メ～で～す

<audio controls>
<source src="audio/01/059.mp3">
</audio><hr>

料理とか  運べますか

は～い～

<audio controls>
<source src="audio/01/060.mp3">
</audio><hr>

ヨ～イ～ショー

ゆっくりだね

うん

百年くらい働かせて～

<audio controls>
<source src="audio/01/061.mp3">
</audio><hr>

いえ  そんなには

<audio controls>
<source src="audio/01/062.mp3">
</audio><hr>

マンドリルです

<audio controls>
<source src="audio/01/063.mp3">
</audio><hr>

食べるのが得意です

<audio controls>
<source src="audio/01/064.mp3">
</audio><hr>

ちょっと  それは

<audio controls>
<source src="audio/01/065.mp3">
</audio><hr>

小蟻食です

い  威嚇ができます

<audio controls>
<source src="audio/01/066.mp3">
</audio><hr>

それだけ

みたいだね

<audio controls>
<source src="audio/01/067.mp3">
</audio><hr>

最後の方  どうぞ

はい

パンダと申します

よろしくです

<audio controls>
<source src="audio/01/068.mp3">
</audio><hr>

やっとまともな人が来たね

<audio controls>
<source src="audio/01/069.mp3">
</audio><hr>

パンダ君  何か得意なことはありますか

はい  ゴロゴロしながら笹を食べることです

<audio controls>
<source src="audio/01/070.mp3">
</audio><hr>

あれ

えーと  条件に希望はありますか

<audio controls>
<source src="audio/01/071.mp3">
</audio><hr>

週二日希望です

うん  週二日ですか

<audio controls>
<source src="audio/01/072.mp3">
</audio><hr>

え  週一日でいいんですか

いや  せめて週四日くらい

<audio controls>
<source src="audio/01/073.mp3">
</audio><hr>

そんなの無理です

<audio controls>
<source src="audio/01/074.mp3">
</audio><hr>

あ  けど

呼びに来てくれたら  すぐ行きます

<audio controls>
<source src="audio/01/075.mp3">
</audio><hr>

僕が呼びに行くんですか

あ  そんなそんな

遅刻した場合だけですよ

<audio controls>
<source src="audio/01/076.mp3">
</audio><hr>


遅刻する気満々だね

<audio controls>
<source src="audio/01/077.mp3">
</audio><hr>


ちなみに  やる気はありますか

そんなにありません

<audio controls>
<source src="audio/01/078.mp3">
</audio><hr>


発表します

全員不合格

<audio controls>
<source src="audio/01/079.mp3">
</audio><hr>


えー工

そこ驚くとこ

<audio controls>
<source src="audio/01/080.mp3">
</audio><hr>


結局バイトの人

見つからなかったね

<audio controls>
<source src="audio/01/081.mp3">
</audio><hr>

残念だね

まだいたの

家に帰ると  お母さんに吸われるし

す  吸われる

<audio controls>
<source src="audio/01/082.mp3">
</audio><hr>


うん　ゴーって

あのう　面接中すみません

<audio controls>
<source src="audio/01/083.mp3">
</audio><hr>


住み込み希望でーす

不合格

<audio controls>
<source src="audio/01/084.mp3">
</audio><hr>

あのう  アルバイト希望じゃないみたいですよ

庭に住み込みたいんですー

<audio controls>
<source src="audio/01/085.mp3">
</audio><hr>


ここまで運んで欲しいって　頼まれちゃいまして

<audio controls>
<source src="audio/01/086.mp3">
</audio><hr>

あなた  お名前は

え  私ですか

笹子ですけど

笹子さん  合格

え

<audio controls>
<source src="audio/01/087.mp3">
</audio><hr>

ねぇ　お母さん

僕今日、すごくいい感じのカフェ見つけちゃったよ

<audio controls>
<source src="audio/01/088.mp3">
</audio><hr>

しろくまカフェって言うんだけど

なんに言ってるの？知ってるわよ

<audio controls>
<source src="audio/01/089.mp3">
</audio><hr>

へ？！そうなの？

ずっと前からあるじゃない？

<audio controls>
<source src="audio/01/090.mp3">
</audio><hr>

あ？

うちの隣りに～

へーーーーーーーー！！！！

<audio controls>
<source src="audio/01/091.mp3">
</audio><hr>
