---
title: "グリズリーさん　旅立つ"
---

<span id="episode-title" data-episode="31"> グリズリーさん　旅立つ </span>  

<audio></audio><hr>


シロクマが おいしい季節でやんすよ

<audio></audio><hr>


お前… シロクマ　食ったこと　あんのか？

えぇ　今日も昼に食べましたよ

夏はおいしいんだ

シロクマ！

<audio></audio><hr>


カワウソが　シロクマを！？

ありえねえ！ お前　１人でやったのか？

いや　いや…　仲間と一緒に

<audio></audio><hr>


えっ！？　仲間とシロクマを？

<audio></audio><hr>


クマ食うヤツが俺の店に来るんじゃねえ！

ふざけやがって！

シロクマが あんなヤロウどもに食われるかよ！

今日の昼

<audio></audio><hr>


シロクマ　はじめました？

<audio></audio><hr>


いらっしゃい

シロクマくん　ごめんね

何？　パンダくん

<audio></audio><hr>


僕…　今までシロクマくんのこと シロクマだと思っていたけど

まだ　シロクマじゃなかったんだね

<audio></audio><hr>


パンダくん…　何言ってるの？

表に　「白くま　はじめました」って

いや　あれはさ…

<audio></audio><hr>


だったら　今までは　ただのシロ？　ただのクマ？

白くまっていうのはかき氷の名前だよ

<audio></audio><hr>


かき氷なの？

そう　練乳かけて フルーツをのせたやつだよ

<audio></audio><hr>


なんでも　上にのせたフルーツが シロクマの顔に見えたのが由来とか

ペンギンさんの退屈な話はいいから

それ　食べてみたい！

退屈かどうかは　最後まで 聞いてから　判断してほしいね

<audio></audio><hr>


これが白くまだよ

上から見てね

本当だ！

シロクマだ！

<audio></audio><hr>


しろくまカフェで　白くまを…

とっても　涼しい感じ？

ものすごく涼しいよ

そして現在

<audio></audio><hr>


ウソだろ！？　シロクマ！

<audio></audio><hr>


ほら！　ガセだ　ガセ

<audio></audio><hr>


マジか！　マジだったのか！！

ごちそうさまでした

あぁ…　そんな！

<audio></audio><hr>


「白くま　はじめました」

「はじめました」じゃねえだろ お前！

人生 終わっちまってんじゃねえかよ！

<audio></audio><hr>


やっぱり　ムリですよ！　ハバネロは… 辛すぎます

そう？　結構　クセになるよ　ハバネロ

<audio></audio><hr>


シロクマ…　お前とは ガキの頃からのつきあいだったよな

ハ…　ハチミツ　食べたい！

大丈夫かよ？　シロクマ！

<audio></audio><hr>


頑張れ！

ワカサギ　食べたい！

大丈夫かよ？　シロクマ…

<audio></audio><hr>


キノコ　食べたい！

大丈夫かよ？　シロクマ！

<audio></audio><hr>


なんか　ろくな思い出がねえな…

とはいえ　懐かしい思い出だぜ

<audio></audio><hr>


あぁ…　ダメだ！こうしていると お前のことばかり思い出しちまう

シロクマ！

<audio></audio><hr>


ビール買う？

持ってきたよ　ほい

それは　リール

ダジャレ！

<audio></audio><hr>


シロクマ！

孤独よ… 俺の悲しみを癒やしてくれ

<audio></audio><hr>


クマだ！かわいい！

何してるの～？

こっち向いて～

<audio></audio><hr>


ねぇ　グリズリーさんのお店　ずっとお休みしてるって　ホント？

<audio></audio><hr>


旅行にでも行ってるのかも

旅かぁ…　やっぱり　ワイルドな旅なんだろうね

<audio></audio><hr>


おそらく

あてもなく　北へと向かうグリズリー

<audio></audio><hr>


ふと立ち寄った居酒屋で…

どうぞ

頼んでねえぜ？

サービスですよ

<audio></audio><hr>


お客さん　旅の方でしょ？

わかるかい？

<audio></audio><hr>


都会のニオイがしますよ

…と　そこへ現れる　人相の悪い男

よう　女将！ 今日も来てやったぜ

<audio></audio><hr>


帰っとくれ！ アンタが来るおかげで　他のお客さんが 寄りつきゃしないよ

<audio></audio><hr>


生意気な口をきくと　タダじゃ…

出ていきな　文句があるなら 俺が相手になるぜ

すみません！

<audio></audio><hr>


ありがとうございます

サケのお礼さ

それがきっかけで グリズリーは居酒屋の用心棒になった

<audio></audio><hr>


女将の幼い子供たちも懐き…

グリズリーおじちゃん

近所のお年寄りたちとも馴染み…

<audio></audio><hr>


悪いね

気にすんなって

いつしか　グリズリーはなくてはならない存在になっていた

<audio></audio><hr>


パンダくん　そんな　リアリティーのない話を 本気にしちゃダメだよ

<audio></audio><hr>


まさか　こんな展開になるとはな

グリの兄貴も一緒にどうっすか？

シャケをサカナに　おシャケを一杯… なんつって！

<audio></audio><hr>


シロクマ…

ちょっと！ ダジャレはダメだって言ったでしょ

すみません…

<audio></audio><hr>


しょせん俺たちは弱肉強食の世界を生きる者

<audio></audio><hr>


もう　俺は泣かないぜ！

<audio></audio><hr>


また　いつでもおいで おじちゃん　バイバーイ！

あばよ　シロクマ！

<audio></audio><hr>


この店は俺が引き継ぐ！

どうしたんですか？　急に

アイツの代わりが務まるのは 親友の俺しかいねえだろ

<audio></audio><hr>


俺が　シロクマ始める！

しろくまカフェの店長やるの？

今日から　マスターと呼びな

<audio></audio><hr>


グリズリー　バーは？

やる！　昼も夜も働く！

いつ　寝るんですか？

合間に寝る

<audio></audio><hr>


ダジャレだってやるぜ！ 何しろ　俺が　この店の…

<audio></audio><hr>


シスターだろ！

それじゃあ…

<audio></audio><hr>


イースターだろ！

それじゃあ　これで　どうだ？

<audio></audio><hr>


ポスターだろ！

これは　ダスター

ダスターで　顔拭くんじゃねえ！

<audio></audio><hr>


テメエ　なんで生きてるんだよ！

お母さんが産んだから

そうじゃねえ！

お前　カワウソに食われたんじゃ！？

<audio></audio><hr>



ちは～　今日も　白くま 食べにきたでやんす

<audio></audio><hr>


どういうことだ！

<audio></audio><hr>


まぎらわしい名前 つけてんじゃねえ

ったく…　驚かせやがって

悲しみにくれた 俺の時間はいったい…

<audio></audio><hr>


思い出すと泣いちゃうほど ショックだったの？

キーン！　ってなってんだよ！

<audio></audio><hr>
