---
title: "半田さんの合コン！"
---

半田さんの合コン！

<audio controls>
<source src="audio/20/001.mp3">
</audio><hr>

前半からつづく

<audio controls>
<source src="audio/20/002.mp3">
</audio><hr>

ご注文　お決まりですか？

<audio controls>
<source src="audio/20/003.mp3">
</audio><hr>

シロクマ！？

<audio controls>
<source src="audio/20/004.mp3">
</audio><hr>

そ…　それじゃ 自己紹介から始めましょうか

<audio controls>
<source src="audio/20/005.mp3">
</audio><hr>

僕からいきますね

桐野です

動物園の飼育員をやっています

<audio controls>
<source src="audio/20/006.mp3">
</audio><hr>

じゃ　次は先輩

は…　は…　半田です！

本日は　このように 晴れがましい合コンに　お…　お招きいただき

<audio controls>
<source src="audio/20/007.mp3">
</audio><hr>

誠にありがとうございます

ふつつか者ではありますが

以後　よろしく お見知りおきください

<audio controls>
<source src="audio/20/008.mp3">
</audio><hr>

先輩　かたい…

そこまで丁寧な 自己紹介じゃなくて大丈夫です

けど　初対面だから

<audio controls>
<source src="audio/20/009.mp3">
</audio><hr>

大丈夫です

合コンって　そういう感じのものじゃないんで

<audio controls>
<source src="audio/20/010.mp3">
</audio><hr>

続きまして 私と同じ職場に勤める

<audio controls>
<source src="audio/20/011.mp3">
</audio><hr>

パンダくんを紹介します！

だから　かたいって…

すみません パンダ　連れてきちゃって

<audio controls>
<source src="audio/20/012.mp3">
</audio><hr>

パンダで～す

かわいい！！

パンダ　意外にウケた…

では　続いて…

<audio controls>
<source src="audio/20/013.mp3">
</audio><hr>

シロクマです ふだんは　カフェやってます

すご～い！

カフェですか？

<audio controls>
<source src="audio/20/014.mp3">
</audio><hr>

行ってみたい！

なんてカフェですか？

しろくまカフェ

<audio controls>
<source src="audio/20/015.mp3">
</audio><hr>

そのまんまなんですね

あの　もしかして 雑誌とかに載ってないですか？

<audio controls>
<source src="audio/20/016.mp3">
</audio><hr>

時々

すごい！　見たことある

今度　行ってもいいですか？

もちろん

<audio controls>
<source src="audio/20/017.mp3">
</audio><hr>

こっちも大好評だな…

趣味は　アザラシの捕獲

<audio controls>
<source src="audio/20/018.mp3">
</audio><hr>

何ですか？それ

今度連れてってください

やめたほうがいいよ…

<audio controls>
<source src="audio/20/019.mp3">
</audio><hr>

じゃあ　女子 いきますね　

ヒロミで～す

先輩　ヒロミちゃん

<audio controls>
<source src="audio/20/020.mp3">
</audio><hr>

リカです

リカちゃん

ミズキです

ミズキちゃん

<audio controls>
<source src="audio/20/021.mp3">
</audio><hr>

わかってるよ　大丈夫 聞こえるから

ご注文　どうぞ

<audio controls>
<source src="audio/20/022.mp3">
</audio><hr>

とりあえず　生

はい

とりあえず　竹

竹？

<audio controls>
<source src="audio/20/023.mp3">
</audio><hr>

ちょっと 置いてないんですが…

え～っ　じゃあ　笹

笹も　ないんですが…

<audio controls>
<source src="audio/20/024.mp3">
</audio><hr>

じゃあ　みんな　どうしてるの？

ビール　飲んだり…

<audio controls>
<source src="audio/20/025.mp3">
</audio><hr>

枝豆　食べたり…

唐揚げ　食べたり…

とりあえず　アザラシ

<audio controls>
<source src="audio/20/026.mp3">
</audio><hr>

ないです

持ち込みは？

ダメです

とりあえず　生６つと ジュース１つでいいです

<audio controls>
<source src="audio/20/027.mp3">
</audio><hr>

僕　竹がいいよ

そうよね　パンダっていったら やっぱり竹よね

<audio controls>
<source src="audio/20/028.mp3">
</audio><hr>

食べてるとこ　見てみたい

かわいいかも！

<audio controls>
<source src="audio/20/029.mp3">
</audio><hr>

いや～ん！ 竹　食べて！

何なんだ？　この合コン…

<audio controls>
<source src="audio/20/030.mp3">
</audio><hr>

いや　僕はね　合コンに行きたいって言ってるわけじゃないんだよ

はい

ただね　

<audio controls>
<source src="audio/20/031.mp3">
</audio><hr>

僕がずっとパンダくんの話を聞いていたわけだからさ

誘うなら　僕を誘うでしょ？

<audio controls>
<source src="audio/20/032.mp3">
</audio><hr>

僕にはペン子さんとい ペンギンがいるわけだから

別に行きたくはないんだけど 社会勉強というか…

<audio controls>
<source src="audio/20/033.mp3">
</audio><hr>

行きたいんですか？

だから行きたくないよ

笹子さんも　笹子さんでしょ

<audio controls>
<source src="audio/20/034.mp3">
</audio><hr>

誘うなら　シロクマさんじゃなくてペンギンさんですよってひと言…

欲しかったな

行きたいんですか？

<audio controls>
<source src="audio/20/035.mp3">
</audio><hr>

行きたいよ

みんな今頃楽しくやってるんだろうな！

笹子さん カフェモカおかわり

<audio controls>
<source src="audio/20/036.mp3">
</audio><hr>

はい

へぇ～　みんな大学からのお友達なんだ

そうなんです

<audio controls>
<source src="audio/20/037.mp3">
</audio><hr>

そうそう　動物園にカピバラいますか？

今　流行ってますよね

<audio controls>
<source src="audio/20/038.mp3">
</audio><hr>

カピバラはネズミだってホントですか？

じゃあ　動物園にはカピバラの温泉とか あるんですか？

<audio controls>
<source src="audio/20/039.mp3">
</audio><hr>

先輩　声に出して しゃべってください

っていうか　さっきから何も　しゃべって ないじゃないですか

<audio controls>
<source src="audio/20/040.mp3">
</audio><hr>

俺そろそろ…

何か用事あるんですか？

<audio controls>
<source src="audio/20/041.mp3">
</audio><hr>

いや　風呂の掃除があるから

わぁ～　ちょっと半田さん！

風呂の掃除で帰るとか

絶対女の子の前で言っちゃダメですって

どうかしたの？

<audio controls>
<source src="audio/20/042.mp3">
</audio><hr>

い…　いや大丈夫

先輩　ちょっと酔っちゃって

<audio controls>
<source src="audio/20/043.mp3">
</audio><hr>

掃除がどうかしたんですか？

ソ…　ソーセージ注文しようかって 先輩が

<audio controls>
<source src="audio/20/044.mp3">
</audio><hr>

ねっ　先輩　僕注文しますね

ソーセージ盛り合わせ２つ

<audio controls>
<source src="audio/20/045.mp3">
</audio><hr>

お刺身　盛り合わせも

シロクマさん　すみません

<audio controls>
<source src="audio/20/046.mp3">
</audio><hr>

あれ？　パンダくんは？

お待ちどおさま！

<audio controls>
<source src="audio/20/047.mp3">
</audio><hr>

待ってないよ！

わざわざ取りに行ったの？

だって　ここ　何もないんだもん

<audio controls>
<source src="audio/20/048.mp3">
</audio><hr>

あるでしょ　いろいろ！

ナッツとか小エビの唐揚げとか

いただきま～す

<audio controls>
<source src="audio/20/049.mp3">
</audio><hr>

かわいい！

パンダが竹食べてるとこ初めて見た！

私も　私も！

写メ　撮っていいですか？

<audio controls>
<source src="audio/20/050.mp3">
</audio><hr>

持ち込みはダメだって書いてあるよ

お店の人にバレたら…

お待ちどおさまで…

<audio controls>
<source src="audio/20/051.mp3">
</audio><hr>

すみません　持ち込みはダメだって 言ったんですけど

<audio controls>
<source src="audio/20/052.mp3">
</audio><hr>

か…かわいい！

写メ　いいですか！？

あの　持ち込みは？

いいです　いいです！

<audio controls>
<source src="audio/20/053.mp3">
</audio><hr>

半田さんは何の動物の飼育を しているんですか？

<audio controls>
<source src="audio/20/054.mp3">
</audio><hr>

パ…　パンダとか

パンダ！？ パンダの飼育をしてるんですか？

え…　えぇ

<audio controls>
<source src="audio/20/055.mp3">
</audio><hr>

かわいい！

か…　かわいい？

パンダの話 

<audio controls>
<source src="audio/20/056.mp3">
</audio><hr>

いろいろ　聞かせてください！

<audio controls>
<source src="audio/20/057.mp3">
</audio><hr>

昼寝しているところ

キャーッ！　かわいい！！

<audio controls>
<source src="audio/20/058.mp3">
</audio><hr>

遊んでいるところ

キャーッ！　かわいい！！

ダラダラしているところ

キャーッ！　かわいい！！

よく　見分けがつきますね

<audio controls>
<source src="audio/20/059.mp3">
</audio><hr>

一応　プロだから

かわいい！

もっと聞かせてください！

<audio controls>
<source src="audio/20/060.mp3">
</audio><hr>

パンダは腸が短くて　竹からだと あまり栄養がとれないんです

だから量で補うために１日中竹を食べているんです

<audio controls>
<source src="audio/20/061.mp3">
</audio><hr>

腸が短いんだ

<audio controls>
<source src="audio/20/062.mp3">
</audio><hr>

かわいい！

そこもかわいいんだ

半田さん　もっと教えてあげて 僕のかわいいとこ

<audio controls>
<source src="audio/20/063.mp3">
</audio><hr>

竹しか食べてないから

パンダのウンチって いいにおいなんですよ

ちょっと レモンのにおいに似ているんです

<audio controls>
<source src="audio/20/064.mp3">
</audio><hr>

あぁ…　これ　これ

うん　パンダのウンチのにおいです

どうぞ

<audio controls>
<source src="audio/20/065.mp3">
</audio><hr>

先輩！　その情報は いらないんじゃないですか？

もう！　もっと かわいいエピソードにしてよ

<audio controls>
<source src="audio/20/066.mp3">
</audio><hr>

えっ！？　そう？

あっ！　パンダって 垂れ目でかわいい感じでしょ？

<audio controls>
<source src="audio/20/067.mp3">
</audio><hr>

あれって　実際の目は 小さくて　鋭いんですよ

それも　いらないよ

<audio controls>
<source src="audio/20/068.mp3">
</audio><hr>

そうなの？

僕にとっては かわいいところなんだけど

もう！　半田さん！！

<audio controls>
<source src="audio/20/069.mp3">
</audio><hr>

ペンギンさん　カフェモカ　おかわり お待たせしました

あれ？　いない…

<audio controls>
<source src="audio/20/070.mp3">
</audio><hr>

今度　パンダコーナー 遊びにいってもいいですか？

もちろんです　見にきてください

<audio controls>
<source src="audio/20/071.mp3">
</audio><hr>

常勤パンダさんも紹介しますよ

常勤パンダさん？ このパンダさんは何なんですか？

週２のバイトなんです

<audio controls>
<source src="audio/20/072.mp3">
</audio><hr>

へぇ～　アルバイトなんだ？

かわいい！

かわいいかな？

かわいいですよ！

ねっ？

<audio controls>
<source src="audio/20/073.mp3">
</audio><hr>

あっ！

どうしたの？

<audio controls>
<source src="audio/20/074.mp3">
</audio><hr>

な…　何？

ペンギン！？

どうも　こんばんは

何しにきたの？

<audio controls>
<source src="audio/20/075.mp3">
</audio><hr>

忙しいんじゃなかったの？ ペンギンさん

いや　

<audio controls>
<source src="audio/20/076.mp3">
</audio><hr>

それは…

かわいい！

えっ！？　そこも？

<audio controls>
<source src="audio/20/077.mp3">
</audio><hr>

マ·マ·マハロ

ペンギンさん　マイク 代わってもらっていいですか？

もう１曲　もう１曲！

しようがないな

<audio controls>
<source src="audio/20/078.mp3">
</audio><hr>

「ぐぅ」？

寝てる！

パンダくん　起きて！　パンダくん！！

<audio controls>
<source src="audio/20/079.mp3">
</audio><hr>

って…　先輩まで！

見て　寝てる！

ねぇ　なんか似てない？

<audio controls>
<source src="audio/20/080.mp3">
</audio><hr>

このカフェにたどり着いた ラッキーボーイズ　アンド　ガールズ

<audio controls>
<source src="audio/20/081.mp3">
</audio><hr>

今日は　ありがとうございました

楽しかったです

また　パンダの話聞かせてください

<audio controls>
<source src="audio/20/082.mp3">
</audio><hr>

えぇ　動物園に遊びにきてください

はい じゃあ　おやすみなさい

<audio controls>
<source src="audio/20/083.mp3">
</audio><hr>

それじゃ　俺も 風呂の掃除あるから　帰るわ

また　明日な

はい

<audio controls>
<source src="audio/20/084.mp3">
</audio><hr>

半田さんらしいや

うちで　コーヒーでも飲んでく？

<audio controls>
<source src="audio/20/085.mp3">
</audio><hr>

はい　シロクマさん

マ·マ·マハロ

イエーイ！

あっ！　あれ？　みんなは？

おしまい

<audio controls>
<source src="audio/20/086.mp3">
</audio><hr>




