---
title: "真夏の雑草取り"
---

<span id="episode-title" data-episode="29">真夏の雑草取り</span>

<audio>
</audio><hr>

やっと着いた

近道しようとしたら　雑草がすごくて迷ちゃったよ

<audio>
</audio><hr>

そうなの　迷ちゃうお客さんもいるみたい

隣なのに家から20分かかちゃったよ

<audio>
</audio><hr>

雑草すごいね

中の席にしようか

よし　やろう

<audio>
</audio><hr>

よいしょ(」・ω・)」

何してるの　白熊君

<audio>
</audio><hr>

テラスで風を感じながら キンキンに冷したミントティーを飲んでる

<audio>
</audio><hr>

そうじゃなくて

なんで僕に君の店の雑草取りさせて

君がテラスをすすんでるの

<audio>
</audio><hr>

僕は普通寒いところにいるでしょう

僕もだよ

真夏に雑草取りをするペンギンなんて どこの世界にいるの

<audio>
</audio><hr>

ごちそうさまでした

では

らまさん　どこ行くの

<audio>
</audio><hr>

もう食べられないんで　失礼しようかなって

ちょっと待って　なんで帰ちゃうの

僕たちの雑草取り始まったばかりでしょう

<audio>
</audio><hr>

けど　もうお腹いっぱいですよ

雑草取りって　そういうことじゃないでしょう

もうちょっと頑張ろうよ

<audio>
</audio><hr>

僕　もうお腹はじけちゃいますよ

そうじゃなくて

<audio>
</audio><hr>

食べる以外の方法で雑草を取れないのかな

そうでしたか　ちょっと考えてみます

<audio>
</audio><hr>

寝てる

起きてますよ

寝てたでしょう

ミントティー　どう？

<audio>
</audio><hr>

あ　いただきます

もう　皆　頑張ろうよ

頑張りたいんだけど　僕ユーカリしか食べられなっくて

<audio>
</audio><hr>

だから　食べない方法もあるんじゃないかな

ペンギンさん

<audio>
</audio><hr>

変な形の石拾った

要らないの　その報告は　雑草取ろう

ペンギンさん

<audio>
</audio><hr>

笹子さん　それは？

土偶です

拾いました

要らない報告でした

<audio>
</audio><hr>

何　この庭

よく落ちてるんだ

遮光器土偶ですね

うん

面白い顔だね

<audio>
</audio><hr>

僕だけかな　雑草取り真面目にやってるの

僕も～

あ　

いるよ～～

怠け者くん

<audio>
</audio><hr>

が～ん～ば～る～ぞ～

やる気はあるんだけどな

<audio>
</audio><hr>

クーラーは涼しいな

ねぇ　笹持ってきて　お母さん

涼しいでしょう

<audio>
</audio><hr>

あ　ペンギンさん何してるの

何してるのじゃないよパンダ君　雑草取りは？

ペンギンさんはなんでそんなに雑草取りがすきなの

<audio>
</audio><hr>

好きじゃないよ

けど　このままじゃ一日じゃ終わらないよ

分かったよ

<audio>
</audio><hr>

もう

じゃ　行こうか

うん　昼寝してからすぐ行くよ

<audio>
</audio><hr>

あ～～～吸わないで～～～

暑いな

僕だって暑いよ

<audio>
</audio><hr>

何！　え！　火事？

ええ？

パンダ君　急ごう

<audio>
</audio><hr>

ちょっと　何してるの

バーベキュー

らまさん　お腹いっぱいだって言ってたでしょう

<audio>
</audio><hr>

バーベキューは別腹ですよ

聞いたことないよ　そんな言葉

ペンギンさん　そこで拾った土偶です

<audio>
</audio><hr>

また？

だから　すごいんだけれど　要らないよ　その報告は

<audio>
</audio><hr>

見せて　見せて

らまさん

はい　どうぞ

焼けたよ

ありがとうございます

僕ちょっと倒れるよ

ペンギンさん

<audio>
</audio><hr>

ナイス　ショット

打てるもんですね

何してるの

<audio>
</audio><hr>

ゴルフ

誰も僕を見習って頑張ろうとしないなんて

<audio>
</audio><hr>

ごめん

ペンギンさん

何　笹子さん　また土偶？

いいえ　皆でここだけはやったんですよ

え？

<audio>
</audio><hr>

この木陰なら涼しいし

ペンギンさんを休ませてあげられるって　らまさんが

テラスが日が射してきちゃって

<audio>
</audio><hr>

ごめんね

友達と一緒に賑やかにできたほうがいいなぁって

<audio>
</audio><hr>

だって　みんなでこうしてるだけで　楽しいよ

<audio>
</audio><hr>

そうだね

僕大事なこと忘れてたみたい

ミントティー　飲む？

うん

<audio>
</audio><hr>

私たちは　雑草取りに戻りましょうか

うん

ペンギンさんは休んでてください

じゃあ

もう一頑張りしますか

<audio>
</audio><hr>

もう食べられません

ペンギンさん　出番が来たよ

<audio>
</audio><hr>

大～丈～夫～　

後は　僕が～

終わらないね

どうしましょうか

バービキュ食べ過ぎて　僕もう草は食べられません

<audio>
</audio><hr>

もしもし

何だよ　このクソ暑い中に呼び出しやがって

庭の雑草が伸びちゃってさ

庭の雑草？　

<audio>
</audio><hr>

白熊　

おめぇまさか　俺に雑草取らせようってじゃねんだろうな

いい？

いい？

じゃねぇー

<audio>
</audio><hr>

これでいいのか

なんて　暴力的で　なんて　丁寧な仕事だ

飯食わせろ！

はい

<audio>
</audio><hr>

うめぇー！

またな

暴風のように去っていた

今日はおごるよ

<audio>
</audio><hr>

ぺんぎんさんにも迷惑かけちゃったし

飲もうか

<audio>
</audio><hr>

やぁ　今日は働いたね

白熊さんもこっちに来て飲みましょう

<audio>
</audio><hr>

楽しにゃ

でしょう

<audio>
</audio><hr>

白熊君相談って何

それが

<audio>
</audio><hr>

どうしたの　僕でよかったら相談に乗るよ

<audio>
</audio><hr>

え

たった数日でこんなに伸びたの

夏の雑草は　伸びるの早いんだよ

<audio>
</audio><hr>

僕が手伝う理由が見えないんだけど

ほら　僕は寒いところの生き物だから

<audio>
</audio><hr>

だから　僕もだよ

さっき見つけた土偶です

笹子さん　その報告はもういいから

<audio>
</audio><hr>

