---
title: "憧れの一人暮らし"
---

<span id="episode-title" data-episode="39"> 憧れの一人暮らし </span> 

<audio></audio><hr>

ねぇねぇ　ペンギンさん

僕に向いてると思わない？

え　動物園のバイト？ やっと本気出すの

<audio></audio><hr>

違うよ　一人暮らしだよ

一人暮らし？

何　また家出するの

<audio></audio><hr>

家出じゃないよ　一人暮らし

一人　一人

パンダくんが？　無理でしょ

即答ですね

<audio></audio><hr>

即答

それは　木刀

それは　格闘

それは　食堂

それは　給湯

いいよね　休養

たまには　のんびりしたいね

<audio></audio><hr>

いいよね　のんびり

一人暮らししたいな

いつものんびりしてるじゃない

違うよ　僕はのんびり 一人暮らしがしたいんだよ

え～　大変だよ

<audio></audio><hr>

自分のことは 自分でしなくちゃいけないから

それがいいんじゃない

パンダくん　ひょっとして 過剰な夢見てない

どういう生活考えてるの？

<audio></audio><hr>

聞く？

いや　やめとく

えっと…

話すの？

朝はね　大きなベッドで目を覚ますの

そしたら　カーテンが開いて

<audio></audio><hr>

都会の景色が　ダーッて広がって

その下には　一面の竹林

都会なのか竹林なのか どっちかにしてよ

<audio></audio><hr>

起きたらね その景色を眺めながら…

朝は　フレッシュジュースで目覚めるんだ

それってもしかして　笹ジュース？

笹ジュースのあとは…

笹でしょ

<audio></audio><hr>

何だか　全体　緑だね

っていうか いつもと同じじゃない

一人暮らしなんて する必要ある？

それで　聞いて

ノックの音がしたら…

<audio></audio><hr>

おはようございます　パンダ様

何で僕？

本日のご予定は

１０時からゴロゴロ　１２時からご昼食

１時からゴロゴロ

３時のおやつののちゴロゴロとなっております

<audio></audio><hr>

レストランに到着したら…

いらっしゃいませ

お待ちしておりました　パンダ様

え～っ　それも僕？

<audio></audio><hr>

お店のテーブルについたら 豪華なディナーが用意されてるの

<audio></audio><hr>

どうぞ　お召し上がりください

まぁまぁだね

バイトの気分じゃないな

代わりに行ってきてくれる？

<audio></audio><hr>

かしこまりました

何で僕が？

っていうか　それだと 一人暮らしじゃないよね

<audio></audio><hr>

楽しくなってきたな 早く　一人暮らししたいよ

そんな物件あるわけないでしょ！

<audio></audio><hr>

ありますよ

一人暮らし用の物件ですよね？

６畳に押し入れつきですから

一人暮らしには 広めだと思いますよ

ちゃんと　ゴロゴロもできますし

<audio></audio><hr>

窓からは　竹林も見えますしね

なんか　もうちょっと…　ワーッとして　ダーッとしてるのが いいんだけど

ワーッとして　ダーッ…

<audio></audio><hr>

曖昧すぎるでしょ　パンダくん

すみません…

ありますよ　ワーッとして　ダーッ

本当？

本当？

<audio></audio><hr>

なんか普通だね

ワーッとしてませんか？

してない

ダーッとは？

してない

<audio></audio><hr>

パンダくんの理想が高すぎるんだよ

そんなことないよ

絶対どこかにあるはずだよ

僕の理想の一人暮らしハウス

<audio></audio><hr>

あるかなぁ…

だって　ペンギンさんがいるもの あとは家だけでしょ？

僕を理想の一部に 組み込まないでくれる？

<audio></audio><hr>

ああ…　絶対あるはずなんだ

竹林！　そうそう こんな感じの竹林が理想だよ

あっ…　

<audio></audio><hr>

ちょっ… ちょっと！　パンダくん！

うわ～っ…　いい感じ

ワーッとして　ダーッとしてるよ！

<audio></audio><hr>

こんなところに住みたいな…

はあ？　って… ここ　パンダくんちじゃないの？

あっ　本当だ

<audio></audio><hr>

やっぱり　一人暮らしする 必要なんて　ないんじゃない？

あれ？

アナグマくんじゃない？

<audio></audio><hr>

何してんの？　物件探し？

あっ… もう耐えられなくてさ

一人暮らし？

大失敗

パンダくん　しっかり 聞いておいたほうがいいよ

<audio></audio><hr>

一人暮らしって いいことばかりじゃないんだから

フローリングの部屋はよくないよ　引っ越したい

えっ　そうなの？ 掃除しやすくない？

<audio></audio><hr>

掃除なら　ペンギンさんに 頼めばいいよ

だから　僕を召し使いにしないで！

どうして引っ越したいの？

<audio></audio><hr>

だって…

穴…　穴　掘れなくて…　もう辛くて　辛くて

え～…　そんなに辛いかな？

パンダくんでいうと　ゴロゴロを 止められるくらい辛いと思うよ

ハッ…　それは辛いね

<audio></audio><hr>

他のみんなは　どんなところに 住んでるんだろうね？

いらっしゃい！

近い　近い　近い

<audio></audio><hr>

さあ　どうぞ

ゆっくり　くつろいでください

近い　近い　近い

いらっしゃい

<audio></audio><hr>

すごいね　コアリクイくん

一軒家？

買っちゃいました　３５年ローンです

うわ～っ！ 上がって　見ていってください

<audio></audio><hr>

寂しい話するけど…

親子ローンかな？　平均寿命的に

親子孫ローンかもね

<audio></audio><hr>

あっ　ゾウガメさんだ

どこ行くの？

家に…

一緒に行ってもいい？

一人暮らし　見せてよ

いいよ

<audio></audio><hr>

へぇ～　オシャレなマンションだね

間取りは？

２ＬＳ

Ｓ？　それって何？　サービスルーム？

<audio></audio><hr>

ううん

セレブって感じだね

Ｓって　セレブのＳ？

<audio></audio><hr>

砂

こだわりの２ＬＳ

<audio></audio><hr>

は～い

あれ？ どうしたの２人とも

おじゃまします

結構きれいにしてるんだ

あっ　ちょっと！

<audio></audio><hr>

ここは　水飲み場？

お風呂場

じゃあ　こっちが　水飲み場？

トイレだよ

見直したよ　半田さん

お風呂も　トイレも きれいにしてあるじゃない

<audio></audio><hr>

あれ？　これで終わり？

これで　全部だよ

まあ　半田さんなら しようがないか

僕　ここでいいよ

何が？　

<audio></audio><hr>

どういうこと？

半田さんは そっちの奥で寝たら？

えっ！？　なんで？

<audio></audio><hr>

真ん中の段に 僕のものを入れるね

勝手に笹ジュース飲まないでね

飲まないよ

ってか入れないで！

自分のリズムで起きたいから 朝出るときは静かにしてね

<audio></audio><hr>

だから寝ないで！

バイトは　どうするの！？

忠実なペンギンさんが 代わりに行ってくれるよ

だから 召し使いにしないでってば！

<audio></audio><hr>

本当は 一人暮らしがしたいんだけど　しようがないよね

３人で頑張っていこう

じゃあ　僕　寝るから ご飯ができたら起こしてね

<audio></audio><hr>

で　半田さんに お風呂掃除するからって　追い返されたの？

ひどいよね

まぁ　無理もない気がするよ

パンダくん まだ一人暮らししたいの？

ふぅ～　

<audio></audio><hr>

もう諦めたよ

あっ　でも 召し使いは見つけたよ

僕のことも諦めてくれる？


<audio></audio><hr>



