---
title: "カフェのお花見"

---

カフェのお花見

<audio controls>
<source src="02/100.mp3">
</audio><hr>

誰にも言わないでよ

はい

<audio controls>
<source src="02/101.mp3">
</audio><hr>

僕、好きなペンギンさんが居るんだ

すみません、抹茶パフェください

<audio controls>
<source src="02/102.mp3">
</audio><hr>

それで

僕好きなペンギンさんが

すみません、やっぱりいちごパフェにしてくれますか

ちょっと！聞く気ある？！

<audio controls>
<source src="02/103.mp3">
</audio><hr>

こんにちは

しろくま君　いつもの

お待ち遠様　竹大盛りね

いただきま～す

<audio controls>
<source src="02/104.mp3">
</audio><hr>

やろうか

何を

ん？お花見

<audio controls>
<source src="02/105.mp3">
</audio><hr>

すごいね、桜

綺麗ですね

あそこにしよう

<audio controls>
<source src="02/106.mp3">
</audio><hr>

すごいね

今年も綺麗に咲いたね

<audio controls>
<source src="02/107.mp3">
</audio><hr>

お摘みどうしよう

情緒がないなぁ

桜は綺麗だなって話してるんだから

<audio controls>
<source src="02/108.mp3">
</audio><hr>

うん、お摘み持ってない？

聞いてないな　まぁ、いいや

<audio controls>
<source src="02/109.mp3">
</audio><hr>

花弁って食べられますかね

もう一人情緒ないのがいるよ

ラマさんは草が食べられるなら　食べられるんじゃない？

<audio controls>
<source src="02/110.mp3">
</audio><hr>

ね～竹持ってない？

持ってないよ

<audio controls>
<source src="02/111.mp3">
</audio><hr>

お弁当なら持って来たよ

さすがしろくま君

<audio controls>
<source src="02/112.mp3">
</audio><hr>

僕買い出しいって来るね

なまけもの君？

<audio controls>
<source src="02/113.mp3">
</audio><hr>

コンビニで

何か乾き物買ってくる

いいよ、あるものだけで

<audio controls>
<source src="02/114.mp3">
</audio><hr>

すぐそこだから

行ってくるね

<audio controls>
<source src="02/115.mp3">
</audio><hr>

じゃね～

いってらっしゃい

<audio controls>
<source src="02/116.mp3">
</audio><hr>

乾杯～

最高だなぁ

<audio controls>
<source src="02/117.mp3">
</audio><hr>

こんなに綺麗なのに、すぐに散っちゃうんだから

ホント　儚いよね

<audio controls>
<source src="02/118.mp3">
</audio><hr>

これ　試しに作って見たんだ

あ～美味しそう　いただきます

<audio controls>
<source src="02/119.mp3">
</audio><hr>

ちょっと、食べてばかないで

もっとお花見らしいことしようよ

<audio controls>
<source src="02/120.mp3">
</audio><hr>

お花見らしいこと？

歌うとか

僕歌下手

同じく

同じく

<audio controls>
<source src="02/121.mp3">
</audio><hr>

踊るとか

踊り？

踊るんですか

ダンスですか

フラダンス？

ベリーダンス？

腹ダンス？

<audio controls>
<source src="02/122.mp3">
</audio><hr>

ペンギンさん寝てる

違うよ、ダジャレどうしようもなくて倒れちゃったんだよ

<audio controls>
<source src="02/123.mp3">
</audio><hr>

ひどいなぁ、ペンギンさん

もっとあるでしょう！

お花見らしいこと、物真似とか

<audio controls>
<source src="02/124.mp3">
</audio><hr>

わ～～名倉さんの物真似でしょう

食べてるだけなのに

<audio controls>
<source src="02/125.mp3">
</audio><hr>

物足りないね

よし、しろくま君

僕をその木の上に挙げて　空を飛んでみせるよ

止めたほうがいいよ

<audio controls>
<source src="02/126.mp3">
</audio><hr>

なんで止めるの？

じゃパンダ君でいいよ

<audio controls>
<source src="02/127.mp3">
</audio><hr>

ほら、僕を木の上に乗せて

僕ラマですけど

酔ってますね

<audio controls>
<source src="02/128.mp3">
</audio><hr>

飲み過ぎじゃない

<audio controls>
<source src="02/129.mp3">
</audio><hr>

すごいすごい

お花見らしくなってきたよ、ペンギンさん

<audio controls>
<source src="02/130.mp3">
</audio><hr>

寝てる

熟睡ですね

寝るな

起きてるよ

<audio controls>
<source src="02/131.mp3">
</audio><hr>

最近の若いペンギンはなっちゃないんだよ

可愛いだけじゃダメなんだよ

そうでしょう

<audio controls>
<source src="02/132.mp3">
</audio><hr>

絡むね

聞いてる、吉崎さん

<audio controls>
<source src="02/133.mp3">
</audio><hr>

誰それ

吉崎さん、目の周りにあざがあるよ

誰かに殴られたよ？大丈夫？

<audio controls>
<source src="02/134.mp3">
</audio><hr>

面倒臭いな

ね～名倉さん、聞いてる？

食べてるだけなのに

<audio controls>
<source src="02/135.mp3">
</audio><hr>

誰にも言わないでね

何を

好きなペンギンがいるんだよ

<audio controls>
<source src="02/136.mp3">
</audio><hr>

パン屋のバイトのペンコさんっていうんだけど

ペンコさん！

<audio controls>
<source src="02/137.mp3">
</audio><hr>

僕パンダだよ

ペンコさん　一生僕と同じ魚を食べてください！

お願いします

<audio controls>
<source src="02/138.mp3">
</audio><hr>

助けて！

もう面白いから、見ていいよ

き、聞いてくれますか

<audio controls>
<source src="02/139.mp3">
</audio><hr>

何を

僕　ペンコさんのポエムを書いたんです

どんな？

<audio controls>
<source src="02/140.mp3">
</audio><hr>

theペンコさん

the？

ペンコさんが笑う

ペンコさんが歩く

ペンコさんが魚を食べる

どうですか、ペンコさん

僕？

<audio controls>
<source src="02/141.mp3">
</audio><hr>

ペンギンさん、ちょっとペンコさんと散歩してきたら、

え？いいの

じゃ、行こうか、ペンコさん

なんでまた僕？

<audio controls>
<source src="02/142.mp3">
</audio><hr>

ほら、行こう

二人きりのロマンチックな夜だね

いろいろ違ってる気がするよ

<audio controls>
<source src="02/143.mp3">
</audio><hr>

いつまでもこうして歩いていたいなぁ

帰りたいよ

ペンコさん！よかったら僕と付き合い……

あれ！吉崎さん、いつの間に

<audio controls>
<source src="02/144.mp3">
</audio><hr>

吉崎さんって誰

ペンコさん、どこ！ペンコさん！

ペンギンさん！

<audio controls>
<source src="02/145.mp3">
</audio><hr>

寝ている

<audio controls>
<source src="02/146.mp3">
</audio><hr>

お待たせ

コンビニ行ってきたよ

誰もいない

<audio controls>
<source src="02/147.mp3">
</audio><hr>

夜桜も綺麗だよ

<audio controls>
<source src="02/148.mp3">
</audio><hr>

昨日はびっくりしたね

毎年こうだから

ペンギンさんって酒癖悪いね

<audio controls>
<source src="02/149.mp3">
</audio><hr>

いらっしゃい

なんか頭が痛いよ

<audio controls>
<source src="02/150.mp3">
</audio><hr>

あれ　それでペンコさんのパン屋さんで買ったの

<audio controls>
<source src="02/151.mp3">
</audio><hr>

え？なんで知ってるの

theペンコさん

なんで僕のポエムを　なんで知ってるの

<audio controls>
<source src="02/152.mp3">
</audio><hr>

ペンコさん　一生僕と同じ魚を食べてください

僕が考えてるプロポーズの言葉！！

な　何でそれを！

<audio controls>
<source src="02/153.mp3">
</audio><hr>

覚えてないんですか

誰にも話してないのに

<audio controls>
<source src="02/154.mp3">
</audio><hr>

ペンコさんが笑う

ペンコさんが歩く

ペンコさんが魚を食べる

やめて

<audio controls>
<source src="02/155.mp3">
</audio><hr>

