---
title: '雑誌取材がやってきた'
---

雑誌取材がやってきた

<audio controls>
<source src="audio/15/001.mp3">
</audio><hr>

なんで　うまく いかないんだろう…

えっ？　なに？

あっ　あれ？ 縦列駐車？

<audio controls>
<source src="audio/15/002.mp3">
</audio><hr>

違うよ！

じゃあ　できるようになったの？

まだ　ちゃんと　できてないけど… 違うってば！

<audio controls>
<source src="audio/15/003.mp3">
</audio><hr>


僕が言いたいのは　デートだよ 

デートのお誘いだよ

<audio controls>
<source src="audio/15/004.mp3">
</audio><hr>

会って言えば いいんじゃないの？

それができないから 困ってるんだよ

なんで？

<audio controls>
<source src="audio/15/005.mp3">
</audio><hr>

もう　いい… パンダくんに 相談するんじゃなかった

シロクマさん！

<audio controls>
<source src="audio/15/006.mp3">
</audio><hr>

すみません 遅くなりました

どなたですか？

<audio controls>
<source src="audio/15/007.mp3">
</audio><hr>

取材の人ですよ

取材？

昨日　言ったじゃないですか

うん　知ってる

<audio controls>
<source src="audio/15/008.mp3">
</audio><hr>

『月刊　フラフラウォーカー』のライター 大崎と申します

よろしくね

何か？

あの…　編集長が 先に来ているはずなんですが

<audio controls>
<source src="audio/15/009.mp3">
</audio><hr>

編集長？　そういう方は まだ　お見えではないですね

そうですか… どうしたんだろう？

<audio controls>
<source src="audio/15/010.mp3">
</audio><hr>

実は こちらの　しろくまカフエを絶対　取り上げよう って言ったのは

うちの編集長なんですよ

<audio controls>
<source src="audio/15/011.mp3">
</audio><hr>

知る人ぞ知る隠れ処カフェや

オープンカフェを見つける勘がとても鋭くて

うちの雑誌は　編集長のセンスに 支えられているようなものです

聞いた？　

<audio controls>
<source src="audio/15/012.mp3">
</audio><hr>

雑誌の取材だって

取材？

いろいろ　インタビューしたり 写真撮ったりするんじゃない？

インタビュー？ 写真？

<audio controls>
<source src="audio/15/013.mp3">
</audio><hr>

ファンレターとか届いたりして

パンダくんの取材じゃないよ

お客さんに　インタビューしたら雑誌に写真載るよ

<audio controls>
<source src="audio/15/014.mp3">
</audio><hr>

えっ！？　それは困るよ！

僕写真写り自信ないんだよ　

<audio controls>
<source src="audio/15/015.mp3">
</audio><hr>

ああ…

じゃあ　とりあえず 取材を 始めさせていただきますね

まずはシロクマさんに

カフェを始めたいきさつなんかをお聞きしたいんですが

<audio controls>
<source src="audio/15/016.mp3">
</audio><hr>

いきさつ…

それは　力作

それは　印刷

それは　警察

それは　改札

<audio controls>
<source src="audio/15/017.mp3">
</audio><hr>

あ…　えっと…　そのダジャレは…

それは　挨拶！！

かぶせてきましたね編集長

<audio controls>
<source src="audio/15/018.mp3">
</audio><hr>

マスターはダジャレが得意なナイスガイ…　と

編集長？

はい　うちの編集長 ハシビロコウさんです

<audio controls>
<source src="audio/15/019.mp3">
</audio><hr>

ですよね！ ホント今回大当たりです

編集長が　本当に ここは　すばらしいカフェだと

<audio controls>
<source src="audio/15/020.mp3">
</audio><hr>

あっ　そう

それでは　改めまして

挨拶ならぬ カフェを始めたいきさつですが

やっぱ　聞いちゃうんだ　それ

なんで？

話せば長くなるんだけど

<audio controls>
<source src="audio/15/021.mp3">
</audio><hr>

僕はカナダのハドソン湾で生まれたの

僕は三つ子のいちばん下で いちばん体が小さかった

お母さんが食べ物を探して歩くと

いつも僕だけ遅れてしまった

<audio controls>
<source src="audio/15/022.mp3">
</audio><hr>

そして　ある吹雪の日

僕はとうとう お母さんたちと はぐれてしまった

<audio controls>
<source src="audio/15/023.mp3">
</audio><hr>

吹雪がやむと…

お母さんたちの姿はどこにもなかった

一生懸命呼んだけど 応えはない

<audio controls>
<source src="audio/15/024.mp3">
</audio><hr>

そのうち気づいた

僕のいる氷は沖へ流されてる

僕はひとりぼっちで海の上を漂流していった

<audio controls>
<source src="audio/15/025.mp3">
</audio><hr>

何日も　何日も…

そ…　それで どうなったの？

お腹が減って ついに動けなくなったとき

<audio controls>
<source src="audio/15/026.mp3">
</audio><hr>

僕は通りがかった猟師の人に助けられたんだ

<audio controls>
<source src="audio/15/027.mp3">
</audio><hr>

それから　僕は助けてくれた人の両親に預けられた

そこは小さな食堂をやっていて

店を手伝ううちに

僕は料理が好きになった

<audio controls>
<source src="audio/15/028.mp3">
</audio><hr>

でも　そんな生活も長くは続かなかったよ

僕は　大きくなりすぎて

おじいさんと　おばあさんの家にいられなくなってしまったんだ

<audio controls>
<source src="audio/15/029.mp3">
</audio><hr>

それで家を出て

カフェを始めた

お店をやっていたら いつか話が伝わって

お母さんたちに会えるかもしれないから

<audio controls>
<source src="audio/15/030.mp3">
</audio><hr>

なに！？

わかります 編集長

シロクマさんの大変さを思うと…

シロクマくん

<audio controls>
<source src="audio/15/031.mp3">
</audio><hr>

大変だったんだね

お母さんたちには まだ会えないの？

うん

<audio controls>
<source src="audio/15/032.mp3">
</audio><hr>

今のところ

あれ？　私この前は建設会社を脱サラして

カフェを始めたって 聞いたんですけど…

<audio controls>
<source src="audio/15/033.mp3">
</audio><hr>

ああ… そういうバージョンもあるね

作り話ですか

だから言ったのに

<audio controls>
<source src="audio/15/034.mp3">
</audio><hr>

ははぁ　真相は お好みってことですね

さすがナイスガイ

じゃあ　次の質問ですが…

<audio controls>
<source src="audio/15/035.mp3">
</audio><hr>

どうしました！？　編集長！

ああ　そのお花ですね

このステキなアレンジメントはどなたが？

<audio controls>
<source src="audio/15/036.mp3">
</audio><hr>

近くの花屋さんに お願いしてるんです

編集長？

編集長！

編集長！

<audio controls>
<source src="audio/15/037.mp3">
</audio><hr>

編集…

これは！

自家菜園です

お店で使う野菜やハーブを 育てているんですよ

さすが編集長！ どんなことも見逃しませんね

<audio controls>
<source src="audio/15/038.mp3">
</audio><hr>

こだわりの食材

景色も良好

客席も充実

洗練された外観

<audio controls>
<source src="audio/15/039.mp3">
</audio><hr>

そんなステキなしろくまカフェさんなんですが

オススメがあれば ぜひ紹介していただけますか？

笹大盛りがオススメだよ！

<audio controls>
<source src="audio/15/040.mp3">
</audio><hr>

それ　料理じゃなくて素材だよね

あぁ　家の隣にあってすぐ来られるのもオススメ

パンダくんだけでしょ

素材と立地が抜群　と…

その他は？

<audio controls>
<source src="audio/15/041.mp3">
</audio><hr>

ランチパスタが人気ですね

うん　うん… アンチョビの入ったやつね

春野菜も　いいよね

せっかくだから 食べてもらったら　どうでしょう？

<audio controls>
<source src="audio/15/042.mp3">
</audio><hr>

どうですか？　編集長

パスタ　嫌いなのかな？

<audio controls>
<source src="audio/15/043.mp3">
</audio><hr>

意外とダイナミックだよね

そうですか！ とっても　おいしいそうです

あぁ　そう

<audio controls>
<source src="audio/15/044.mp3">
</audio><hr>

えっ！？ この間の雑誌もう出たの？

うん　サンプルが来てる

見せて　見せて！

あっ！　これだね

<audio controls>
<source src="audio/15/045.mp3">
</audio><hr>

写ってない…

写ってる…

ですね

<audio controls>
<source src="audio/15/046.mp3">
</audio><hr>


