---
title: "女子高生とリンリン"
---

<span id="episode-title" data-episode="34"> 女子高生とリンリン </span> 

<audio></audio><hr>

笹子さん　人間の鼻の下の溝は 何のためにあるの？

さぁ　よく知りません

<audio></audio><hr>

ペンギンさん　ペンギンさん 何　パンダくん

ペンギンさんって カフェでいつもダラダラしてるけど

たまには僕みたいに ちゃんと働いたほうがいいよ

<audio></audio><hr>

キミに言われたくないってことで いいかな

そういうパンダくんこそ 今日バイトじゃないの？

午後からだよ

<audio></audio><hr>

週２は　キツイから 午後からにしたんだ

よくクビにならないね

<audio></audio><hr>

あれ　パンダくん来てたの

え　何？

はい　これ　パンダくんに

<audio></audio><hr>

何　今日パンダの日

何の日それ

シロクマくん　これどうしたの？

さっき…

パンダくんに 渡してください

って頼まれた

<audio></audio><hr>

あげる

またリンリンだよ

あの花屋さん

うん　僕に何の恨みがあるんだろう

<audio></audio><hr>

花くれてるだけじゃない

パンダくん　喜んでくれたかな？

あっ… 厘太郎さんだ…

いらっしゃいませ

<audio></audio><hr>

あっ…　これください

すみません　これください

<audio></audio><hr>

ありがとうございました

厘太郎さん いつ見ても　ステキ…

<audio></audio><hr>

あの…　何か？

あっ…　いえ…

あの…　また来ます

<audio></audio><hr>

キミ！

はい？

今から　僕に つきあってくれないかな？

<audio></audio><hr>

えっ！？ど…　ど…　ど…　どうしよう…

厘太郎さんに誘われちゃった

これって…　デート？ ど…　ど…　ど…　どうしよう…

でも　どうして私なんて…

<audio></audio><hr>

あんなステキな女の人たちが たくさんいるのに

あっ…　地味さ？

女子高生の地味さが勝ったの？

<audio></audio><hr>

デート…　厘太郎さんが 私を　デートに…

大丈夫？　行ける？

はい！！

<audio></audio><hr>

センスがいい 厘太郎さんのことだから

きっと　すごくステキなところに…

<audio></audio><hr>

は～い　みんな ゾウさんですよ

え～っと…

どうしたの？

あっ…　いえ　意外で…

<audio></audio><hr>

じゃあ　行こうか

はい！

<audio></audio><hr>

あの…　厘太郎さん

何？

いえ…

どうしたの？ 何でも聞いていいよ

<audio></audio><hr>

あの…　厘太郎さんの恋人って　ステキな人なんでしょうね

恋人は　いないんだ

<audio></audio><hr>

えっ…　そうなんですか？

うん

<audio></audio><hr>

でも　僕を 夢中にさせてくれる人はいるよ

それって　もしかして…

<audio></audio><hr>

と…　歳の差は　いいんですか？

歳の差？　そういうのは 考えたことないな

私も…

その人って どんな人なんですか？

<audio></audio><hr>

白と黒が　かわいくて…

制服？　制服フェチ？

いい…　それでも　全然いい！

<audio></audio><hr>

フサフサしてて…

これだ！　ツインテだ

偉い！　偉いよ　私！

ポッチャリしてて…

ポテチだ… ポテチを食べすぎた…

ダメ…　ダメよ　私…

ゴロゴロしてる姿が たまらなくて…

えっ！？ 盗撮？　盗撮されてる！？

<audio></audio><hr>

そんな…　パンダくんに最高に夢中なんだ

<audio></audio><hr>

パンダ…

うん　パンダ

リンリン　また来てる

ねぇ　ねぇ　キミ　ちょっと　これ　お願い

<audio></audio><hr>

ありがとう！

パンダくんと一緒に撮った写真 初めてだよ！

キミに来てもらって　よかったよ

いえ…

キミ　パンダ好きでしょ？　それ見て　すぐわかったよ

<audio></audio><hr>

パンダ好きは パンダ好きを知るんだよね

ねっ！

なに　このテンション…

本当に　あの厘太郎さん？

<audio></audio><hr>

けど…　パンダで厘太郎さんと 仲よくなれるなら

わぁ　かわいい！

違う違う

<audio></audio><hr>

かわいいのは あっちのパンダさんじゃなくて　こっちのパンダくん！

ち…　違うんですか？

<audio></audio><hr>

全然　違うよ

いいかい？　よ～く見てごらん

<audio></audio><hr>

ボーッとしてないで見て

は…　はい！

あっちのパンダさんと　こっちのパンダくん

あっちのパンダさんと　こっちのパンダくん

<audio></audio><hr>

ねっ！

全然　違いがわからない…

<audio></audio><hr>

けど…

本当　こっちのパンダのが　かわいい

でしょ～！

キミ！

はい！

<audio></audio><hr>

一緒に　パンダくんの どこがかわいいか

小一時間　語り合わないか？

<audio></audio><hr>

愛くるしいよね

あのモフモフした顔見た？

僕は見たよ！　どうしよう！？

あんな かわいいものってあるかな？

ない！　ないよ！

できるならパンダコーナーで パンダくんと一緒に住みたいよね

<audio></audio><hr>

いいな　それ！　どうしよう

ああ　だけど パンダくん　週２日のバイトだから

それ以外のときはパンダコーナーでパンダ…

帰りたい…

<audio></audio><hr>

パンダくんの かわいい転がってる姿を間近で見られるなんて 最高だよね！

…転がってるパンダくんも可愛いんだよ

帰りたい…

滑り台を滑ってるパンダ君もとびきり可愛いよね

閉園の時間になりました

またのご来園を…

閉園時間だね

ごめんね　長くなっちゃったね

<audio></audio><hr>

い…　いえ

はぁ…　助かった

じゃあ　そろそろ

はい！

場所変えて　続きを話そう

<audio></audio><hr>

すげぇ　この人…

<audio></audio><hr>

どこに行こうか？

あっ　いえ　あの 私　宿題あるから　失礼します！

ああ　キミ　ちょっと待って！

パンダくんの話しようよ！

<audio></audio><hr>

あげます！

いいの？　ありがとう！ 一生　恩に着るよ！

いいです 一生というほどのものでは…

<audio></audio><hr>

大事にするよ

すごい嬉しい！

<audio></audio><hr>

さようなら！

あっ！　ああ　キミ！

さようなら！　私の恋！

<audio></audio><hr>

またパンダの話しようね！

さようなら　私の恋！

これ　返せって言っても 返さないからね！

<audio></audio><hr>

お疲れ

アイスコーヒー？

うん

やっぱり 労働って半日もきついな

なんとか 半日の半分にしてもらおう

<audio></audio><hr>

キミ　クビになってもいいのにね

なんで？

あっ　リンリンの花！ どっかにやってよ

<audio></audio><hr>

まぁまぁ　きれいな花じゃない

<audio></audio><hr>



