---
title: "半田さんの合コン？"
---

半田さんの合コン？

<audio>
<source src="audio/19/001.mp3">
</audio><hr>

すみませんでした

どうしたの？

<audio>
<source src="audio/19/002.mp3">
</audio><hr>

いつものって頼んだらさ

餃子が出てきたんだよ

僕　カフェで餃子頼んだことあった？

<audio>
<source src="audio/19/003.mp3">
</audio><hr>

ありませんでしたっけ？

ないでしょ

餃子…　メニューにないでしょ

はい…

<audio>
<source src="audio/19/004.mp3">
</audio><hr>

わざわざ　作ったの？

はい

笹子さん　偉い！

<audio>
<source src="audio/19/005.mp3">
</audio><hr>

褒めるところかな？

おいしいよ

ホントですか？

喜ぶところかな！？

<audio>
<source src="audio/19/006.mp3">
</audio><hr>

まぁ　いいや　いつものくれる？

うん

<audio>
<source src="audio/19/007.mp3">
</audio><hr>

何　これ

餃子定食

頼んだことある？

ないね

<audio>
<source src="audio/19/008.mp3">
</audio><hr>

遊んでる？

うん

はぁ…　疲れた

バイト　お疲れ

<audio>
<source src="audio/19/009.mp3">
</audio><hr>

いつものちょうだい

いつものね

笹子さん　餃子定食

はい　

<audio>
<source src="audio/19/010.mp3">
</audio><hr>

竹大盛りとアイスコーヒーね

ねぇねぇ　聞いてよ　今日ね…

<audio>
<source src="audio/19/011.mp3">
</audio><hr>

え～？　もう　こんな時間？

まだ眠いよ もうちょっと寝よう

<audio>
<source src="audio/19/012.mp3">
</audio><hr>

ちょっと待って！

二度寝の話がしたいの？

<audio>
<source src="audio/19/013.mp3">
</audio><hr>

どっから話そうかなと思って

もうちょっと　まとめてから 話してくれる？

<audio>
<source src="audio/19/014.mp3">
</audio><hr>

ヒマじゃないんだから

うん　わかった

<audio>
<source src="audio/19/015.mp3">
</audio><hr>

桐野君　おはよう

おはよう　パンダ君

って…　早くないよ　遅刻だよ？

<audio>
<source src="audio/19/016.mp3">
</audio><hr>

半田さんのお弁当だ 開けてみよう

ダメだよ　パンダ君

<audio>
<source src="audio/19/017.mp3">
</audio><hr>

ちょっと開けるだけだよ

ダーメ！

<audio>
<source src="audio/19/018.mp3">
</audio><hr>

ダメだからね

<audio>
<source src="audio/19/019.mp3">
</audio><hr>

開けるだけだよ

<audio>
<source src="audio/19/020.mp3">
</audio><hr>

なんて　茶色いお弁当なんだろう

おばあちゃんのお弁当みたいだ

<audio>
<source src="audio/19/021.mp3">
</audio><hr>

ちょっと待って！

お弁当の話がしたいの？

もう まだ　話してる途中なんだから

<audio>
<source src="audio/19/022.mp3">
</audio><hr>

頼むよ！ ヒマじゃないって言ってるでしょ

ヒマでしょ？

<audio>
<source src="audio/19/023.mp3">
</audio><hr>

いつも　ここにいるじゃない

ペンギンさんって ふだん　何してんの？

<audio>
<source src="audio/19/024.mp3">
</audio><hr>

い…　いいから 早く本題に入ってよ

わかったよ

<audio>
<source src="audio/19/025.mp3">
</audio><hr>

パンダ君　今日は午後から小学生の団体が来るから

サービスしようね

<audio>
<source src="audio/19/026.mp3">
</audio><hr>

はい　いつもより多めに　ゴロゴロしま～す

<audio>
<source src="audio/19/027.mp3">
</audio><hr>

ねぇ　常勤パンダさん

何？

今日　半田さんの お弁当見ちゃったんだけどね

<audio>
<source src="audio/19/028.mp3">
</audio><hr>

茶色くてさ　おばあちゃんの お弁当みたいだったよ

おいしかったけど

<audio>
<source src="audio/19/029.mp3">
</audio><hr>

食べちゃったの？

うん

食べちゃったの…

うん！

<audio>
<source src="audio/19/030.mp3">
</audio><hr>

お弁当おいしかったけど 何ていうのかな…

<audio>
<source src="audio/19/031.mp3">
</audio><hr>

男が男のために 作ったお弁当というか

まぁ　半田さんが 自分のために作った弁当だからね

<audio>
<source src="audio/19/032.mp3">
</audio><hr>

というより　おばあちゃんが おばあちゃんのために作ったお弁当というか

<audio>
<source src="audio/19/033.mp3">
</audio><hr>

ひと言でいうと　モテなさそう

モテなさそうなお弁当なんだよね

<audio>
<source src="audio/19/034.mp3">
</audio><hr>

見たかったな そのモテなさそうな弁当

聞こえてますよ

聞こえるように言ったんだよ

<audio>
<source src="audio/19/035.mp3">
</audio><hr>

半田さん　今度そのモテなさそうな弁当私にも見せてよ

<audio>
<source src="audio/19/036.mp3">
</audio><hr>

ちょっと　失礼だな

じゃあ　モテるの？

<audio>
<source src="audio/19/037.mp3">
</audio><hr>

最近　女性と喋った？

何　急に

だから

<audio>
<source src="audio/19/038.mp3">
</audio><hr>

最近　女性と喋った？

お母さん以外だよ

<audio>
<source src="audio/19/039.mp3">
</audio><hr>

動物以外だよ

<audio>
<source src="audio/19/040.mp3">
</audio><hr>

ほらね

おかしいな

そんなモテない半田さんのために

僕が桐野くんに頼んでおいたから

<audio>
<source src="audio/19/041.mp3">
</audio><hr>

え　何を

半田さん！

決まりましたよ

何だ？

<audio>
<source src="audio/19/042.mp3">
</audio><hr>

合コンですよ 半田さんがやりたいって　パンダくんが

俺言ってないよ

<audio>
<source src="audio/19/043.mp3">
</audio><hr>

そんなの行かないよ

ちょっと待ってくださいよ

半田さんのために セッティングしたんですから

<audio>
<source src="audio/19/044.mp3">
</audio><hr>

相手は　ＯＬさんですよ

俺　忙しいから

何かあるんですか？

帰って風呂の掃除しないと

<audio>
<source src="audio/19/045.mp3">
</audio><hr>

それは忙しいに入りませんよ

行くよね　半田さん

<audio>
<source src="audio/19/046.mp3">
</audio><hr>

桐野くん　半田さんをよろしくお願いします

もう　勝手に決めないで

<audio>
<source src="audio/19/047.mp3">
</audio><hr>

行きましょうよ　半田さん

半田さん！

かわいくてもダメ！

<audio>
<source src="audio/19/048.mp3">
</audio><hr>

桐野くんはね パンダくんに言われて

半田さんのために やったこともない合コンをセッティングしたんだよ

<audio>
<source src="audio/19/049.mp3">
</audio><hr>

ちょっとくらいは やったことありますけど

<audio>
<source src="audio/19/050.mp3">
</audio><hr>

半田さん行こうよ！

もういいよ　２人とも

<audio>
<source src="audio/19/051.mp3">
</audio><hr>

わかりました　

半田さんが どうしても嫌なら　断ります

<audio>
<source src="audio/19/052.mp3">
</audio><hr>

わかった　行くよ

ホントですか！

よかった

<audio>
<source src="audio/19/053.mp3">
</audio><hr>

男性チームは　僕の友人が来て ３対３です

じゃあ　今晩７時ですから

<audio>
<source src="audio/19/054.mp3">
</audio><hr>

半田さん　ＯＬさんにお弁当見せちゃダメだよ

見せないよ

<audio>
<source src="audio/19/055.mp3">
</audio><hr>

お疲れ様

今日　合コン頑張ってね

シーッ！

<audio>
<source src="audio/19/056.mp3">
</audio><hr>

声が大きいよ

ごめん　ごめん

じゃあ　また明日

<audio>
<source src="audio/19/057.mp3">
</audio><hr>

これで 半田さんのお弁当も変わるな

えっ　ウソ　ホントに？

<audio>
<source src="audio/19/058.mp3">
</audio><hr>

そうか　わかった

困ったな

どうしたの？

<audio>
<source src="audio/19/059.mp3">
</audio><hr>

今日の合コンなんだけど 友達が来られなくなっちゃって

<audio>
<source src="audio/19/060.mp3">
</audio><hr>

今からじゃ　メンバー見つからないよ

桐野くん

<audio>
<source src="audio/19/061.mp3">
</audio><hr>

大丈夫だよ

僕にあてがあるから

ホント？

うん　任せておいて

<audio>
<source src="audio/19/062.mp3">
</audio><hr>

ありがとう パンダくん　ありがとう

<audio>
<source src="audio/19/063.mp3">
</audio><hr>

そういうわけなんだ

ふ～ん　話はわかった

要するに 合コンのメンバーが必要なんだね

<audio>
<source src="audio/19/064.mp3">
</audio><hr>

それでシロクマくんを誘おうと思うんだけど　どう思う？

えっ！？　僕じゃなくて？

シロクマくん　今日　ヒマ？

<audio>
<source src="audio/19/065.mp3">
</audio><hr>

今日　ヒマ？

僕じゃないんだ…

僕　結構　話　聞いてたのに

<audio>
<source src="audio/19/066.mp3">
</audio><hr>

ペンギンさん　さっきから ヒマじゃない　ヒマじゃないって…

<audio>
<source src="audio/19/067.mp3">
</audio><hr>

いや　まあ　そうだけど…

やりくりすれば　合コンに行けないことも ないんじゃないかな

<audio>
<source src="audio/19/068.mp3">
</audio><hr>

ヒマじゃないんでしょ？

ああ　僕　ヒマじゃないからね

じゃ　楽しんでくれば？

<audio>
<source src="audio/19/069.mp3">
</audio><hr>

パンダくんにシロクマさん？

どうして…

今日の男性チームです

<audio>
<source src="audio/19/070.mp3">
</audio><hr>

半田さん　頑張ろうね

<audio>
<source src="audio/19/071.mp3">
</audio><hr>

半田さん　すみません 頑張りましょうね

じゃあ　行こうか

後半へつづく

<audio>
<source src="audio/19/072.mp3">
</audio><hr>

