---
title: "ペンギンさんの告白"

---

ペンギンさんの告白

<audio>
<source src="audio/18/001.mp3">
</audio><hr>

クロワッサンもいけるね

これに竹の葉を練りこんだら もっと　おいしくなるんじゃない？

<audio>
<source src="audio/18/002.mp3">
</audio><hr>

それはどうかな？

それより　パンダあんぱん っていうのが　あるみたいだよ

<audio>
<source src="audio/18/003.mp3">
</audio><hr>

本当？　

ねぇ　ペンギンさん 次は　そのパンダあんぱんを…

あぁ　もう…

僕は　別にパンを買うためにパン屋さんに 行ってるわけじゃないんだよ！

ペン子さんを…　その…

<audio>
<source src="audio/18/004.mp3">
</audio><hr>

デートに誘いたいんだよ…

知ってるよ　そんなの

でも　結局　いつも　パンを 買って帰ってくるだけじゃない

だって…

<audio>
<source src="audio/18/005.mp3">
</audio><hr>

いっそ　告白しちゃったら どうです？

そ…　そんな！

小さな１歩を恐れるときは

大きな１歩を踏み出すときである

<audio>
<source src="audio/18/006.mp3">
</audio><hr>

フランスの古い格言だよ

大きな１歩を踏み出すとき…

ウソだけど

小さな１歩　

<audio>
<source src="audio/18/007.mp3">
</audio><hr>

大きな１歩…

決めた！　僕は　やるよ

やるって　まさか…

ペン子さんに告白する！

<audio>
<source src="audio/18/008.mp3">
</audio><hr>

告白？

ごめん！　今の僕は ダジャレにつきあってる暇はないの

早速　行ってくるよ！

<audio>
<source src="audio/18/009.mp3">
</audio><hr>

行っちゃった…

ヒャッハー！

それは　極悪？

<audio>
<source src="audio/18/010.mp3">
</audio><hr>

でも　どうやって言おう？

ノープランなの？

当たり前でしょ！

さっき　思い立ったんだから

どうしたらいいかな？

<audio>
<source src="audio/18/011.mp3">
</audio><hr>

例えばクジャクは羽を広げて愛の告白をするよね

なるほど！

こんな感じ？

<audio>
<source src="audio/18/012.mp3">
</audio><hr>

地味だね

じゃあ…　他には！？

グンカンドリは赤いノド袋を膨らますらしいよ

<audio>
<source src="audio/18/013.mp3">
</audio><hr>

あんまり変わりませんね

もっと膨らまないの？

リクガメは甲羅アタック

<audio>
<source src="audio/18/014.mp3">
</audio><hr>

噛みつき マウントだよ

え～　プロレス？

噛みつきは反則じゃないんですか？

ワルだね　かっこいい！

あれ？ でも　ペンギンさん　甲羅ないよ

<audio>
<source src="audio/18/015.mp3">
</audio><hr>

お皿　付けたら？

カッパ？

カッパって　なんて言って 告白するの？

<audio>
<source src="audio/18/016.mp3">
</audio><hr>

ちょっと！　まじめに考えてよ！

はぁ…　もう　どうしていいか わからないよ

最悪だ　世界の終わりだ

<audio>
<source src="audio/18/017.mp3">
</audio><hr>

や…　やっぱり　好きです　って シンプルなのがいちばんですよ

あからさますぎない？

それじゃあ 好きって　バレちゃうよ～！

告白するんじゃないんですか？

はっ…　そうだった

<audio>
<source src="audio/18/018.mp3">
</audio><hr>

わかった　シンプルに頑張るよ

それじゃあ　行こうか

ついてくる気！？

<audio>
<source src="audio/18/019.mp3">
</audio><hr>

昔の武将は　こう言った

１本の矢なら折れるが ３本の矢なら折れない　と

<audio>
<source src="audio/18/020.mp3">
</audio><hr>

え～っと… 三人寄れば　文殊の知恵

モンキーの知恵？

それじゃあ 猿知恵になっちゃうよ

<audio>
<source src="audio/18/021.mp3">
</audio><hr>

一人で大丈夫だから 来ないでね！

うまくいくといいですね

あ…　あれ？

<audio>
<source src="audio/18/022.mp3">
</audio><hr>

す…　好きです！

これ　受け取ってください

よ～し…　言える！　言えるぞ！

行くぞ…　よし　行くぞ！

<audio>
<source src="audio/18/023.mp3">
</audio><hr>

す…　好きです！ これ　受け取ってください！

よし！

す…　好きです　ペン子さん！

これ　受け取ってください！

す…　好きです！

<audio>
<source src="audio/18/024.mp3">
</audio><hr>

好きです これ　受け取ってください！

あれ　何？　何かのおまじない？

恋する者は

それが 意味のない行為だとしても

<audio>
<source src="audio/18/025.mp3">
</audio><hr>

幾度となく繰り返してしまう

また　古い格言？

ううん　いずれペンギンさんが作る未来の格言

<audio>
<source src="audio/18/026.mp3">
</audio><hr>

やっぱり　僕に告白なんてムリなのかなぁ…

<audio>
<source src="audio/18/027.mp3">
</audio><hr>

もし　彼女が僕の愛を受け入れてくれたら…

嬉しいよ　ペン子さん

<audio>
<source src="audio/18/028.mp3">
</audio><hr>

嬉しいよ　ペン子さん！

おいしいよ　ペン子さん！

嬉しいよ…　イテッ！

あ…　しまった！

<audio>
<source src="audio/18/029.mp3">
</audio><hr>

いけない　いけない 夢の世界に浸ってしまった

でも 夢が現実になる可能性はある！

そのためにも頑張らなくっちゃ！

<audio>
<source src="audio/18/030.mp3">
</audio><hr>

あ～　よかった　行ったよ

うん　よかった

<audio>
<source src="audio/18/031.mp3">
</audio><hr>

僕は言う　言うよ！

ペン子さ…

<audio>
<source src="audio/18/032.mp3">
</audio><hr>

ペンギンさん　なかなか起きないね

もう帰ろうかな

<audio>
<source src="audio/18/033.mp3">
</audio><hr>

あれ？　僕…　

そうだ！ ペン子さんに告白！

でも　今日はやっぱやめとこうかな

なんか空回りしてる感じだし…

いや！　

<audio>
<source src="audio/18/034.mp3">
</audio><hr>

思い立ったが吉日！

けどなぁ なんか調子悪い気もするしな…

いやいや そんなこと言ってちゃダメだ！

でもなぁ…

<audio>
<source src="audio/18/035.mp3">
</audio><hr>

ねぇ　まだ？

待ちくたびれたよ

えっ！？　なんで２人ともいるの？

来ないでって言ったのに！

<audio>
<source src="audio/18/036.mp3">
</audio><hr>

早くしてよ 僕　もう　お腹すいたよ

知らないよ！

しないの？　告白

<audio>
<source src="audio/18/037.mp3">
</audio><hr>

そ…　それは…

古きローマの詩人は言った

幸運と愛は勇者とともにあり

勇者とともに？

<audio>
<source src="audio/18/038.mp3">
</audio><hr>

幸運も愛も　その勇者って人の ところにあるってことだね

今から行こう

行くのは　ペン子さんのところ！

<audio>
<source src="audio/18/039.mp3">
</audio><hr>

そうなの？

よ～し　いくぞ！

…って　２人とも ついてこないで！

言うぞ　言うぞ！

<audio>
<source src="audio/18/040.mp3">
</audio><hr>

なんで いざっていうとき邪魔するの！？

パンダあんパンが気になっちゃって

わかったよ！ 買ってきてあげるよ！

だから帰ってよ！ ほら　帰って帰って！

<audio>
<source src="audio/18/041.mp3">
</audio><hr>

あの…

あっ　あの…

大丈夫かな？　ペンギンさん

<audio>
<source src="audio/18/042.mp3">
</audio><hr>

お～い！

やった！　やったよ～！

おめでとう　ペンギンさん

<audio>
<source src="audio/18/043.mp3">
</audio><hr>

へぇ～　じゃあ うまくいったんですね

いやぁ　ホントまいっちゃう

それで　ペン子さんは何て？

<audio>
<source src="audio/18/044.mp3">
</audio><hr>

うん？　知りたい？

もう　詳しく教えてくださいよ

実はね　ペン子さん僕の顔を 覚えててくれたみたいでね

<audio>
<source src="audio/18/045.mp3">
</audio><hr>

「よかったら　どうぞ」って　これ！

なんと　サービス券もらったの！

<audio>
<source src="audio/18/046.mp3">
</audio><hr>

ちょっと多めにって３枚も

ねっ　サービス券をサービスだよ！

あの…　告白は？

<audio>
<source src="audio/18/047.mp3">
</audio><hr>

それどころじゃないよ！

なんと受け取るときにちょっと手が触れちゃったんだよ

どうしよう　もう手洗わない！

洗えないよ！　洗いたくないよ！

<audio>
<source src="audio/18/048.mp3">
</audio><hr>

１枚のサービス券は　サービス券だが

３枚なら…　やっぱりサービス券だ

それを言っちゃダメですよ

パンダくん聞いてる？

聞いてるよ

笹子さん　ほら！

もう　幸せ！

<audio>
<source src="audio/18/049.mp3">
</audio><hr>
