---
title: "海に行こう"
---

海に行こう

<audio>
<source src="audio/28/001.mp3">
</audio>




<hr>

いらっしゃいませ

あれ　今日白熊君は

お出かけなんですよ

<audio>
<source src="audio/28/002.mp3">
</audio>



<hr>

やってきました　海

海

夏は海だよね

<audio>
<source src="audio/28/003.mp3">
</audio>



<hr>

ペンギンさん　どう　このシャツおニュウなんだ

パンダ君　普段何にも着てないのに

シーンにあわせた装い

何のシーンなんだか

<audio>
<source src="audio/28/004.mp3">
</audio>
<div>

<hr>

早く着替えて泳ごう

ええ　もっとゆっくりしようよ　白熊君

<audio>
<source src="audio/28/005.mp3">
</audio>

<hr>

あれ　パンダや

ほんまや　海にパンダがいてるわ

アロハ着て　可愛らしいな

これからどこ行くん

飴ちゃ　あげようか

ありがとう

<audio>
<source src="audio/28/006.mp3">
</audio>

<hr>

ほなな　気ィつけてな

モテモテだよ

あれ　白熊君は

あっち

<audio>
<source src="audio/28/007.mp3">
</audio><hr>

素敵　

かっこいい

モテモテだね

<audio>
<source src="audio/28/008.mp3">
</audio><hr>

白熊君　早く行かないと日が暮れちゃうよ

さっきまでゆっくりしようって言ってたのに

<audio>
<source src="audio/28/009.mp3">
</audio><hr>

やっぱり着替えるんだ

ペンギンさんこそ　いつも同じで飽きないの

パンダ君だっていつもは大体同じじゃない

<audio>
<source src="audio/28/010.mp3">
</audio><hr>

まず　何しようか

僕　魚とりに行く

僕はお昼寝

<audio>
<source src="audio/28/011.mp3">
</audio><hr>

いい波だね

皆　ばらばらだな

<audio>
<source src="audio/28/012.mp3">
</audio><hr>

せっかく皆で来てるんだからさ

一緒になんかやろうよ

<audio>
<source src="audio/28/013.mp3">
</audio><hr>

あっちでシーカヤックを貸してくれるらしいよ

何それ

知らないけど　やりたい

<audio>
<source src="audio/28/014.mp3">
</audio><hr>

うん　見渡す限りの水平線　気持ちがいいね

難しいよ白熊君　どうやるの

<audio>
<source src="audio/28/015.mp3">
</audio><hr>

水面深くまでパドルを入れないで

利き手側のブレード引き押せたら 同時に反対側を押し出す

<audio>
<source src="audio/28/016.mp3">
</audio><hr>

両肩のラインよりひじが回らないように

むしろ腰を回転…

もっと簡単に言ってくれる

<audio>
<source src="audio/28/017.mp3">
</audio><hr>

ペンギンさんがいつも泳ぐときみたいに

よーし

<audio>
<source src="audio/28/018.mp3">
</audio><hr>

ね　見た　パンダ君

飽きたよ

はやっ

<audio>
<source src="audio/28/019.mp3">
</audio><hr>

海しか見えないし　動かないよ

海に来てるんだし　漕いでないから当たり前じゃない

こがなくていいやつ　乗る

<audio>
<source src="audio/28/020.mp3">
</audio><hr>

次は　何しようか

やっぱり砂浜でまったりがいいよ

のんびり干物作り

ウクレレ弾こうっと

<audio>
<source src="audio/28/021.mp3">
</audio><hr>

ねえ　僕の体を作ってよ

どんなの

マッチョでね　セクシーな感じがいいな

<audio>
<source src="audio/28/022.mp3">
</audio><hr>

前に言ってた　逆三角形の足の長いやつ

呼ばれて飛び出た　ドリームパンダ

<audio>
<source src="audio/28/023.mp3">
</audio><hr>

あれよりごつい感じ

でもむきむきすぎないの

注文多いな

任せて

<audio>
<source src="audio/28/024.mp3">
</audio><hr>

どう

お相撲さんだね

ごつくてむきむきすぎない

やだ

<audio>
<source src="audio/28/025.mp3">
</audio><hr>

任せて

ごつ過ぎるよ

<audio>
<source src="audio/28/026.mp3">
</audio><hr>

もっとかっこいいのがいいな

任せて

<audio>
<source src="audio/28/027.mp3">
</audio><hr>

かっこいいけど違う

モテモテがいい

任せて

<audio>
<source src="audio/28/028.mp3">
</audio><hr>

これってモテモテ

うん　皆でお祝いしてるし

僕　必要

次は何しようか

<audio>
<source src="audio/28/029.mp3">
</audio><hr>

誰がやる

白熊君　やりなよ

いいの

<audio>
<source src="audio/28/030.mp3">
</audio><hr>

何遠慮してるの

そうじゃなくて

<audio>
<source src="audio/28/031.mp3">
</audio><hr>

目隠ししても分かっちゃうんだよ

鼻がいいから

<audio>
<source src="audio/28/032.mp3">
</audio><hr>

じゃあ　パンダ君

よーし

パンダ君　寝てる

パンダ君に目隠しはダメだね

<audio>
<source src="audio/28/033.mp3">
</audio><hr>

右だよ　ペンギンさん

右ってどれぐらい

上半身を30度右にねじって　僅かに前傾姿勢をとる

<audio>
<source src="audio/28/034.mp3">
</audio><hr>

そして　腕を目の高さに当てて…

もっと簡単に言ってくれる

<audio>
<source src="audio/28/035.mp3">
</audio><hr>

真ん前

そこだよ　ペンギンさん

ホント

<audio>
<source src="audio/28/036.mp3">
</audio><hr>

ペン子さんにアタックするつもりで

<audio>
<source src="audio/28/037.mp3">
</audio><hr>

ペン子さん

あの　え　ペン子さん　干物がお好きですか　

僕は好きです

あの　干物が好き　というかペン子さんも　いいえ

ペン子さんが　あ

ぺぺぺぺぺ　ペン子さん

<audio>
<source src="audio/28/038.mp3">
</audio><hr>

ペン子さん　聞いてくれますか

ペン子さん　ペン子さん

お幸せに

<audio>
<source src="audio/28/039.mp3">
</audio><hr>

ご注文は　お決まりですか

竹　大盛り

ありません

じゃあ　普通盛りでいいんです

すみません　どっちもありません

<audio>
<source src="audio/28/040.mp3">
</audio><hr>

海の家名物　竹大盛り

絶対人気出るよ

パンダ君にだけでしょ

<audio>
<source src="audio/28/041.mp3">
</audio><hr>

僕　このサーモンの軽いスモーク ミキュイ　ソース　クレソニエール

<audio>
<source src="audio/28/042.mp3">
</audio><hr>

違うでしょ

じゃあ　僕もトッピング竹で

ないから　そのトッピング

<audio>
<source src="audio/28/043.mp3">
</audio><hr>

ペンギンさんは

僕はシーフードラーメン

<audio>
<source src="audio/28/044.mp3">
</audio><hr>

あつっ　あつあつあつ

ペンギンさんいつも生魚だもんね

ペンギン舌だね

<audio>
<source src="audio/28/045.mp3">
</audio><hr>

なにそれ

猫舌のペンギン版

普通に猫舌でいいよ

<audio>
<source src="audio/28/046.mp3">
</audio><hr>

頑張って シーフードがペンギンさんを待ってるよ

あつあつ

<audio>
<source src="audio/28/047.mp3">
</audio><hr>

シーフードなら海で食べればいいのに

<audio>
<source src="audio/28/048.mp3">
</audio><hr>

もっともなこと言わないでくれる

ああ　もう行儀悪いな

女の子に嫌われちゃうよ

<audio>
<source src="audio/28/049.mp3">
</audio><hr>

ほら

パンダさんが焼き蕎麦食べてる

可愛い

<audio>
<source src="audio/28/050.mp3">
</audio><hr>

高評価だね

何で

シーンに合わせたふるまい

僕だってラーメン食べてるのに

<audio>
<source src="audio/28/051.mp3">
</audio><hr>

ペンギンがラーメン食べてる

何だあれ　珍しい

低評価だね

何で

<audio>
<source src="audio/28/052.mp3">
</audio><hr>

おいしいね

やっぱりおいしく感じるシーンっていうのがあるのかもね

<audio>
<source src="audio/28/053.mp3">
</audio><hr>

皆と一緒に風を感じながら

次はかき氷食べよう

<audio>
<source src="audio/28/054.mp3">
</audio><hr>

僕　イチゴ味がいいな

せっかくいいこと言ったのに

<audio>
<source src="audio/28/055.mp3">
</audio><hr>

もう　皆ばらばらだよ

ホント自分勝手っていうか　チームワークがないっていうか

ばらばらだよ

<audio>
<source src="audio/28/056.mp3">
</audio><hr>

楽しかったね

そうだね　干物も作れたし

海って　いいよね

<audio>
<source src="audio/28/057.mp3">
</audio><hr>

本日の列車は運行を終了しました

寝過ごした

山も　いいよね

<audio>
<source src="audio/28/058.mp3">
</audio><hr>

次は何する

干物食べる

<audio>
<source src="audio/28/059.mp3">
</audio><hr>


