---
title: "パンダくんの家出"
---

<span id="episode-title" data-episode="36"> パンダくんの家出 </span> 

<audio></audio><hr>

あれ？　パンダくん？

大荷物だね　おつかいかな？

<audio></audio><hr>

聞かないでください

いってらっしゃい

<audio></audio><hr>

それでさ　僕こう言ったわけよ

それもしかして座敷童子じゃないの？　って

<audio></audio><hr>

それより　ペン子さんたちとは どうなったの？

その件は　ここにいる間だけ 忘れさせてくれない？

今は　座敷童子の話だけに 集中したいんだ

<audio></audio><hr>

逃避行動だね　

なんとでも言って

<audio></audio><hr>

入れない…

どうしたの？　あの荷物

フリマ？

元気ないね　何かあったの？

<audio></audio><hr>

お母さんが　いつも 僕のこと怒るんだ

また　あなたは 昼間から　ゴロゴロして…

<audio></audio><hr>

パンダがゴロゴロして　何が悪いの？

まぁ　基本　ゴロゴロしてるもんね

<audio></audio><hr>

僕から　ゴロゴロを奪ったら なんにも残らないよ？

なんにも残らないんだ？

<audio></audio><hr>

逆に　すごいね

お母さんは　きっと 僕が嫌いなんだ

え～っと…　お母さんは　もっと　お手伝いして ほしいんじゃないの？

<audio></audio><hr>

でも　弟や　妹だって ゴロゴロしてるのに

お母さん　怒らないんだよ？

それは…　その子たちはまだ小さいからでしょ？

弟や　妹は　かわいいけど 僕は違うからだよ

<audio></audio><hr>

パンダなんて みんな　かわいいじゃない

これ　妹の写真

<audio></audio><hr>

パンダでも違うんだね

うん

あっ…

やっぱり　僕は 橋の下で拾われた子なんだ

<audio></audio><hr>

橋の下で　パンダ拾えるなら

動物園が　みんな拾いに行くよ

で　どうしたの？

<audio></audio><hr>

実は　家出してきたの

あ　やっぱり

それで　どこに行くの　

<audio></audio><hr>

橋の下？

え～っ　もうちょっと心配して 僕んちおいで　とか言ってよ

言わないよ

<audio></audio><hr>

で　どこ行くの？

うんとね　ゴロゴロしてても何も言われなくて

黙っててもご飯が出てきて

パンダくん　かわいいって 言ってくれる

誰かがいるところ

それ　かなり限定されてるよね

<audio></audio><hr>

あ～　リンリンのところは？

<audio></audio><hr>

イヤだよ

もっと放っておいてほしいんだよ

だったら　動物園は？

住み込みでバイトすればいいでしょ

うわ～　パンダさん　かわいい！

<audio></audio><hr>

どうして毎日 働かないといけないの？

僕　絶対に 毎日　働くのはイヤなんだよ

<audio></audio><hr>

そんなに堂々と 言うことじゃないね

あ！

何？

<audio></audio><hr>

シロクマくん　あの荷物置いといていい？

えっ？

家で　晩ご飯食べてくるよ

じゃあね

<audio></audio><hr>

帰るんだ

いろんな家出があるんだね

こういうのは 家出って言わないでしょ

<audio></audio><hr>

パンダくん　まだ取りに来てないの家出の荷物

うん　昨日 晩ご飯食べに帰ったっきり

家で寝たんだね

うん

<audio></audio><hr>

家出の仕方間違ってない？

家出の続きをしに来ました

<audio></audio><hr>

あのさ　パンダくん

お腹が空いたら 家に帰っちゃうんだとさ

家出というかさ 

<audio></audio><hr>

何だろう…　日常生活？

家には戻らないよ

もう戻らないよ

いや　戻っていいんだよ

<audio></audio><hr>

何があったの？

夕べ　また 大ショックなことがあったんだよ

<audio></audio><hr>

来週は　あなたの お誕生日だけど

お母さんが ちょっと　忙しくてね

弟たちと一緒に 来月お祝いにするから…

えっ！

まぁ　大人の都合ってやつだね

ケーキが１個で済むとかさ

ケーキは　何個食べたって いいじゃない

<audio></audio><hr>

お祝いは　何回もあったほうが 楽しいのに

どうして 減らそうとするんだろうね

<audio></audio><hr>

もう…　あんな家にはいられないよ

まあ　まあ

<audio></audio><hr>

けど　どうしてパンダくんの誕生日じゃなくて

弟さんたちの誕生日に合わせるんですかね？

<audio></audio><hr>

へえ～っ！

かわいいでしょ

ああ…　シロクマくん　ダメだよ！

この　かわいい妹さんの写真をかわいくないパンダくんの前で褒めちゃ！

<audio></audio><hr>

あ…　ごめん

ま…　待とうよ　パンダくん

お祝いはしてくれるんだし

１か月遅れでも　いいじゃない

そこは　子供側も 妥協が必要じゃないかな？

<audio></audio><hr>

よくないよ

どうして？

僕は　プレゼントに パンダかき氷機が欲しかったんだよ！

ひと月後だと　もう　かき氷が 食べたくなくなっちゃうよ！

<audio></audio><hr>

え…　そんな理由？

僕　もう　ペンギンさんちの子になるよ

ちょっと！　勝手に 僕の戸籍に入ってこないで！

<audio></audio><hr>

ペンギンさんは　僕のことかわいくないんだ…

そういう問題じゃないよね？

<audio></audio><hr>

いいじゃないですか 置いてあげれば

えっ？　笹子さん！？

何を言うんだい？

<audio></audio><hr>

じゃあ　今から　笹子さんちか シロクマくんちの子になるよ

それは　無理

<audio></audio><hr>

みんな　僕を 子供にするのは　イヤなんだ…

やっぱり　僕が かわいくないからなんだね…

<audio></audio><hr>

そういうことでは ないんだけど…

あっ　だったら

僕たちが　今月 かき氷機を　プレゼントすれば？

<audio></audio><hr>

かき氷パーティーしようよ

本当？　いつ？　いつ？

<audio></audio><hr>

今日が　ここ

いつ？いつ？

カフェが休みの日曜で…

あっ　来週は 町内会の用事があるんだった

僕　再来週は法事でいないよ

<audio></audio><hr>

私も　親戚の結婚式で いないですね

じゃあ…　あっ　来月になっちゃうね

<audio></audio><hr>

こ…　今週末

土曜の午後なら　どう？

そうですね

<audio></audio><hr>

じゃあね

僕　お家　帰る

もう家出はいいんだ？

<audio></audio><hr>

うん

荷物　持って帰ったら？

ああ　それね かき氷パーティーするなら必要だから

うん？

<audio></audio><hr>

かき氷パーティーには これが　なくっちゃね

<audio></audio><hr>

やっぱり　家出の仕方 間違ってるよね？

楽しみだな　週末

<audio></audio><hr>

今日は涼しいですね

かき氷パーティーは中止かな

だね

<audio></audio><hr>

うんうんうん……

やろう！　今すぐ　やろう！！

はい…

いただきま～す！

<audio></audio><hr>

やっぱり…

雨の日だと　おいしくないね

うん

<audio></audio><hr>



