---
title: "パンダくん パンダじゃなくなる"
---

<span id="episode-title" data-episode="41"> パンダくん パンダじゃなくなる </span> 

<audio></audio><hr>

僕 明日から パンダじゃなくなるんだ

ちょっと待って…

いきなり 何？

どういうこと？

<audio></audio><hr>

だから パンダじゃなくなるの

流していいとこかな？

<audio></audio><hr>

じゃあ 何になるの？

パンダ以外だ

いや… パンダは パンダ以外にはなれないでしょ

<audio></audio><hr>

なれるよ

配置換えを希望したもん

配置換え？

<audio></audio><hr>

辞令

非常勤パンダ アナグマコーナーに配属を命ず

園長

パンダくんが アナグマコーナーに？

何 考えてるんですかね？ 園長は…

<audio></audio><hr>

今日から配属になった パンダです

よろしくお願いしま～す

えっ！？ パンダくん アナグマになったの？

<audio></audio><hr>

辞令が出たんだよ

そうなんだ

まぁ パンダの目も 夜行性動物と同じらしいからね

<audio></audio><hr>

難しい話はいいよ

僕 アナグマ がんばるよ

じゃあ 一緒に穴を掘ろうか

は～い

<audio></audio><hr>

寝てる…

ちょっと パンダくん 起きてよ！

<audio></audio><hr>

あぁ 半田さん おはよう

ちょっと 半田さん！

パンダくん 寝てばかりで

アナグマとしてのやる気が 全然 感じられないよ

<audio></audio><hr>

やっぱり やる気がないからかな？

自分で 配置換え 希望したんでしょ？

だって ここ暗いし

日の当たらないパンダは

パンダじゃないよ

<audio></audio><hr>

そうだ！

別の所に配置換えを頼んでみるよ

そんな希望 通るわけないでしょ

<audio></audio><hr>

通った…

今度は ラッコ…

今日から配属になった パンダです

よろしくお願いします

<audio></audio><hr>

がんばってよ 結構きついよ ラッコ

じゃ 早速 飛び込んでみようか

僕は ここで見てるよ

<audio></audio><hr>

何言ってるの

ラッコは 水の中に入らないとダメでしょ

じゃあ これ 割ってみようか

<audio></audio><hr>

これは大事だから

ハマグリ割れないと ラッコできないから

そうなんだ？

見てて

<audio></audio><hr>

じゃあ やってみようか

割れないよ？

もっと力入れて

<audio></audio><hr>

ムリだよ？

何言ってるの がんばってよ

お腹 痛いんだよね

僕だって痛いよ

あっ そうだ！

<audio></audio><hr>

ラッコさんのお腹で割らせてよ

人のお腹で 貝割るラッコなんていないよ？

<audio></audio><hr>

あっ 半田さん

何？

この新人さん ダメだよ

そもそも 貝割らないからね パンダは

仕事としては割るけど

<audio></audio><hr>

割ってないじゃない

半田さん ラッコはムリだよ

パンダくんが配置換え 希望したんでしょ？

<audio></audio><hr>

今度は ラマ…

お母さん 早く早く

はいはい

えっと…

なんで 僕まで？

桐野くん… もう一人いないと 僕 ラマできないからね

<audio></audio><hr>

でも 僕 他に仕事が…

ラマをするのも立派な仕事だよ？

<audio></audio><hr>

わかったよ

でも 前が見えなくて 苦しいね

じゃあ 前後交代する？

<audio></audio><hr>

僕が前だと 意味ないんじゃ…

やっぱり 僕が前かな

こんにちは パンダくん

<audio></audio><hr>

あぁ ラマさん

よろしくお願いしま～す

こちらこそ

ねぇねぇ 僕 何か ラマっぽいことしたほうがいいよね

<audio></audio><hr>

別にいいんじゃないでしょうか

何で？

誰も見ないと思うんですよ

みんな 隣のキリンさんのほうへ 行っちゃうんですよね

<audio></audio><hr>

キリンさんだ！

首長い！

大きいね

ねっ

<audio></audio><hr>

どう ラマうまくやれてる？

あっ 半田さん

あのね ここはちょっと やりがいがないと思うんだよね

え～っ？

<audio></audio><hr>

え～っ！ 今度は飼育係？

先輩 パンダが飼育係ってありですか？

<audio></audio><hr>

半田さん 桐野くん 今日も１日頑張ろう！

パンダくん ちゃんとやってるかな

<audio></audio><hr>

あれ？

おや？

<audio></audio><hr>

はい ふれあい動物園です

僕 よくわからないので あとでかけ直してください

じゃあ

<audio></audio><hr>

あっ いいな この温泉

どこにあるんだろう？

パンダくん 何してるの

あっ ちょうどいいところに

ねぇねぇ この 温泉どこにあるか知ってる？

<audio></audio><hr>

そこ僕の席なんだけど

あぁ 半田さん 安心して

半田さんの荷物は そこに置いておいてあげたよ

<audio></audio><hr>

ちょっと 勝手に片づけないでよ

っていうか みんなに飼育係の 仕事させて何やってるの！

デスクワークだよ

<audio></audio><hr>

いや～ 忙しいよ

電話切ったり パソコンやったり 電話切ったり

全然 仕事してないじゃない

<audio></audio><hr>

ねぇ パンダくん

何？

飼育係が自分で食べちゃダメでしょ

僕 思うんだけどね やっぱり動物に動物の世話は

ムリだと思うんだよね

<audio></audio><hr>

そんなに文句ばかり言ってたら パンダくんの配属先もうないよ

え～っ じゃあ もうあとは 園長やるしかないかな

<audio></audio><hr>

園長？

先輩… それだけは 絶対に阻止しましょうね

<audio></audio><hr>

常勤パンダさんは しっかり やってるかな？

あっ パンダくんじゃないですか

ラマさん 何やってるの？

配置換えを希望したんですよ

<audio></audio><hr>

園長… ラマさんを パンダコーナーに配属したんですね

お～い ラマくん

今から団体さん来るから サービス よろしくね

はい わかりました

<audio></audio><hr>

あっ かわいい！

すご～い！！

うわ～っ！

見て 見て！ かわいい！

すごいね

ラマさん 大人気ですね 先輩

そうだな

サービス サービス 

<audio></audio><hr>

いいねぇ キミ いいよ

パンダ 向いてるんじゃない？

ラマやってるより 輝いてるよ

本当ですか？

サービス サービス！ サービス サービス！

いいねぇ キミ ホント 向いてるよ

<audio></audio><hr>

非常勤パンダ パンダコーナーに配属を命ず

パンダくん 元に 戻してもらったみたいですね

<audio></audio><hr>

やっぱり 僕は パンダが いちばん向いてるね

ラマさん これ 今日のお昼ご飯ね

ありがとうございます

掃除は 午後にやるから

<audio></audio><hr>

半田さん

何？

また配置換えの辞令 出ないですかね

<audio></audio><hr>



