---
title: "半田さん改造計画"
---

半田さん改造計画

<audio controls>
<source src="07/001.mp3">
</audio><hr>

ねぇねぇ モテ期って知ってる？

モテ期？

<audio controls>
<source src="07/002.mp3">
</audio><hr>

それは　汽笛

それは　射的

それは　奇跡

モテ期って？

<audio controls>
<source src="07/003.mp3">
</audio><hr>

人は一生のうちすごくモテる時期があって

それをモテ期って言うんだって

それ繁殖期でしょ

<audio controls>
<source src="07/004.mp3">
</audio><hr>

だよね

ちょっと違うらしいよ

<audio controls>
<source src="07/005.mp3">
</audio><hr>

繁殖期は　季節が巡ってこないと 訪れないんだけど

モテ期は　努力によって くるらしいんだよ

<audio controls>
<source src="07/006.mp3">
</audio><hr>

何のお話ですか？

見てて

笹子さん

はい？

はい！

<audio controls>
<source src="07/007.mp3">
</audio><hr>

お面？

あれ？　じゃあ…

はい

ニンジン？

あれ？　じゃあ…

僕　体重１００キロ以上あるんだ

<audio controls>
<source src="07/008.mp3">
</audio><hr>

そう

重いでしょ？

重いね

それだけ？

うん

おかしいな…

モテるには　お面で野菜で 重かったりするはずなんだけど…

<audio controls>
<source src="07/009.mp3">
</audio><hr>

あの…　

イケメンで優しくて おもしろかったりしたらじゃ…

<audio controls>
<source src="07/010.mp3">
</audio><hr>

ちょっと違った

ニアピン賞

いや　大きく間違ってるから

<audio controls>
<source src="07/011.mp3">
</audio><hr>

あっ！ 配達ですか？

ステキなお花ですね

ありがとうございます

<audio controls>
<source src="07/012.mp3">
</audio><hr>

あれがモテ期かぁ

じゃあ　これ 売店に届けてきますので

行っちゃイヤ！

<audio controls>
<source src="07/013.mp3">
</audio><hr>

す…　すみません

ああ　いえ　こちらこそ

大丈夫ですか？

<audio controls>
<source src="07/014.mp3">
</audio><hr>

ケガはないかい？

ああ　僕は　大丈夫です


本当に？

ええ

よかった

<audio controls>
<source src="07/015.mp3">
</audio><hr>

心配しちゃったよ

半田さん

僕が力になるよ

<audio controls>
<source src="07/016.mp3">
</audio><hr>

なんとかしてあげるから

ああ　パンダくん　おはよう！

リンリンは　僕のこと必要ないでしょ

<audio controls>
<source src="07/017.mp3">
</audio><hr>

さあ　半田さん行こう

<audio controls>
<source src="07/018.mp3">
</audio><hr>

こんにちは！ 聞いて　聞いて！

どうしたんですか？

やっと仮免　受かったよ

ついにだよ　とうとうだよ！

<audio controls>
<source src="07/019.mp3">
</audio><hr>

あれ？　シロクマくんはいないの？

大切な用事があるからって…

<audio controls>
<source src="07/020.mp3">
</audio><hr>

ここでやるの？

協力してね　シロクマくん

パンダくん　やる気だね

<audio controls>
<source src="07/021.mp3">
</audio><hr>

いろいろ情報　仕入れてきたよ

ごめん！　ちょっと お年寄りに道を聞かれてさ

さあ　行くよ　半田さん

<audio controls>
<source src="07/022.mp3">
</audio><hr>

えっ？　どこへ？

半田さん改造計画！

<audio controls>
<source src="07/023.mp3">
</audio><hr>

まずは　ファッションだよ

さり気ない　トラッド

う～ん　ちょっとカタイね

<audio controls>
<source src="07/024.mp3">
</audio><hr>

パンクはどう？

う～ん　これもね…

<audio controls>
<source src="07/025.mp3">
</audio><hr>

渋谷系とか

というより　サブカル系？

<audio controls>
<source src="07/026.mp3">
</audio><hr>

あぁ～！　これ　これ

いいんじゃない？

これじゃ　いつもと同じだよ

う～ん　

<audio controls>
<source src="07/027.mp3">
</audio><hr>

じゃあ…

モテファッションといえば　

オスとして 強く　アピールできるものがいいよね

<audio controls>
<source src="07/028.mp3">
</audio><hr>

ニワトリなら　立派なトサカだし

猫なら　耳かな？

鳥なら　羽でしょ

<audio controls>
<source src="07/029.mp3">
</audio><hr>

でも　やっぱ　これだよね　

パンダの着ぐるみ？

半田さん 日ごろの僕を見てて　わからない？

<audio controls>
<source src="07/030.mp3">
</audio><hr>

モテモテだよ

これなんか　どう？

ちょっと　きついけど

シロクマくん　パンダみたいだね

パンダくんの代わりに 動物園で働こうかな

<audio controls>
<source src="07/031.mp3">
</audio><hr>

ムリでしょ

袋　開けたんだから ちゃんと買いなよ

お財布　持ってきてない

<audio controls>
<source src="07/032.mp3">
</audio><hr>

ありがとうございました

じゃあ　次

<audio controls>
<source src="07/033.mp3">
</audio><hr>

グルメ情報も大事らしいよ

どう　大事なの？

半田さんの人生にだよ

そうなんだ…

<audio controls>
<source src="07/034.mp3">
</audio><hr>

もう！　何？　そのやる気のなさ

僕が　こんなに一生懸命なのに

おいしそうなもの いっぱい　あるね

<audio controls>
<source src="07/035.mp3">
</audio><hr>

あぁ～！　笹まんじゅう 笹だんご　笹ようかん

<audio controls>
<source src="07/036.mp3">
</audio><hr>

買ってあげなよ

しようがないな…　１個だけね

これも　よろしく

<audio controls>
<source src="07/037.mp3">
</audio><hr>

半田さん！

半田さん！

１００円　１００円

シロクマくん　何やってるの！？

<audio controls>
<source src="07/038.mp3">
</audio><hr>

半田さん　いっぱい　持ってるね　モテモテだよ

これで　半田さんも だいぶ　改造人間になったね

いや…　それ　戦っちゃうから

<audio controls>
<source src="07/039.mp3">
</audio><hr>

どうする？

行こう！

なんだろう？　こっち　見てるよ

<audio controls>
<source src="07/040.mp3">
</audio><hr>

あの…

はい

もし　よかったら…

<audio controls>
<source src="07/041.mp3">
</audio><hr>

一緒に写真　撮ってもらえますか？

きたよ　モテ期！

いいですよ

お願いします！

<audio controls>
<source src="07/042.mp3">
</audio><hr>

パンダくん　人気者だね

僕も一緒に撮ってくる

<audio controls>
<source src="07/043.mp3">
</audio><hr>

もう１枚　撮りますよ

は～い！

<audio controls>
<source src="07/044.mp3">
</audio><hr>

あぁ　楽しかった！

おかえり　遅かったね

<audio controls>
<source src="07/045.mp3">
</audio><hr>

すみません！ 注文　お願いします

はい　お待たせしました

お水のお代わりください

ただ今！

<audio controls>
<source src="07/046.mp3">
</audio><hr>

忙しそうだな

笹子さん　モテモテだね

<audio controls>
<source src="07/047.mp3">
</audio><hr>

あっ！ 半田さんじゃないですか

すみません お水　お代わり　お願いします

あぁ　半田さん！ 背中　かいてもらえますか？

半田さ～ん…

<audio controls>
<source src="07/048.mp3">
</audio><hr>

ここに座らないように言って

はい　はい

<audio controls>
<source src="07/049.mp3">
</audio><hr>

うん　ありがとうございます

いえ　いえ

このへん？

も…　もうちょい　右です

ここに座ってね

ありがとう

<audio controls>
<source src="07/050.mp3">
</audio><hr>

半田さんにも　やっと…

きたね

モテ期

半田さん お水　もう１杯　もらえますか？

はい　はい

半田さん　

<audio controls>
<source src="07/051.mp3">
</audio><hr>

こっちもかいて

かくよ！

半田さ～ん！

なんだい？

<audio controls>
<source src="07/052.mp3">
</audio><hr>



