---
title: "シロクマくん　動物園へ"
---

シロクマくん　動物園へ

<audio controls>
<source src="audio/05/001.mp3">
</audio><hr>

シロクマくん　暇だから　何か問題出してよ

いいよ

<audio controls>
<source src="audio/05/002.mp3">
</audio><hr>

第１問

Ｔ字路と呼ばれる交差点

<audio controls>
<source src="audio/05/003.mp3">
</audio><hr>

法令上の正式名称は　Ｔ字路ではありません

さて　何と言うでしょう

<audio controls>
<source src="audio/05/004.mp3">
</audio><hr>

もっと　フランクな問題がいいな

<audio controls>
<source src="audio/05/005.mp3">
</audio><hr>

無洗米の製法には　いくつかありますが

<audio controls>
<source src="audio/05/006.mp3">
</audio><hr>

加工法という方法では　よく…　

ごめん、もういいや(ー_ー)!!

<audio controls>
<source src="audio/05/007.mp3">
</audio><hr>

おぉ　パンダくん

いらっしゃい

<audio controls>
<source src="audio/05/008.mp3">
</audio><hr>

パンダくん　いつもの？

<audio controls>
<source src="audio/05/009.mp3">
</audio><hr>

どうしたの？　クイズ出す？

<audio controls>
<source src="audio/05/010.mp3">
</audio><hr>

クイズより

どうして　シロクマくんは　動物園に来てくれないの？

<audio controls>
<source src="audio/05/011.mp3">
</audio><hr>

何？　急に

僕は　いつもシロクマくんの仕事場に　遊びに来てるのに　ずるいよ

<audio controls>
<source src="audio/05/012.mp3">
</audio><hr>

カフェに　お茶しに来てるだけでしょ

<audio controls>
<source src="audio/05/013.mp3">
</audio><hr>

僕　人には　モテるんだからね　（　^ω^）

聞いてないなぁ…

<audio controls>
<source src="audio/05/014.mp3">
</audio><hr>

一度　動物園に遊びに来てよ

<audio controls>
<source src="audio/05/015.mp3">
</audio><hr>

大人気で　びっくりするよ(#^.^#)

大人気で　びっくりするよ(#^.^#)

<audio controls>
<source src="audio/05/016.mp3">
</audio><hr>

なんで　２回言うの？／(-_-)＼

<audio controls>
<source src="audio/05/017.mp3">
</audio><hr>

もしもし　シロクマくん？

明日　動物園に来る件だけど　忘れないでよ

<audio controls>
<source src="audio/05/018.mp3">
</audio><hr>

じゃあ　ペンギンさんにも　伝えておいてね

<audio controls>
<source src="audio/05/019.mp3">
</audio><hr>

おはようございま～す

おはよう　パンダくん

なんだか　元気だね

<audio controls>
<source src="audio/05/020.mp3">
</audio><hr>

今日　友達が僕のこと見に来るの

そうなんだ

<audio controls>
<source src="audio/05/021.mp3">
</audio><hr>

あっ　そうだ　今日は　常勤パンダさんが　娘さんの参観日だから　休むって

そうなの？(｀・ω・´)

<audio controls>
<source src="audio/05/022.mp3">
</audio><hr>

あれ？　ということは…

<audio controls>
<source src="audio/05/023.mp3">
</audio><hr>

パンダは　僕ひとり…

パンダさん　かわいい～！＼(^o^)／

パンダく～ん！　かわいい！

<audio controls>
<source src="audio/05/024.mp3">
</audio><hr>

ようし！　頑張るぞ～！(^_-)-☆

<audio controls>
<source src="audio/05/025.mp3">
</audio><hr>


何名様ですか？

動物が

２名です

<audio controls>
<source src="audio/05/026.mp3">
</audio><hr>

ここが　動物園か

思ったより　広いね　　

まずは　パンダくんを見に行こう

<audio controls>
<source src="audio/05/027.mp3">
</audio><hr>

ただ今から　シロクマの　おやつタイムを行います

シロクマが　プールへダイビングする姿を　どうぞお楽しみください

<audio controls>
<source src="audio/05/028.mp3">
</audio><hr>

見たい！　すごそう！

えっ！？　見たい！？

<audio controls>
<source src="audio/05/029.mp3">
</audio><hr>

シロクマくんって　シロクマだよね？

シロクマが　シロクマのダイビングする姿が見たいの？

<audio controls>
<source src="audio/05/030.mp3">
</audio><hr>

行こう　行こう！

パンダく～ん

<audio controls>
<source src="audio/05/031.mp3">
</audio><hr>

そんなに飛ばして大丈夫？

半田さん　友達が来たら　ちゃんと写真撮ってね

<audio controls>
<source src="audio/05/032.mp3">
</audio><hr>

でも　おかしいなぁ

シロクマくんたち　１時って言ったのに　来ないね

<audio controls>
<source src="audio/05/033.mp3">
</audio><hr>

シロクマくん　駄目だよ　ほら

なに？　

<audio controls>
<source src="audio/05/034.mp3">
</audio><hr>

入館不可だって

しろくま館へのシロクマの入館は　ご遠慮ください

<audio controls>
<source src="audio/05/035.mp3">
</audio><hr>

まぎらわしいので

こっそり入れば　バレない　バレない　(*￣∇￣)ノ

<audio controls>
<source src="audio/05/036.mp3">
</audio><hr>

いや　すごく目立ってるから

<audio controls>
<source src="audio/05/037.mp3">
</audio><hr>

お～！　すごい迫力

シロクマ！

<audio controls>
<source src="audio/05/038.mp3">
</audio><hr>

ちょっと　ちょっと　シロクマは　入れないって書いてあったでしょう

困りますよ

<audio controls>
<source src="audio/05/039.mp3">
</audio><hr>

え？　これ　剥製ですけど

<audio controls>
<source src="audio/05/040.mp3">
</audio><hr>

今　動いてましたよ　剥製なわけないでしょう

<audio controls>
<source src="audio/05/041.mp3">
</audio><hr>

なんで来ないの？　

もう行っていいかな？来たら呼んで

<audio controls>
<source src="audio/05/042.mp3">
</audio><hr>

もう　叱られたじゃない

僕は　バレるって言ったのに

じゃあ　パンダくんとこに行こう

うん

<audio controls>
<source src="audio/05/043.mp3">
</audio><hr>

パンダくん　かわいい　キャ～ッ　かわいい(>_<)

パンダく～ん

パンダくん　遅れてごめん

あれ？　

<audio controls>
<source src="audio/05/044.mp3">
</audio><hr>

お～い　パンダくん

寝てる

パンダくん　起きて(#`O′)　

<audio controls>
<source src="audio/05/045.mp3">
</audio><hr>

笑ってる

パンダくん　おい　パンダくん！

駄目だ

<audio controls>
<source src="audio/05/046.mp3">
</audio><hr>

他のとこ回ってこようか

寝ててもいいなんて　うらやましい仕事だね

<audio controls>
<source src="audio/05/047.mp3">
</audio><hr>

ハッ　今　ペンギンさんの声が

いない

<audio controls>
<source src="audio/05/048.mp3">
</audio><hr>

あっ　半田さん　

なに？

友達来なかった？　

え？　気づかなかったな

ちゃんと写真撮ってよ　

はいはい

<audio controls>
<source src="audio/05/049.mp3">
</audio><hr>

おっ　あざらし館　行こう　行こう

<audio controls>
<source src="audio/05/050.mp3">
</audio><hr>

シロクマの入館は　ご遠慮ください

<audio controls>
<source src="audio/05/051.mp3">
</audio><hr>

あざらしが怖がるので…

だってさ

<audio controls>
<source src="audio/05/052.mp3">
</audio><hr>

バレない　バレない　

いや　目立ってるし

<audio controls>
<source src="audio/05/053.mp3">
</audio><hr>

食べない　食べない(*￣∇￣)ノ

シロクマ！

食べないとわかっていても　実際　本物見るとテンション上がるなあ

<audio controls>
<source src="audio/05/054.mp3">
</audio><hr>

シロクマくんの野性が　呼び覚まされないうちに　早く行こうよ

<audio controls>
<source src="audio/05/055.mp3">
</audio><hr>

ちょっと　ちょっと

シロクマは　入らないで　って書いてあったでしょう

<audio controls>
<source src="audio/05/056.mp3">
</audio><hr>

え？　これ絨毯ですよ

ほ～ら　見てみて　こんなに　ふっかふかo(*￣▽￣*)o　

<audio controls>
<source src="audio/05/057.mp3">
</audio><hr>

いや～　騙せないもんだね

もう

パンダくん　そろそろ起きてるんじゃない？

<audio controls>
<source src="audio/05/058.mp3">
</audio><hr>

お～い　パンダくん　

また　笑ってる

<audio controls>
<source src="audio/05/059.mp3">
</audio><hr>

よくあんな状態で寝られるね

あれは逆に尊敬するね

<audio controls>
<source src="audio/05/060.mp3">
</audio><hr>

あの　もしかして　パンダくんのお友達ですか？

あ　はい　

写真撮りましょうか

撮ってくれって頼まれてるんで

<audio controls>
<source src="audio/05/061.mp3">
</audio><hr>

キリンさん　しろくまカフェに　来てくれないかな？

いや　カフェに入れないでしょ

<audio controls>
<source src="audio/05/062.mp3">
</audio><hr>

別のところも回ってみよう

そうだね

で　どこ行こうか？

<audio controls>
<source src="audio/05/063.mp3">
</audio><hr>

う～ん　あっ！　ペンギンコーナー

えぇ～

ペンギンさん　曲芸に飛び入りしてよ

<audio controls>
<source src="audio/05/064.mp3">
</audio><hr>

僕　運動神経　悪いから

ちょっと　ちょっと　

<audio controls>
<source src="audio/05/065.mp3">
</audio><hr>

あ　ラマさん

今日は　どうしたんですか？

<audio controls>
<source src="audio/05/066.mp3">
</audio><hr>

パンダくんに会いにきたのに　寝てるんだよね

たまには　起きてますよ

そっか

<audio controls>
<source src="audio/05/067.mp3">
</audio><hr>

いいかげん　パンダくん　起きてるよね？

戻ろう

<audio controls>
<source src="audio/05/068.mp3">
</audio><hr>

また寝てる

更に　だらしないね

パンダくん　僕たちに　いったい何を　見てもらいたかったんだろうね

<audio controls>
<source src="audio/05/069.mp3">
</audio><hr>

あのパンダさん　寝てばっかりで　つまんない

うん　行こう

<audio controls>
<source src="audio/05/070.mp3">
</audio><hr>

大人気ねぇ…

あ　また　笑った

<audio controls>
<source src="audio/05/071.mp3">
</audio><hr>

ず～っと待ってたのに　なんで来てくれなかったの？

いや　何度も行ったよ

<audio controls>
<source src="audio/05/072.mp3">
</audio><hr>

ほんと？　

行ったってば

ねぇ　ラマさん　今日　動物園で会ったよね？

会いましたよ

ほら　ちゃんと行ったでしょ？

<audio controls>
<source src="audio/05/073.mp3">
</audio><hr>

どうして僕のとこには　来てくれないの？

だから　行ったんだって！

そんなに　ずっと　ラマさんを見てたの？

<audio controls>
<source src="audio/05/074.mp3">
</audio><hr>

だから　パンダくんとこに行ったってば！

じゃあ　なんで　会えなかったんだろうね

パンダくんが　寝てばっかりだったからでしょ

<audio controls>
<source src="audio/05/075.mp3">
</audio><hr>

起こしてよ　

起きなかったよｍ(＿　＿)ｍ　

せっかく半田さんが　写真　撮ってくれるって言ってたのに

<audio controls>
<source src="audio/05/076.mp3">
</audio><hr>

撮ったよ

ほんとだ　来てたんだね

<audio controls>
<source src="audio/05/077.mp3">
</audio><hr>

だから　言ったのに

へぇ～　僕って　寝てても　かわいいなぁ

<audio controls>
<source src="audio/05/078.mp3">
</audio><hr>

ねえねえ　どの寝顔が　いちばん好き？

シロクマくん　おかわりくれる？

<audio controls>
<source src="audio/05/079.mp3">
</audio><hr>

