---
title: "見知らぬお店"
---

<span id="episode-title" data-episode="32"> 見知らぬお店 </span>  

<audio></audio><hr>



私が仕事で その街を訪れたのは

とある暑い夏の日のことだった

<audio></audio><hr>


まとわりつく 熱気もさることながら

何よりも私の心を ささくれさせたのは

昼に入った駅前の中華屋だ

<audio></audio><hr>


蒸し暑い店内

生ぬるい冷やし中華の麺は

みごとにのびきっていた

<audio></audio><hr>


しかし　頼んだものを残すのは 私のプライドが許さない

が　

<audio></audio><hr>


胃はまだもたれている

リフレッシュせねば

<audio></audio><hr>


見知らぬ街で 見知らぬ店に入るのは

当たりハズレが大きい

<audio></audio><hr>


生き返る

いらっしゃいませ お好きな席へどうぞ

あれは…

シロクマさんです

<audio></audio><hr>


そ　それはわかります

店長なんです

<audio></audio><hr>


シロクマが　店長なんですか

ええ　しろくまカフェですから

<audio></audio><hr>


そ　そうですか

いらっしゃいませ

お決まりの頃 おうかがいします

あ…　はい

<audio></audio><hr>


チャックなどは見つからない

やはり着ぐるみではなく本物

<audio></audio><hr>


この街は 動物が多いと聞いていたが

こうして 働く動物を見たのは初めてだ

<audio></audio><hr>


大きい　あんな手で 料理をするのだろうか

<audio></audio><hr>


カフェなのに輪切り　ありえない

でも　そんな想像しかできない

<audio></audio><hr>


ムダがなく　しかも美しい動き

疑ってすまない

<audio></audio><hr>


さぁ　もはや偏見は捨てて　注文するぞ

<audio></audio><hr>


メニューが動物用だなんてことは…

あ～　さすがに普通か

<audio></audio><hr>


これは　竹…

いや待て　もしかすると 竹をモチーフにしたスイーツかもしれん

<audio></audio><hr>


しかし　正真正銘の 竹であることも否定できない

<audio></audio><hr>


お決まりですか？

あ　えっと…　アイスコーヒー

アイスコーヒーを おひとつでよろしいですか

<audio></audio><hr>


はい　いえ…

竹を

竹ですか？

はい

大盛りもできますが

<audio></audio><hr>


じゃ　それで

はい

注文してしまった しかも大盛り

<audio></audio><hr>


この選択　吉と出るか 凶と出るか

お待たせしました

<audio></audio><hr>


やっぱ凶か！

あ　いや待て　今まで 食べる機会がなかっただけで

案外おいしいのかもしれない

そうだ　きっとそうだ

<audio></audio><hr>


竹の香りが だんだんと青臭さに変わり

噛み切れない筋とともに 口の中に広がってくる

<audio></audio><hr>


やっぱ　ただの竹だ

どうする こっそり出しちゃおうか

<audio></audio><hr>


しかし　一度口に入れたものを 出すなど　言語道断

う～　だが意識が飲み込めと 命令しても体が拒否する

水　水だ…

<audio></audio><hr>


うわ～　しまった！

さっき全部飲み干してしまった

もはや限界…

<audio></audio><hr>


アイスコーヒーです

天の助け

<audio></audio><hr>


戦いはまだ始まったばかり

<audio></audio><hr>


こんにちは

パンダ！

よいしょ

<audio></audio><hr>


パンダだ

子供の頃　動物園に行ったときは

人の頭しか見えなかったパンダが

<audio></audio><hr>


今まさにこんな近くに

しかし至近距離過ぎて 見るのが気まずい

どうしたものか

<audio></audio><hr>


そうだ　まわりを見るふりして

えっと…　お手洗いはどっちかな

<audio></audio><hr>


見られてる パンダにメッチャ見られてる

<audio></audio><hr>


食べないの？

えっ　いっ？！

もらってあげてもいいよ

<audio></audio><hr>


このチャンスを逃してはならぬ

よ…　よかったら どうぞ

ありがとう

ピンチ脱出！

<audio></audio><hr>


なんだか　すみませんね

ああ　いえいえ

よろしかったら　どうぞ　サービスです

<audio></audio><hr>


ふ…　振り出しに戻った…

いらっしゃい

<audio></audio><hr>


こんにちは

今度は　ペンギン！？

かわいい…

<audio></audio><hr>


そのイスに座るつもりか？

よじ登るのか？　跳ぶのか？ 誰かにのせてもらうのか？

<audio></audio><hr>


コーヒー　おかわり　いかがです？

ありがとうございます

<audio></audio><hr>


クソ！　見そこねた！

今日は暑いね

<audio></audio><hr>


ホント　仕事場にもクーラー欲しいよ

<audio></audio><hr>


それは　カーラー

それは　セーラー

それは　ディーラー

それは…　何だっけ？

<audio></audio><hr>


何とかラー？

ラー…　ラー…

マーラー？　トレーラー？

<audio></audio><hr>


ハスラーだ！

ハスラー！

何だっけ？

教えてよ

ひ　み　つ

<audio></audio><hr>


言いたい… 言ってしまいたい…

しかし　いきなり 会話に入り込むなど…

<audio></audio><hr>


ああ　レスラー

惜しい！

じゃあ　ブロイラー！

<audio></audio><hr>


遠ざかった…

もう我慢できない どう思われても　私は言う！！

<audio></audio><hr>


ハス…

いらっしゃい

<audio></audio><hr>


これまた　動物園のアイドル　コアラ！

根強い人気のラッコ

マンドリル　色　鮮やか！

<audio></audio><hr>


ラクダ？

ロバ…　じゃない　え～

タ…　タマ…　いや　そんな感じの…

<audio></audio><hr>


ああ　思い出せない…　クソ！

いらっしゃい　ラマさん

そうだ！　ラマだ

<audio></audio><hr>


ああ…　すっきりした

<audio></audio><hr>


そういえば　この前の 半田さん　おもしろかったよね

<audio></audio><hr>


気がついたら　私以外 周りは　みんな動物

しかも　みんな　常連風だ

<audio></audio><hr>


なんか　居づらい…

<audio></audio><hr>


せ…　席が　いっぱいだよ

テーブル席は空いてるよ

あ…　あの…　よかったら　どうぞ

もう帰りますので

<audio></audio><hr>


もう帰っちゃうの？ ゆっくりしていけばいいのに

いつの間に仲よくなったの？

<audio></audio><hr>


ネクタイさんとは 竹をもらった仲だよ

<audio></audio><hr>


ね？

はい

ありがとうございました

<audio></audio><hr>


ごちそうさま

あの…

は…　はい？

お持ち帰りできますので　どうぞ

あ…　ありがとうございます…

<audio></audio><hr>


さて…　あと　ひと仕事　頑張るか

<audio></audio><hr>


そうして　私は日暮れまで働き

<audio></audio><hr>


この街で夜を迎えた

一杯　やるか

<audio></audio><hr>


おう　そこは空いてるぜ　座んな

いや…　その…

座れって　遠慮すんな

<audio></audio><hr>


見知らぬ店に入るのは

当たりはずれが　とても大きい

<audio></audio><hr>


