---
title: "スマフォに夢中"
---

スマフォに夢中

<audio controls>
<source src="04/001.mp3">
</audio><hr>

ねぇ　シロクマくん

それ　楽しい？(^^)

<audio controls>
<source src="04/002.mp3">
</audio><hr>


そういう時もあるね

どんな時？

<audio controls>
<source src="04/003.mp3">
</audio><hr>


こんなのが折れた時

おぉ～！ (*^▽^*)


シロクマだね

<audio controls>
<source src="04/004.mp3">
</audio><hr>

ねぇ　どうやったの？

秘密 (#^.^#)

器用だね

写真撮っていいかな？

<audio controls>
<source src="04/005.mp3">
</audio><hr>

写真？　カメラ持ってるんだ？

カメラっていうかさ…

買ったんだ　スマフォ

<audio controls>
<source src="04/006.mp3">
</audio><hr>

なに？　スマフォって

<audio controls>
<source src="04/007.mp3">
</audio><hr>

それは　す巻き

それは　ちまき

はちまき

葉巻

ハマチ！　

キムチ！

スマフォだよ！　ス　マ　フォ！(-_-;)

<audio controls>
<source src="04/008.mp3">
</audio><hr>

スマートフォン　携帯電話の一種だよ

あっ！　ペンギンさん それが　スマートフォンですか？

<audio controls>
<source src="04/009.mp3">
</audio><hr>

私も　よく知らないんですよね

え？　笹子さんも？

<audio controls>
<source src="04/010.mp3">
</audio><hr>

何ができるんですか？

いろいろ便利だよ　アプリも多いし

<audio controls>
<source src="04/011.mp3">
</audio><hr>

地図とかも見られますしね

<audio controls>
<source src="04/012.mp3">
</audio><hr>

ネットだって見られるんだよ　ほら

<audio controls>
<source src="04/013.mp3">
</audio><hr>

なんか　小さくて 字　読みづらくないですか？

<audio controls>
<source src="04/014.mp3">
</audio><hr>

そんなことないよ こういう時はね　こうするの

パンチ操作って言ってね

叩くんですか？

違うよ

<audio controls>
<source src="04/015.mp3">
</audio><hr>

ピンチ操作じゃないですか？

似たようなもんでしょ

<audio controls>
<source src="04/016.mp3">
</audio><hr>

そうですか

そうだよ

いい？　笹子さん　見てて…

よっ…(｀・ω・´)

<audio controls>
<source src="04/017.mp3">
</audio><hr>

本当に　それ　便利なんですか？

便利だってば！

え～と　こうやって…

<audio controls>
<source src="04/018.mp3">
</audio><hr>

そのうち　簡単に 操作できるようになるよ

あれ？　シロクマくんも持ってたの？

<audio controls>
<source src="04/019.mp3">
</audio><hr>

まぁね　見てて

こうやるの

あぁ～　かっこいい！  (m´・ω・｀)m

シロクマさん　器用ですね

<audio controls>
<source src="04/020.mp3">
</audio><hr>

それほどでも アヤメの花　折ってみた

すご～い！

ほんと器用ですね！

<audio controls>
<source src="04/021.mp3">
</audio><hr>

よ～し　こうやって…

えい！　それ！(・∀・)

駄目だ…

<audio controls>
<source src="04/022.mp3">
</audio><hr>

まぁ　慣れですよ　慣れ

なんか上から目線

僕も　スマフォですし

<audio controls>
<source src="04/023.mp3">
</audio><hr>

えっ　そうなの？

はい

ラマさん　そういう君こそ 上手に操作できるの？

<audio controls>
<source src="04/024.mp3">
</audio><hr>

もちろんですよ　見ててください

おぉ～　(ﾉﾟοﾟ)ﾉすごい！ なんて柔軟な発想！

<audio controls>
<source src="04/025.mp3">
</audio><hr>

そうか… わぁ…

あっ　プロフ交換します？

するする

<audio controls>
<source src="04/026.mp3">
</audio><hr>

お勧めの便利なアプリ　知ってるよ

え？ なになに？　教えて！

<audio controls>
<source src="04/027.mp3">
</audio><hr>

やっぱ時代は　スマフォだよね

そうなの？

そうだよ

<audio controls>
<source src="04/028.mp3">
</audio><hr>

スマフォがあると すっごく便利なんだから

どんなふうに？

えっとね…

<audio controls>
<source src="04/029.mp3">
</audio><hr>

画面を ちまちま触って操作したり…

<audio controls>
<source src="04/030.mp3">
</audio><hr>

なめたり…

くちばしで　つついたり…

<audio controls>
<source src="04/031.mp3">
</audio><hr>

そんでもって 字が　すっごく小さくて

読みづらいんだよ

<audio controls>
<source src="04/032.mp3">
</audio><hr>

便利なの？それ

あれ？

<audio controls>
<source src="04/033.mp3">
</audio><hr>

とにかく　外で働いてるパンダが ケータイ持ってないなんて

駄目だよ　困るよ(/ω＼)

<audio controls>
<source src="04/034.mp3">
</audio><hr>

別に困らないわよ

いらないでしょ

それだと困るなぁ

<audio controls>
<source src="04/035.mp3">
</audio><hr>

何が？

ほら　ケータイあると 何かあったときに便利だよ

何かあったときね…

<audio controls>
<source src="04/036.mp3">
</audio><hr>

ねぇ　キッチンのバルサミコ酢が きれちゃったの

バイト帰りに買ってきてくれる？

うん　いいよ

<audio controls>
<source src="04/037.mp3">
</audio><hr>

便利じゃない！(＾ｖ＾)

いいわよ　買ってあげる

やった～！Ｖ（=＾0＾=）ｖ

<audio controls>
<source src="04/038.mp3">
</audio><hr>

ほら　見て見て～

何ですか？

この前撮った写真 待ち受けにしてみたんだ

<audio controls>
<source src="04/039.mp3">
</audio><hr>

へぇ～　今日は 折り紙折らないんですか？

えっ？ 気が向いたら

そっちの感想！？ (;ﾟДﾟ)!

<audio controls>
<source src="04/040.mp3">
</audio><hr>

こんにちは～

いらっしゃい

パンダくん　嬉しそうだね

<audio controls>
<source src="04/041.mp3">
</audio><hr>

実はさぁ…

ジャーン！

あぁ　それ！

パンダカバーのスマフォだよ！

かわいいね！(#^.^#)

<audio controls>
<source src="04/042.mp3">
</audio><hr>

いいでしょう～ 見つけるの苦労したんだよ

どう？　スマフォ

やっぱり便利だよね

<audio controls>
<source src="04/043.mp3">
</audio><hr>

ほら　好きな時に　いつだって 天気予報も見られるしね

<audio controls>
<source src="04/044.mp3">
</audio><hr>

地図も見られるから 迷子にならなくて済むし

<audio controls>
<source src="04/045.mp3">
</audio><hr>

頭にのせて バランス感覚も　みがけるし

<audio controls>
<source src="04/046.mp3">
</audio><hr>

それ スマフォの使い方じゃないけどね

でも　ペンギンさんより 使いこなしてませんか？

ぼ　僕だって 待ち受けかえてるし

<audio controls>
<source src="04/047.mp3">
</audio><hr>

他にも…

写真を撮ったり

音楽だって聴けるしね

<audio controls>
<source src="04/048.mp3">
</audio><hr>

だ　大丈夫だよ　パンダくん

壊れたのは　カバーだけみたい

だって

<audio controls>
<source src="04/049.mp3">
</audio><hr>

だから　元気出して

スマフォが無事でよかったです

はい　パンダくん

<audio controls>
<source src="04/050.mp3">
</audio><hr>

僕にとって…　スマフォは パンダカバーのおまけだから

<audio controls>
<source src="04/051.mp3">
</audio><hr>

あら　ちょっと スマホは　どうしたの？　スマホは

さっき電話したのよ

<audio controls>
<source src="04/052.mp3">
</audio><hr>

ねぇ　聞こえてる？

 バ　ル　サ　ミ　コ　酢よ　バールーサーミーコー酢！
 
 <audio controls>
<source src="04/053.mp3">
</audio><hr>

この電話は　お客様の 都合により　出られません

えっ？

<audio controls>
<source src="04/054.mp3">
</audio><hr>

ちっとも便利じゃないわね　スマホ

あのさ　スマートフォンなんだから スマホじゃなくて　スマフォだよ

どっちだっていいじゃない

<audio controls>
<source src="04/055.mp3">
</audio><hr>

こんにちは～(=゜ω゜)ノ

シロクマくん　いつものお願い

<audio controls>
<source src="04/056.mp3">
</audio><hr>

パンダくん　ひょっとして 立ち直った？

何が？

<audio controls>
<source src="04/057.mp3">
</audio><hr>

心配した僕が　バカだったよ

パンダくんのスマフォ　ここにあるからね

<audio controls>
<source src="04/058.mp3">
</audio><hr>

あぁ　スマフォなら　もういいんだ

強がり？

本気　

<audio controls>
<source src="04/059.mp3">
</audio><hr>

だって　パンダじゃないし

えっ？　せっかく買ったんだから 大事に使ったら？

<audio controls>
<source src="04/060.mp3">
</audio><hr>

パンダくん　これ見て　スマフォのケース

<audio controls>
<source src="04/061.mp3">
</audio><hr>

こんなの折ってみた

あっ　パンダだ～！

<audio controls>
<source src="04/062.mp3">
</audio><hr>

これなら　紙だから割れないね

よかったですね

シロクマさん　さすが！

<audio controls>
<source src="04/063.mp3">
</audio><hr>

フフッ　やっぱり　パンダは最高だね

<audio controls>
<source src="04/064.mp3">
</audio><hr>



