---
title: "みんなのパフェ"
---

みんなのパフェ

<audio controls>
<source src="audio/10/001.mp3">
</audio><hr>

こんにちは

シロクマくん？

<audio controls>
<source src="audio/10/002.mp3">
</audio><hr>

どうしたの？　何か考え事？

これ

おだんご？

<audio controls>
<source src="audio/10/003.mp3">
</audio><hr>

なんで　信号って 赤　青　黄色の３色なのか考えてた

そうなんだ

<audio controls>
<source src="audio/10/004.mp3">
</audio><hr>

違うよ　パンダくん

シロクマさん　カフェのスペシャルメニューを 考えてるんだよ

スペシャルメニュー？

<audio controls>
<source src="audio/10/005.mp3">
</audio><hr>

また　実技　落とされちゃったよ…

実技？

ああ　自動車教習所ね

<audio controls>
<source src="audio/10/006.mp3">
</audio><hr>

大体　あの教官 細かすぎなんだよ！

どう細かいんですか？

<audio controls>
<source src="audio/10/007.mp3">
</audio><hr>

いやね　キョロキョロしないで まっすぐ前を見ろ！　とか

慌てすぎるな！　とか

ハンドルを握るときには 手を　パタパタさせるな！　とか

<audio controls>
<source src="audio/10/008.mp3">
</audio><hr>

それは　ダメなんじゃないですか？

あの教官のおかげで

いつまでたってもペン子さんを　ドライブデートに誘えないよ

<audio controls>
<source src="audio/10/009.mp3">
</audio><hr>

デート？

それは　テント

それは　弁当

それは　電灯

それは　剣道

デートだってば！！

<audio controls>
<source src="audio/10/010.mp3">
</audio><hr>

どうやったら　彼女のハートを 射止めることができるんだろう？

射止める…

シロクマくんなら　どうする？

<audio controls>
<source src="audio/10/011.mp3">
</audio><hr>

待つ

待つの？

うん　ひたすら待つね

へえ～っ　なんか大人だね

<audio controls>
<source src="audio/10/012.mp3">
</audio><hr>

そう　これができないと 大人になれない

なれない？

ひたすら　待って　待って　待って

<audio controls>
<source src="audio/10/013.mp3">
</audio><hr>

出てきたところを…

射止めてないよ！ それじゃ仕留めちゃうよ！

シロクマくん　ちゃんと考えてよ！

<audio controls>
<source src="audio/10/014.mp3">
</audio><hr>

ペンギンさん見てて思ったんだけど…

えっ　何？

笹子さん　パフェフェアーは　どうかな？

パフェですか　いいですね

<audio controls>
<source src="audio/10/015.mp3">
</audio><hr>

何それ？　デートと全然関係ないよね

どこをどうすれば　そうなるの？

さっきまでスペシャルメニューの話を してたんですけど

なかなか決まらなくて

<audio controls>
<source src="audio/10/016.mp3">
</audio><hr>

スペシャルメニューでパフェ？

僕　パフェ好き

<audio controls>
<source src="audio/10/017.mp3">
</audio><hr>

パフェはいいですけど

パフェフェアーって なんか言いづらいですよね

いや　全然大丈夫

よし　決まり

<audio controls>
<source src="audio/10/018.mp3">
</audio><hr>

パヘヘアーにしよう

言えてないよね

<audio controls>
<source src="audio/10/019.mp3">
</audio><hr>

イチゴパフェ　バナナパフェ　チョコパフェ

間違いはないけど　フェアなのに 定番だけじゃつまらない

<audio controls>
<source src="audio/10/020.mp3">
</audio><hr>

う～ん　スペシャルなパフェか

シロクマさん

パフェフェアー


をするんですよね？ 

<audio controls>
<source src="audio/10/021.mp3">
</audio><hr>

メニューは決まりましたか？

今　検討中

だったらマンドリルパフェは　どうですか？

<audio controls>
<source src="audio/10/022.mp3">
</audio><hr>

それ　何？

マンドリルなパフェです

それはもう　すごい迫力なんです！

<audio controls>
<source src="audio/10/023.mp3">
</audio><hr>

パフェに迫力はいらないかな

<audio controls>
<source src="audio/10/024.mp3">
</audio><hr>

う～ん　スペシャルなパフェね

シロクマさんじゃないですか

ああ　ラマさん

<audio controls>
<source src="audio/10/025.mp3">
</audio><hr>

こんにちは

聞きましたよ

何を？

パフェフェアーをやるんですよね？

ステキなパフェを思いついたんですよ

<audio controls>
<source src="audio/10/026.mp3">
</audio><hr>

パフェなのに　とってもヘルシーなんです

いいね　どんなの？

自信作ですよ

草　大盛りパフェです

<audio controls>
<source src="audio/10/027.mp3">
</audio><hr>

どんなパフェかというとですね

お皿の上に草がのっていてですね

お皿？

その上に水煮の草が のっていていてですね

<audio controls>
<source src="audio/10/028.mp3">
</audio><hr>

更に　その上に覆いかぶさるように 産地直送の草がのるんです

<audio controls>
<source src="audio/10/029.mp3">
</audio><hr>

いや　それすでにパフェじゃないし どっちかっていうとサラダかな

<audio controls>
<source src="audio/10/030.mp3">
</audio><hr>

う～ん　スペシャルなパフェ…

シロクマさ～ん　ここです！

<audio controls>
<source src="audio/10/031.mp3">
</audio><hr>

待って～！

は…　話があるから…

<audio controls>
<source src="audio/10/032.mp3">
</audio><hr>

どうしたの？　ゾウガメさん

パフェ…　フェ…

パフェフェアー？

甲羅パフェは？

<audio controls>
<source src="audio/10/033.mp3">
</audio><hr>

甲羅パフェ？

食べづらいかな

<audio controls>
<source src="audio/10/034.mp3">
</audio><hr>

う～ん　スペシャルなパフェ…

何が　いいかな？

<audio controls>
<source src="audio/10/035.mp3">
</audio><hr>

シロクマさん！

あっ！　コアリクイくん

すごいパフェを…

すごいパフェを考えました

<audio controls>
<source src="audio/10/036.mp3">
</audio><hr>

どんなパフェ？

それは　もう　すごいトッピングで！

ビジュアルは黒ゴマ的ですが…

すごく　うごめいている！

<audio controls>
<source src="audio/10/037.mp3">
</audio><hr>

いや　それは　いいかな

だから　めちゃくちゃ　生き生きと うごめいている　黒ゴマ的トッピングの…

<audio controls>
<source src="audio/10/038.mp3">
</audio><hr>

う～ん　和のテイストもいいけど…

どうしたの？　シロクマくん

<audio controls>
<source src="audio/10/039.mp3">
</audio><hr>

早く　パフェフェアーのメニュー　考えないと みんなが暴走してるから

暴走？(;ﾟДﾟ)!

<audio controls>
<source src="audio/10/040.mp3">
</audio><hr>

スペシャルメニューだけに　みんな 結構　楽しみにしてるんだね

はい　は～い！　僕に　いいアイディア

<audio controls>
<source src="audio/10/041.mp3">
</audio><hr>

はい

これ　これ！　竹パフェ

パンダくんに聞いて　作ってみました

すごいでしょ？

<audio controls>
<source src="audio/10/042.mp3">
</audio><hr>

竹ゼリーに笹クリームをのせて 新鮮な笹とタケノコをトッピングした上に

刻んだ竹が いっぱい　のっかってるの

<audio controls>
<source src="audio/10/043.mp3">
</audio><hr>

すごく緑色なパフェだね(-_-;)

パンダくん以外　食べないかも

そう？ こんなに　おいしそうなのに？

<audio controls>
<source src="audio/10/044.mp3">
</audio><hr>

刻んだ竹が口に刺さりそうだよ

パンダくん…　パフェって言えば なんでも　パフェだと思ってるでしょ

任せておけないよ

<audio controls>
<source src="audio/10/045.mp3">
</audio><hr>

よし　ここは　僕のアイディアを…

<audio controls>
<source src="audio/10/046.mp3">
</audio><hr>

イワシパフェ

ＤＨＡたっぷり　頭もよくなる

ダメ？

<audio controls>
<source src="audio/10/047.mp3">
</audio><hr>

じゃあ　今からだと 旬なアジとかでも　いいと思うよ

魚から離れようよ

なんていうか　それ パフェっていうより…

オシャレなお刺身？

<audio controls>
<source src="audio/10/048.mp3">
</audio><hr>

あっ！ こういうのは　どうでしょうか？

<audio controls>
<source src="audio/10/049.mp3">
</audio><hr>

パンダパフェ

パンダの頭は　バニラアイスで 耳や顔は　チョコレートです

<audio controls>
<source src="audio/10/050.mp3">
</audio><hr>

わぁ～！　パフェになっても パンダって　やっぱり　かわいいね

<audio controls>
<source src="audio/10/051.mp3">
</audio><hr>

クマクマパフェ

バニラとコーヒーアイスで作ってみました

いいね！

<audio controls>
<source src="audio/10/052.mp3">
</audio><hr>

南極パフェ

かき氷で氷山をイメージしました

すご～い！ かわいい！　新商品ですか？

あ…　いえ　試作品です

よかったら　どうぞ

えっ！？　いいんですか？

<audio controls>
<source src="audio/10/053.mp3">
</audio><hr>

では… いただきます！

<audio controls>
<source src="audio/10/054.mp3">
</audio><hr>

まずは　パンダさんから！

<audio controls>
<source src="audio/10/055.mp3">
</audio><hr>

じゃあ　ペンギンさんも！

<audio controls>
<source src="audio/10/056.mp3">
</audio><hr>

じゃあ　シロクマさんも！

<audio controls>
<source src="audio/10/057.mp3">
</audio><hr>

この鼻のとこ　食べちゃおうかな！

アハハハハ！　ひどい！！　私も　えい！

これ　絶対 お店で出してくださいね

よかった！　大人気です

<audio controls>
<source src="audio/10/058.mp3">
</audio><hr>

そ…　そうだね

ちょっと　聞いてよ！ また　今日も落とされたよ

<audio controls>
<source src="audio/10/060.mp3">
</audio><hr>

すみません　お水ください

いつも以上に大繁盛じゃない どうしたの？

新メニューのフェアが大人気らしいよ

<audio controls>
<source src="audio/10/061.mp3">
</audio><hr>

あぁ　パフェフェアー？

ワンプレートランチフェア

<audio controls>
<source src="audio/10/062.mp3">
</audio><hr>

パフェじゃないんだ？

<audio controls>
<source src="audio/10/063.mp3">
</audio><hr>

ペンギンさん　ペンギンさん

どうしたの　パンダ君

何も言わないで

<audio controls>
<source src="audio/10/064.mp3">
</audio><hr>

預金通帳もらえるかな

嫌だってこといいかな

<audio controls>
<source src="audio/10/065.mp3">
</audio><hr>

白熊君　まとめて

次回のしろくまカフェは

ボルトがル語でお送りします

日本語で行こう

お楽しみに

<audio controls>
<source src="audio/10/066.mp3">
</audio><hr>



