---
title: "七夕飾り"
---

七夕飾り

<audio controls>
<source src="audio/25/001.mp3">
</audio><hr>

あれ？

あんなところにおいしそうな笹が落ちてる

ちょっと味見

<audio controls>
<source src="audio/25/002.mp3">
</audio><hr>

おいしい！

まったく　もう…

もったいないな

おいしい！

あっ

<audio controls>
<source src="audio/25/003.mp3">
</audio><hr>

パンダくん

この笹　どうするの？

笹パーティー？

笹パーティー？

笹だらけのパーティーだよ

<audio controls>
<source src="audio/25/004.mp3">
</audio><hr>

七夕飾りに使うんだよ

明日　七夕だから

七夕？

<audio controls>
<source src="audio/25/005.mp3">
</audio><hr>

それは　棚ぼた

それは　井戸端

それは　花畑

七夕はね　

夏のお祭りだよ

<audio controls>
<source src="audio/25/006.mp3">
</audio><hr>

年に１回のね

お祭り？　やっぱり　笹パーティー？

違うよ

違うの？

<audio controls>
<source src="audio/25/007.mp3">
</audio><hr>

それで神様が怒ってしまい

彦星と引き離されたんだよね

<audio controls>
<source src="audio/25/008.mp3">
</audio><hr>

で　七夕っていうのは

その彦星と織姫の２人がね…

<audio controls>
<source src="audio/25/009.mp3">
</audio><hr>

鬼姫？

なんで怖い人がいるの？

つまりね　

<audio controls>
<source src="audio/25/010.mp3">
</audio><hr>

彦星と織姫と鬼姫の３人が揃うと

<audio controls>
<source src="audio/25/010.mp3">
</audio><hr>

夏の夜空に大三角が完成

違うよ！

三角関係ってやつ？

それも違うよ！

<audio controls>
<source src="audio/25/012.mp3">
</audio><hr>

でね　その彦星と織姫の２人が…

って…

<audio controls>
<source src="audio/25/013.mp3">
</audio><hr>

おいしい！

ちょっと…　聞いてる？

聞いてるよ　鬼の三角関係

<audio controls>
<source src="audio/25/014.mp3">
</audio><hr>

違うってば　もう…

七夕のこと教えてって言ったのパンダくんでしょう？

<audio controls>
<source src="audio/25/015.mp3">
</audio><hr>

それで　笹はいつ食べるの？

だから　食べないって

紙なんかで作った飾りをいっぱいつけて

それから　願いごとを書いた短冊なんかもぶら下げるんだよ

<audio controls>
<source src="audio/25/016.mp3">
</audio><hr>

そんなに　いろいろつけたら食べるとき邪魔だよ

<audio controls>
<source src="audio/25/017.mp3">
</audio><hr>

聞いてないな あの笹は食べないんだって

<audio controls>
<source src="audio/25/018.mp3">
</audio><hr>

それを先に言ってよ

言ってるよ！！

<audio controls>
<source src="audio/25/019.mp3">
</audio><hr>

笹を食べずに 短冊をぶら下げたら

願いごとが叶うよ

<audio controls>
<source src="audio/25/020.mp3">
</audio><hr>

どんな願いごとでも？

小さいのなら

大きい願いはダメなの？

<audio controls>
<source src="audio/25/021.mp3">
</audio><hr>

中くらいなら大丈夫じゃない？

何なの？　それ

<audio controls>
<source src="audio/25/022.mp3">
</audio><hr>

ねぇ　笹子さん

それが願いごとを書く紙？

<audio controls>
<source src="audio/25/023.mp3">
</audio><hr>

ああ… これは飾りを作ってるんだよ

おもしろそうだね

<audio controls>
<source src="audio/25/024.mp3">
</audio><hr>

パンダくんもやる？

うん！　やる　やる！

<audio controls>
<source src="audio/25/025.mp3">
</audio><hr>

こんにちは

お待たせしました

あっ…　どうも

<audio controls>
<source src="audio/25/026.mp3">
</audio><hr>

半田さん　動物園は今日はお休みなんですか？

えっ！？　は…　はい…

最近　よくいらっしゃいますよね

あっ…　いえ

いや　はい！

<audio controls>
<source src="audio/25/027.mp3">
</audio><hr>

こ…　ここに来ると…

<audio controls>
<source src="audio/25/028.mp3">
</audio><hr>

はい？

あっ　あぁ　いや

こ…　心が落ち着くというか

そうなんですか

<audio controls>
<source src="audio/25/029.mp3">
</audio><hr>

あっ　じゃあ お邪魔しちゃ悪いですね

ごゆっくり

<audio controls>
<source src="audio/25/030.mp3">
</audio><hr>

ねぇ　笹子さん　これ　どうやるの？

どうしたの？

どうしたらこうなるか不思議だよ

<audio controls>
<source src="audio/25/031.mp3">
</audio><hr>

ある意味　器用だね

もう そんなこと言っちゃダメですよ

いい？　ここはね

<audio controls>
<source src="audio/25/032.mp3">
</audio><hr>

まずはこっちから折るんだよ

こう？

パンダくん　反対

<audio controls>
<source src="audio/25/033.mp3">
</audio><hr>

それを３枚におろして…

できた！

<audio controls>
<source src="audio/25/034.mp3">
</audio><hr>

何それ？

パンダだよ

ああ　そう

白黒模様ではあるね

<audio controls>
<source src="audio/25/035.mp3">
</audio><hr>

はい　笹子さん

じゃあ　飾りは ひとまず置いといて

次は　短冊を作るね

<audio controls>
<source src="audio/25/036.mp3">
</audio><hr>

願いごとを書くやつ？

そうそう

<audio controls>
<source src="audio/25/037.mp3">
</audio><hr>

これに願いごとを書いてね

明日の夕方までに 持ってきてくれたら

笹につるすから

<audio controls>
<source src="audio/25/038.mp3">
</audio><hr>

これに中くらいまでの願いごとを書くの？

なんでも大丈夫だと思うよ

えっ？

<audio controls>
<source src="audio/25/038.mp3">
</audio><hr>

なんでもいいの？

なんでもいいんだよ

<audio controls>
<source src="audio/25/040.mp3">
</audio><hr>

どうしようかな～！

はい　ペンギンさんも　どうぞ

<audio controls>
<source src="audio/25/041.mp3">
</audio><hr>

真剣だね

なんでもいいんでしょ？

ペン子さんへの気持は なんでもよくないよ

<audio controls>
<source src="audio/25/042.mp3">
</audio><hr>

１枚じゃ足りないな

笹子さん　１０枚ちょうだい

<audio controls>
<source src="audio/25/043.mp3">
</audio><hr>

ずるい

じゃあ　僕は　２０枚

１人１枚です

<audio controls>
<source src="audio/25/044.mp3">
</audio><hr>

どうぞ

な…　なんでしょう？

半田さんも　はい

<audio controls>
<source src="audio/25/045.mp3">
</audio><hr>

短冊です　七夕の

<audio controls>
<source src="audio/25/046.mp3">
</audio><hr>

ありがとうございます

明日は七夕デーで夜遅くまでやってますからね

あっ　はい

それじゃ

<audio controls>
<source src="audio/25/047.mp3">
</audio><hr>

お願い　何書こう

笹がいっぱい食べられますようにって

どうかな？

<audio controls>
<source src="audio/25/048.mp3">
</audio><hr>

パンダくんいつもいっぱい食べてるじゃない

<audio controls>
<source src="audio/25/049.mp3">
</audio><hr>

ペンギンさんは　何書いたの？

まだだよ

１枚しかないから迷っちゃうね

<audio controls>
<source src="audio/25/050.mp3">
</audio><hr>

みんな何書いてるんだろう？

<audio controls>
<source src="audio/25/051.mp3">
</audio><hr>

お嫁さんが欲しい

いや　そもそもその前に彼女だよな

<audio controls>
<source src="audio/25/052.mp3">
</audio><hr>

すみません

は～い！ちょっと　お待ちくださ～い！

<audio controls>
<source src="audio/25/053.mp3">
</audio><hr>

笹子さん　かわいいな

<audio controls>
<source src="audio/25/054.mp3">
</audio><hr>

すみません なんでもないです　はい

パンダくん　

<audio controls>
<source src="audio/25/055.mp3">
</audio><hr>

聞いた？

かわいいよねぇ

いや　別に それだけが目的じゃ…

こ…　このカフェ　コーヒーおいしいし

<audio controls>
<source src="audio/25/056.mp3">
</audio><hr>

半田さん 動物園で会えるのに

かわいい僕を見に カフェに来るなんて

もう

<audio controls>
<source src="audio/25/057.mp3">
</audio><hr>

かわいいからね　僕

違うでしょ！ かわいいのは笹子さん

<audio controls>
<source src="audio/25/058.mp3">
</audio><hr>

笹子さん！

あのね…

<audio controls>
<source src="audio/25/059.mp3">
</audio><hr>

ダメ！！

なんで？

まだ　そんな 関係じゃないから！

<audio controls>
<source src="audio/25/060.mp3">
</audio><hr>

そうなの！

わかった

<audio controls>
<source src="audio/25/061.mp3">
</audio><hr>

ねぇ　笹子さん

動物の世話好きな男性とかどう思う？

<audio controls>
<source src="audio/25/062.mp3">
</audio><hr>

あと　パンダみたいな体型の男の人…

パ…　パンダくん！

どう思う？

こっち…　こっちへ！

何やってんの？　あれ

<audio controls>
<source src="audio/25/063.mp3">
</audio><hr>

さぁね

<audio controls>
<source src="audio/25/064.mp3">
</audio><hr>

