---
title: "サケハンター　グリズリーさん"
---

サケハンター　グリズリーさん

<audio controls>
<source src="audio/16/001.mp3">
</audio><hr>

おはよう

おはよう　パンダくん

あれ！？　これ　なんの荷物？

<audio controls>
<source src="audio/16/002.mp3">
</audio><hr>

お出かけの準備

えっ！？　出かけちゃうの？ カフェは？

今日はお休み

<audio controls>
<source src="audio/16/003.mp3">
</audio><hr>

せっかく　早起きできたからモーニング食べようと思ったのに

ごめんね

<audio controls>
<source src="audio/16/004.mp3">
</audio><hr>

どこ行くの？

今日はね…

シロクマ！ 用意はできてんだろうな？

<audio controls>
<source src="audio/16/005.mp3">
</audio><hr>

荷物はこれで全部か？

うん

グリズリーさんおはよう

おう

シロクマくんとどこ行くの？

<audio controls>
<source src="audio/16/006.mp3">
</audio><hr>

あぁ　ちょっと食材をな

料理の材料を発掘しに

<audio controls>
<source src="audio/16/007.mp3">
</audio><hr>

発掘？ 楽しそう！

僕も行きたい…

遊びじゃねえんだよ！

<audio controls>
<source src="audio/16/008.mp3">
</audio><hr>

まぁ　でも 遠足みたいなものかな

遠足？

笹はおやつに入る？ ごはんかな？

<audio controls>
<source src="audio/16/009.mp3">
</audio><hr>

う～ん…　難しいね

アザラシはごはんだけど…

おやつは？

セイウチかな

<audio controls>
<source src="audio/16/010.mp3">
</audio><hr>

何　ダラダラとくっちゃべってんだよ！

行くぞ 早く乗れ

<audio controls>
<source src="audio/16/011.mp3">
</audio><hr>

おい　シロクマ

何？　グリズリーくん

なんでアイツがいるんだよ？

グリズリーくんが乗れって言ったんじゃない

そうじゃなくてよ！

まぁ　いいじゃない

<audio controls>
<source src="audio/16/012.mp3">
</audio><hr>

ねぇ　どこ行くの？

山？　それとも　海？

山はおいしい笹がいっぱい生えてるし…

海はかわいい女の子がいっぱいいるよね

<audio controls>
<source src="audio/16/013.mp3">
</audio><hr>

川だよ

<audio controls>
<source src="audio/16/014.mp3">
</audio><hr>

お前は店で出す分が欲しいんだろ？

うん　いっぱい獲れるといいな

結構いそうな感じだぜ

あっ

<audio controls>
<source src="audio/16/015.mp3">
</audio><hr>

魚！

あれが俺たちの獲物だ

え…　あれが？

そうだ　サケだ

<audio controls>
<source src="audio/16/016.mp3">
</audio><hr>

なんだよ？

もっと　タケノコ的なものを 想像してたのに…

イヤなら帰れ！

なんだ…　発掘じゃないじゃない

<audio controls>
<source src="audio/16/017.mp3">
</audio><hr>

似たようなもんでしょ

そうかなぁ…

頑張ってよ

明日からのしろくまカフェのランチ

<audio controls>
<source src="audio/16/018.mp3">
</audio><hr>

グリズリー君にかかってるんだから

まったく…　他力本願なヤツめ

えっ　どうやって獲るの？

シッ！

<audio controls>
<source src="audio/16/019.mp3">
</audio><hr>

オラァッ！

オラ　１匹目！

２匹目！　３匹　４匹！

まぁ　俺の手にかかりゃ こんなもんよ

<audio controls>
<source src="audio/16/020.mp3">
</audio><hr>

さすが！

わぁ…　ピチピチしてる

ん？　このシチュエーション ガキの頃にもあったぞ…

<audio controls>
<source src="audio/16/021.mp3">
</audio><hr>

あれ？

全然　獲れねえ…

<audio controls>
<source src="audio/16/022.mp3">
</audio><hr>

なんだシロクマ！　テメエ！ 笑って見てんじゃねえ！

え？　笑ってないよ？

笑ってるだろうが　口がよ！

<audio controls>
<source src="audio/16/023.mp3">
</audio><hr>

口の下が黒いだけだよ

ホントだ　口　閉じてる

ね？

まぎらわしいヤツだな！

<audio controls>
<source src="audio/16/024.mp3">
</audio><hr>

うおりゃ～っ！

イテッ

やっぱ　笑ってんじゃねえか！

思わず…

アイツに笑われてた俺も

今じゃ　立派にサケが獲れるようになったんだぜ

<audio controls>
<source src="audio/16/025.mp3">
</audio><hr>

何やってんだ

えっ？　ピクニックの準備

俺が働いてるときに何だそりゃ！

まぁまぁ　グリズリーくんがサケ獲って お腹が空いたら

ランチができてるってわけ

<audio controls>
<source src="audio/16/026.mp3">
</audio><hr>

なかなか　いいでしょ

腹にたまるもんを頼むぜ

<audio controls>
<source src="audio/16/027.mp3">
</audio><hr>

ん？ サケがいねえ

何やってんだ！

なかなか グリズリーさんみたいにはいかないね

<audio controls>
<source src="audio/16/028.mp3">
</audio><hr>

誰でもできそうに見えたのにな

<audio controls>
<source src="audio/16/029.mp3">
</audio><hr>

いいか　よく見てろ

もういいや　笹食べよっと

そんな簡単に諦めんな！

えっ？

<audio controls>
<source src="audio/16/030.mp3">
</audio><hr>

でも疲れちゃったし お腹空いたし…

そういう問題じゃねえ！

同じクマとして　シロクマ！お前もコイツに何か言ってやれ！

<audio controls>
<source src="audio/16/031.mp3">
</audio><hr>

パンダくんは 竹と笹があれば満足だから

うん

何だと？

クマは狩りだろ 狩ってこそのクマだろ！

<audio controls>
<source src="audio/16/032.mp3">
</audio><hr>

タケノコだ！

ちょっとそこでとってきた

これだったら　パンダくんも狩りをする気になるでしょ

なるほどな

<audio controls>
<source src="audio/16/033.mp3">
</audio><hr>

えっ　サケってタケノコ食べるの？

違う

お前が食うんだよ　パンダ

パンダくん

<audio controls>
<source src="audio/16/034.mp3">
</audio><hr>

グリズリーくんが 狩りのお手本見せてくれるって

狩りをしてこそのクマだもんね

お　おう　よく見てろよ　パンダ

まずは　標的を見つける

<audio controls>
<source src="audio/16/035.mp3">
</audio><hr>

絶対に目を離さない

獲物の動きを予測する

<audio controls>
<source src="audio/16/036.mp3">
</audio><hr>

どうだ　やってみろ

おいしいね

って食ってんじゃねえ！

<audio controls>
<source src="audio/16/037.mp3">
</audio><hr>

ちゃんと泳いでるタケノコをとれ

タケノコは泳がないよ

だよね

んなの知ってる！

<audio controls>
<source src="audio/16/038.mp3">
</audio><hr>

イライラしないで　グリズリーさん

僕のとっておきの笹あげるから

笹は健康にもいいんだよ

<audio controls>
<source src="audio/16/039.mp3">
</audio><hr>

お前も食わず嫌いしてないで

サケくらい食ってみろよ

うん　わかった

<audio controls>
<source src="audio/16/040.mp3">
</audio><hr>

笹どう？

あんまし　うまくねえ

サケのほうがうまいだろ

ん～　あんまり

<audio controls>
<source src="audio/16/041.mp3">
</audio><hr>

いいニオイ！

コーヒー入ったよ

おう　ありがてえ

<audio controls>
<source src="audio/16/042.mp3">
</audio><hr>

おいしいね

ああ

いっぱいとれてよかったね

お前もな

<audio controls>
<source src="audio/16/043.mp3">
</audio><hr>

おい　パンダ！　こっちだ

いらっしゃい

おかげさまで大人気ですよ　ランチパスタ

<audio controls>
<source src="audio/16/044.mp3">
</audio><hr>

これって…

サケと…

タケノコ？

昨日のお礼ね

<audio controls>
<source src="audio/16/045.mp3">
</audio><hr>

おい　パンダ　俺のタケノコお前にやる

グリズリーさん　僕のサケあげるね

<audio controls>
<source src="audio/16/046.mp3">
</audio><hr>

あ　好き嫌いはダメですよ

細かいこと気にするなよ

そうそう

もう

まぁ　いいじゃない

<audio controls>
<source src="audio/16/047.mp3">
</audio><hr>
