---
title: "目指せ！　ワイルドパンダ"
---

目指せ！　ワイルドパンダ

<audio>
<source src="audio/12/001.mp3">
</audio><hr>

いらっしゃい

<audio>
<source src="audio/12/002.mp3">
</audio><hr>

こんにちは

何してるの　パンダくん

<audio>
<source src="audio/12/003.mp3">
</audio><hr>

どうしたの　その格好

悪いヤツな気分になってみたくて

ワルな人って憧れちゃうな

<audio>
<source src="audio/12/004.mp3">
</audio><hr>

パンダくん　いつもの？

うん　あ　いや　ストロングコーヒー

えっ　ストロング？　結構　苦いよ

<audio>
<source src="audio/12/005.mp3">
</audio><hr>

今日は　ワルの気分だから

はい　ストロング

いただきます

外せば

<audio>
<source src="audio/12/006.mp3">
</audio><hr>

ねぇ　ワルのどこに憧れたの？

ほら　僕って優柔不断だから

強気な人が羨ましくって

<audio>
<source src="audio/12/007.mp3">
</audio><hr>

それ　ワルとは関係ないでしょ

えっ　そう？

僕に足りないのは ワイルドさだと思うんだ

<audio>
<source src="audio/12/008.mp3">
</audio><hr>

ワイルドねぇ…

うわ～　苦っ！

やっぱり…

マイルドなコーヒーね

<audio>
<source src="audio/12/009.mp3">
</audio><hr>

いろいろビデオを見て ワイルドなイメージを膨らませてみたの

ビデオ？

うんとね…

<audio>
<source src="audio/12/010.mp3">
</audio><hr>


山吹色の お菓子でございます

<audio>
<source src="audio/12/011.mp3">
</audio><hr>

越後屋　お主もワルよのう

ノー　ノー！

<audio>
<source src="audio/12/012.mp3">
</audio><hr>

微妙に　ズレてない？　それ

イマイチ強気で ワイルドなイメージがつかめなくて

<audio>
<source src="audio/12/013.mp3">
</audio><hr>

強気で　ワイルドですか

グリズリーくんとか　そうかも

えっ　誰？　誰？

お店やってるから 夜　行ってみる？

<audio>
<source src="audio/12/014.mp3">
</audio><hr>

グリズリーさんのお店って　この辺りなの？

いや　もっと先

<audio>
<source src="audio/12/015.mp3">
</audio><hr>

ここを抜けると　すぐそこ

<audio>
<source src="audio/12/016.mp3">
</audio><hr>

着いたよ　ここね

<audio>
<source src="audio/12/017.mp3">
</audio><hr>

パンダくん　こっち　こっち

<audio>
<source src="audio/12/018.mp3">
</audio><hr>

確かに　ワイルドなお店だね

猛獣館って感じ？

<audio>
<source src="audio/12/019.mp3">
</audio><hr>

こんばんは　グリズリーくん 

よお　シロクマ 久しぶりじゃねえか

<audio>
<source src="audio/12/020.mp3">
</audio><hr>

本当に　ワイルドだ…

相変わらず なまっちろい野郎だぜ　この　シロクマ野郎

<audio>
<source src="audio/12/021.mp3">
</audio><hr>

ちょっと焼いてこいよ　日サロで

いや…　行っても たぶん変わらない

今日は　友達を連れてきた

<audio>
<source src="audio/12/022.mp3">
</audio><hr>

は…　はじめまして

白いのか　黒いのか はっきりしねえ野郎だな

<audio>
<source src="audio/12/023.mp3">
</audio><hr>

パンダだからね

まあ　いいか　座れ

<audio>
<source src="audio/12/024.mp3">
</audio><hr>

何にする？

シングルモルト

<audio>
<source src="audio/12/025.mp3">
</audio><hr>

おい　パンダ

はい…

お前は？

えっと…　竹　大盛り

悪いな　ヘルシーなものは 置いてないんだ

<audio>
<source src="audio/12/026.mp3">
</audio><hr>

じゃ…　じゃあ… アイスコーヒー　お願いします

ソフトドリンクもないね

<audio>
<source src="audio/12/027.mp3">
</audio><hr>

じゃあ　笹の入ったパフェを お願いします

ヘルシーなものは ないっつってんだろ！！

<audio>
<source src="audio/12/028.mp3">
</audio><hr>

グリズリーくん

しようがねえな

シロクマの友人だ 特別に　コーヒー　いれてやるよ

<audio>
<source src="audio/12/029.mp3">
</audio><hr>

ミルクは？

なしで

あっ　いや…　ありで

あっ　やっぱ　なしで

白黒　はっきりしろ！！

<audio>
<source src="audio/12/030.mp3">
</audio><hr>

もう…　相変わらず短気だな

まあ　パンダが白黒はっきりしたら

シロクマか ただのクマになっちまうよな

<audio>
<source src="audio/12/031.mp3">
</audio><hr>

グリズリーさんって　怖い人だね

そう？

<audio>
<source src="audio/12/032.mp3">
</audio><hr>

よう　兄ちゃん

アンタ　丸々と太ってて うまそうだな

<audio>
<source src="audio/12/033.mp3">
</audio><hr>

どうやって食べるのがいいかな

丸飲みとか

<audio>
<source src="audio/12/034.mp3">
</audio><hr>

ヤシの実とか

バーベキューとか

<audio>
<source src="audio/12/035.mp3">
</audio><hr>

もろきゅうとか

活け作りとか

若作りとか

<audio>
<source src="audio/12/036.mp3">
</audio><hr>

おい　お前！

あんまり他の客を 怖がらすんじゃねえよ

か…　帰ります！

<audio>
<source src="audio/12/037.mp3">
</audio><hr>

おい　パンダ！

悪かったな ほらよ　コーヒーだ

<audio>
<source src="audio/12/038.mp3">
</audio><hr>

グリズリーさん　ありがとう！

ねぇ　グリズリーさん

何だ？

<audio>
<source src="audio/12/039.mp3">
</audio><hr>

あの写真って グリズリーさんだよね？

うん？　おお　あれか

愛車で　アメリカを 横断したときのやつさ

かっこいい！

<audio>
<source src="audio/12/040.mp3">
</audio><hr>

よかったぜ　地平線まで続く道を ぶっ飛ばしてよ

わぁ～　憧れちゃうな

<audio>
<source src="audio/12/041.mp3">
</audio><hr>

どうせ　お前らはスローライフとかいって ダラダラ暮らしてやがんだろ？

<audio>
<source src="audio/12/042.mp3">
</audio><hr>

ロハスって言ってよ

言い方変えただけだろ

ゆっくりでも そんなに変わらないよ

昔からマイペースだよな　お前は

<audio>
<source src="audio/12/043.mp3">
</audio><hr>

人生は　一度きりだぜ

熱く　ぶっ飛ばさなきゃな

<audio>
<source src="audio/12/044.mp3">
</audio><hr>

グリズリーさん　すごくかっこいいね

僕　そういうの大好き！

おっ？ シロクマの知り合いにしちゃあ

話のわかるヤツじゃないか

ほら　冷めちまうぞ　飲めよ

うん！

<audio>
<source src="audio/12/045.mp3">
</audio><hr>

どうだ？ アイリッシュコーヒーにしてみたんだ

まっ　コーヒーより　ウイスキーのほうが 多かったかもな

えっ？　それは…

<audio>
<source src="audio/12/046.mp3">
</audio><hr>

また　ソイツと来いよ

今度は　インスタントじゃないコーヒーを いれてやるから

うん　マイルドで　よろしくね

<audio>
<source src="audio/12/047.mp3">
</audio><hr>

あれ？

目が覚めた？

シロクマくん　運んでくれたんだね

うん

ありがとう

<audio>
<source src="audio/12/048.mp3">
</audio><hr>

いいよ　別に

それと　もうひとつ　ありがとう

<audio>
<source src="audio/12/049.mp3">
</audio><hr>

えっ？

僕　だいぶ　ワイルドってのが わかった気がするよ

そう　それならよかった

<audio>
<source src="audio/12/050.mp3">
</audio><hr>

シロクマくん　どう？　これ　

ワイルド？

いやぁ　マイルドかな

じゃあ！

<audio>
<source src="audio/12/051.mp3">
</audio><hr>

あれ？　パンダくん　どこ行くの？

ワルは後ろを振り返らない

あっ　そう…

<audio>
<source src="audio/12/052.mp3">
</audio><hr>

ペンギンさん　ペンギンさん

どうしたの　パンダ君

ペンギンさんって　どうしてみんなに嫌われてるんだっけ

<audio>
<source src="audio/12/053.mp3">
</audio><hr>

そんな事実ないでしょう

人気ものだよ　僕は

どっちでもいいじゃない

次回のしろくまカフェは

<audio>
<source src="audio/12/054.mp3">
</audio><hr>

鉛筆書きでお送りします

塗ります

お楽しみに

<audio>
<source src="audio/12/055.mp3">
</audio><hr>

