---
title: "ラブラブ　ドライブ　大作戦"
---

ラブラブ　ドライブ　大作戦

<audio controls>
<source src="07/101.mp3">
</audio><hr>

見て　見て！

ついに取ったよ！

免許！

よかったね

ちょっと！ 

<audio controls>
<source src="07/102.mp3">
</audio><hr>

おめでとうって言ってよ！

それは　こんぺいとう！

<audio controls>
<source src="07/103.mp3">
</audio><hr>

それは　エッフェル塔！

それは　合気道！

<audio controls>
<source src="07/104.mp3">
</audio><hr>

違う！　全然違うよ

おめでとうございます

うん！　ありがとう

<audio controls>
<source src="07/105.mp3">
</audio><hr>

おめでとう

うん！

永遠に取れないかと思ったよ

縁起でもないこと 言わないでくれる？

<audio controls>
<source src="07/106.mp3">
</audio><hr>

さぁ　これで　ペン子さんと…

海へ　ドライブだよ！

<audio controls>
<source src="07/107.mp3">
</audio><hr>

いきなりはどうかな？

なんで？

たとえば…

道を間違えて　海へ行くはずが 山へ行っちゃったり…

<audio controls>
<source src="07/108.mp3">
</audio><hr>

ギア　壊しちゃったり…

ハンドル　引っこ抜いたり…

いや　そんな失敗しないから

<audio controls>
<source src="07/109.mp3">
</audio><hr>

でも　ただのドライブじゃないよね？

デートだよ　デート

<audio controls>
<source src="07/110.mp3">
</audio><hr>

ペン子さんを助手席に乗せて

洒落た会話をこなしつつ

しかも　道を間違えずに うまくエスコートできるかな？

すごいミッションだね

<audio controls>
<source src="07/111.mp3">
</audio><hr>


わかった！ 明日　予行演習しよう

<audio controls>
<source src="07/112.mp3">
</audio><hr>

デートの練習って何するの？

それは　いろいろ考えてあるから

ペンギンさん　おはよう

あれ？

<audio controls>
<source src="07/113.mp3">
</audio><hr>

ペン子さん…

ペンギンさん！

なんで　こんなとこで寝てるの？

<audio controls>
<source src="07/114.mp3">
</audio><hr>

いや…　

３時間前に来ちゃって…

早いのはいいけど 寝るのは最悪だね

その１　待ち合わせ　不合格

<audio controls>
<source src="07/115.mp3">
</audio><hr>

何それ？

採点表だよ

合格しないと デートする免許がもらえないの

<audio controls>
<source src="07/116.mp3">
</audio><hr>

デートにも免許がいるんだ？

いるの

いや　普通いらないから

<audio controls>
<source src="07/117.mp3">
</audio><hr>

ペンギンさん 今日は僕がデートの教官

わ…　わかってるよ

で…　今日の計画は？

海に行きます！

<audio controls>
<source src="07/118.mp3">
</audio><hr>

それだけ？

オシャレなレストランで食事したり

ムード盛り上げる演出はないの？

<audio controls>
<source src="07/119.mp3">
</audio><hr>

考えてなかったでしょ？

その２　段取り　不合格

<audio controls>
<source src="07/120.mp3">
</audio><hr>

合格までの道のりは 厳しそうだね

あとはどんなチェック項目があるの？

<audio controls>
<source src="07/121.mp3">
</audio><hr>

３　楽しい会話。

４　おいしい食事

５　ロマンチックなムード

<audio controls>
<source src="07/122.mp3">
</audio><hr>

全部合格すれば　仮免

で　ラブラブでドライブした最後に 愛の告白

そうすれば ラブラブ免許を獲得できるよ

えっ　ラブラブ免許？

<audio controls>
<source src="07/123.mp3">
</audio><hr>

すでに２つ不合格だね

え～っ！

じゃあ　やり直してみよう

はい

<audio controls>
<source src="07/124.mp3">
</audio><hr>

おはよう　待った？

おはよう

僕も　今　来たところだよ

いいね　合格

<audio controls>
<source src="07/125.mp3">
</audio><hr>

デートの計画は？

おいしいレストランに行って　海に行って

ムードを盛り上げて 告白します　教官

<audio controls>
<source src="07/126.mp3">
</audio><hr>

ザックリしてるけど　まぁ合格

じゃあ　いこうか

ハァー　なんか疲れた

シロクマくん　運転して

ダメでしょ　

<audio controls>
<source src="07/127.mp3">
</audio><hr>

それ

あ　おやつ忘れた

ペンギンさん持ってない？

気が散るから　話かけないで

<audio controls>
<source src="07/128.mp3">
</audio><hr>

そういえばさぁ　この間ね…

だから　話かけないで

３　楽しい会話　不合格

<audio controls>
<source src="07/129.mp3">
</audio><hr>

もっと盛り上げないと

だって　男３人でドライブじゃ 盛り上がらないよ

<audio controls>
<source src="07/130.mp3">
</audio><hr>

予行演習したいって言ったの ペンギンさんでしょ

そうだけどさ

仕方ないな

<audio controls>
<source src="07/131.mp3">
</audio><hr>

うわ～　ステキな景色ね

何やってるの？

僕がペン子さんのふりしてあげるから

えっ シロクマくん　今から女の子なんだ

<audio controls>
<source src="07/132.mp3">
</audio><hr>

私　日焼け止め持ってくるの忘れちゃった

へぇ～

ちょっと　それじゃダメ

<audio controls>
<source src="07/133.mp3">
</audio><hr>

えっ　何言えばいいの？

とにかく褒めて　私を褒めて

う　うん

<audio controls>
<source src="07/134.mp3">
</audio><hr>

シ　シロクマちゃんて 色白できれいだね

やだ　ペンギンさんたら

うわ～っ！

あら　ごめんなさい

<audio controls>
<source src="07/135.mp3">
</audio><hr>

私　最近　太っちゃって

へぇ～

へぇ～？

<audio controls>
<source src="07/136.mp3">
</audio><hr>

シ　シロクマちゃんみたいにポッチャリしてる 女の子のほうが　かわいいよ

ホント？

うわ～っ　シロクマちゃん　爪　　爪！

あら

<audio controls>
<source src="07/137.mp3">
</audio><hr>

ごめんなさい

爪　痛かったかしら

痛いよ！

シロクマちゃんの爪　頑丈でステキ

<audio controls>
<source src="07/138.mp3">
</audio><hr>

ホント？

ホント　ホント

３　楽しい会話　合格

よかったね　ペンギンさん

<audio controls>
<source src="07/139.mp3">
</audio><hr>

お昼は　どうする？

笹食べたい！

ん～　ペン子さんが 喜びそうなところ…

<audio controls>
<source src="07/140.mp3">
</audio><hr>

笹がない

全然　レストランじゃないわね

本番ではステキなシーフードレストランに行くから

<audio controls>
<source src="07/141.mp3">
</audio><hr>

すみません　サーモンください

売り切れです

シロクマくんが　食べきっちゃったよ　ここのサーモン

<audio controls>
<source src="07/142.mp3">
</audio><hr>

じゃあ　いきましょうか

もちろん　ペンギンさんのおごりね

えっ？

やだ　デートで女の子にお金払わせるつもり？

<audio controls>
<source src="07/143.mp3">
</audio><hr>

信じらんな～い

わかったよ…

４　おいしい食事も合格だね

<audio controls>
<source src="07/144.mp3">
</audio><hr>

う～ん…　デートで回転寿司って どうなのかしら…

あれだけ食べといて！？

じゃ　合格でいいよ　合格で…

<audio controls>
<source src="07/145.mp3">
</audio><hr>

会話…　ないんだけど

そこは　もう合格したから

ここからが本番だよ

ムード　盛り上げないと

どうやって？

<audio controls>
<source src="07/146.mp3">
</audio><hr>

会話が途切れたら　ＢＧМとか

ＣＤ　持ってきてないよ

じゃあ　僕　歌うよ

<audio controls>
<source src="07/147.mp3">
</audio><hr>

「ねむれ　ねむれ」

「母のむねに」

「ねむれ　ねむれ」

ペンギンさん！　眠っちゃ　ダメ！！

<audio controls>
<source src="07/148.mp3">
</audio><hr>

なんで　子守唄　歌うの！？

これじゃ　合格点　あげられないね

<audio controls>
<source src="07/149.mp3">
</audio><hr>

じゃあ　不合格？

海　見たら　絶対　盛り上がるから！

ペンギン的には

<audio controls>
<source src="07/150.mp3">
</audio><hr>

海だ

遠いけどね

道　間違えた…

<audio controls>
<source src="07/151.mp3">
</audio><hr>

あっ…　ペンギンさん　

１００円　１００円

もう見なくていいから…

もう… 

<audio controls>
<source src="07/152.mp3">
</audio><hr>

道　間違えるなんて　最低

ペン子さん　怒って帰っちゃうよ？

大丈夫…　これは　予行演習

今から行くと　ちょうど 海に夕日が沈む頃だから…

<audio controls>
<source src="07/153.mp3">
</audio><hr>

絶対　ロマンチックだよ！！

海だ

けど…

<audio controls>
<source src="07/154.mp3">
</audio><hr>

夕日　間に合わなかったね

５　ロマンチックなムードは　不合格と…

<audio controls>
<source src="07/155.mp3">
</audio><hr>

や…　夜景も　きれいじゃない？

ほらほら　ムードが盛り上がってるよ！

じゃあ　いってみる？　告白

<audio controls>
<source src="07/156.mp3">
</audio><hr>

いってみようよ

さあ　ペンギンさん

私への思いのたけを　熱く語って

ペ…　ペン子さん…

<audio controls>
<source src="07/157.mp3">
</audio><hr>

ずっと…　好きでした

僕と…

僕と…

つきあってください

はい

<audio controls>
<source src="07/158.mp3">
</audio><hr>

痛い！！

やったね！

いや…　練習とわかっていても ドキドキするよね

じゃあ… まあ　合格ってことで

<audio controls>
<source src="07/159.mp3">
</audio><hr>

はい　ラブラブ免許

やった！

よかったね

<audio controls>
<source src="07/160.mp3">
</audio><hr>

あっ　ペンギンさん

デート　どうだった？

はい　食べて

ありがとうございます

それで　デートは？

行ってないよ

<audio controls>
<source src="07/161.mp3">
</audio><hr>

えっ？

いや　ほら…　まだ夏じゃないし 海へドライブには早いよ

ダメじゃん…

<audio controls>
<source src="07/162.mp3">
</audio><hr>



