---
title: "リンリン感激　パンダくんち！"

---

リンリン感激　パンダくんち！

<audio>
<source src="audio/17/001.mp3">
</audio><hr>

お花 こちらでよろしいでしょうか

は　はい　それでお願いします

またいらしてくださいね

<audio>
<source src="audio/17/002.mp3">
</audio><hr>

はい！

かっこいいよね

<audio>
<source src="audio/17/003.mp3">
</audio><hr>

パンダくん　

バイトお疲れ　はい　これ

まぁ もらっておくけど

そんじゃ　お疲れ

<audio>
<source src="audio/17/004.mp3">
</audio><hr>

パンダくん　つれないな

あ～　パンダくん 仲よくなりたいのに

<audio>
<source src="audio/17/005.mp3">
</audio><hr>

大丈夫　きっと仲よくなれるよ

そうだよね　

もちろんさ

パンダ最高！

<audio>
<source src="audio/17/006.mp3">
</audio><hr>

はい　フローリスト リンリンです

竹をメインにしたアレンジですか

はい　できますよ

で　お届けはどちらまで

<audio>
<source src="audio/17/007.mp3">
</audio><hr>

リンリンてさ　困った人だよね

リンリンて

花屋さんの

そう　僕が通りかかるたびにさ

<audio>
<source src="audio/17/008.mp3">
</audio><hr>

あげる

好きでしょ

パンダって　かわいいよね

いい人じゃない

あれ？

<audio>
<source src="audio/17/009.mp3">
</audio><hr>

でもでも

くれるパンダグッズだって趣味悪いし

こんなのとか

わ～　かわいい！

え～　そうかな

じゃあ　笹子さんにあげれば

<audio>
<source src="audio/17/010.mp3">
</audio><hr>

あげないよ

気に入ってるじゃない

リンリンて　ホント困った人だから

今頃パンダくんの家に行ってたりして

やめてよ

<audio>
<source src="audio/17/011.mp3">
</audio><hr>

パンダくんちだよ

お花をお届けにあがりました

<audio>
<source src="audio/17/012.mp3">
</audio><hr>

パンダくんは…　

この時間は　しろくまカフェかな

どうも　ご苦労様です

<audio>
<source src="audio/17/013.mp3">
</audio><hr>

どうしました？

パンダだ　パンダママだ

あ　ねぇ

はい

お代は別に払うから　部屋の竹も活け直してもらえないかしら

お家に 上がっていいんですか！

<audio>
<source src="audio/17/014.mp3">
</audio><hr>

リンリンのパンダ好きは相当なものらしいよ

パンダグッズも かなり集めてるそうですよ

花屋じゃなくて パンダグッズ屋やればよかったのに

事情があるんだよ

<audio>
<source src="audio/17/015.mp3">
</audio><hr>

どんな？

若き日のリンリンが パンダグッズを集めるため　世界を旅していた頃

とある事件に巻き込まれ…

<audio>
<source src="audio/17/016.mp3">
</audio><hr>

嘘ですね

うん

何で嘘つくの？

ささやかな嘘で あなたの味気ない日常に彩りを

味気ない日常で悪かったね

もう　リンリンの話はいいよ

<audio>
<source src="audio/17/017.mp3">
</audio><hr>

よし　いかがです？

まぁ　ステキ！

今　お代を払うわ

ちょっと待っててね

ここでパンダくんが 暮らしているんだな

<audio>
<source src="audio/17/018.mp3">
</audio><hr>

かわいい

こんにちは

ママがお茶どうぞって

パンダだ　パンダ妹だ

<audio>
<source src="audio/17/019.mp3">
</audio><hr>

ここに置いとくね

ありがとう…　えっと…

メイメイって呼んで

あなた　リンリンでしょ？

僕のこと　知ってるんだ？

<audio>
<source src="audio/17/020.mp3">
</audio><hr>

イケメン花屋って街じゃ有名よ

そうらしいね

否定しないのね…

でも…　私の好みじゃないわね

<audio>
<source src="audio/17/021.mp3">
</audio><hr>

ちょっと痩せすぎ

まあ　いいわ ちょっと遊んであげる

鬼ごっこね

ああ　ごめん お店があるから　帰らないと

<audio>
<source src="audio/17/022.mp3">
</audio><hr>

リンリンさん　お待たせ

あら？

<audio>
<source src="audio/17/023.mp3">
</audio><hr>

待て！

パンダを追いかける…

パンダと回る…

<audio>
<source src="audio/17/024.mp3">
</audio><hr>

パンダと転がる…

なんて幸せな時間なんだ…

次は　かくれんぼね

<audio>
<source src="audio/17/025.mp3">
</audio><hr>

パンダと　かくれんぼ…

１　２…

リンリンさん案外タフね

<audio>
<source src="audio/17/026.mp3">
</audio><hr>

お～い　どこだい？

店に戻らないで 遊んでていいのか？

<audio>
<source src="audio/17/027.mp3">
</audio><hr>

いい！

だって　パンダなんだも～ん！

見つけた！

何奴？

<audio>
<source src="audio/17/028.mp3">
</audio><hr>

どうしたの？

あっ　お爺ちゃん 何やってるの？

お爺ちゃん？

曲者め

違うわよ　リンリンは　お花屋さんよ

<audio>
<source src="audio/17/029.mp3">
</audio><hr>

ニチニチ　コレコー　ニチ…

ジョージョー　シャクリョー　セーコー　トーテー…

都合が悪くなると すぐとぼけるんだから

アオゾラチューシャ…

パンダ…　だ…

<audio>
<source src="audio/17/030.mp3">
</audio><hr>

パンダお爺ちゃんの太極拳…　だ…

<audio>
<source src="audio/17/031.mp3">
</audio><hr>

というわけで

彼は　パンダグッズ屋ではなく

花屋を営むこととなりました

悲しすぎる…　

ホラ話と わかってても　涙が止まらない…

<audio>
<source src="audio/17/032.mp3">
</audio><hr>

思わず　リンリンに 優しくしちゃいそうだよ

事情があるんだよ

それはあの眩しくも世知辛い国でのことだった

いや　さすがに　もういい

<audio>
<source src="audio/17/033.mp3">
</audio><hr>

あっ…　あれ？　ここは…

イテテ…　あっ　そうか

パンダくんちに配達に来て　それで…

まいったな… 早く店に帰らなきゃ

<audio>
<source src="audio/17/034.mp3">
</audio><hr>

こ…　これは　パンダくんの…

もしかして　この部屋は…

パンダくんの部屋？

<audio>
<source src="audio/17/035.mp3">
</audio><hr>

パンダくんのベッド… パンダくんのパンダクッション

パンダくんのパンダスリッパ！ パンダくんのシール…

<audio>
<source src="audio/17/036.mp3">
</audio><hr>

あっ…　これ　僕があげたプレゼント

なんだよ… 大事にしてくれてるじゃん

<audio>
<source src="audio/17/037.mp3">
</audio><hr>

うぉ～！

仔パンダ！！

うぉ～！　超かわいい！！

さ…　触りたい

<audio>
<source src="audio/17/038.mp3">
</audio><hr>

ダメだよ　それは観賞用だよ

くれるの？

かわいい！

<audio>
<source src="audio/17/039.mp3">
</audio><hr>

お目覚め？　ごめんなさいね

うちの　お爺ちゃんが…あら？

ありがとう！　おいしいな

<audio>
<source src="audio/17/040.mp3">
</audio><hr>

リンリン！？　それ　観賞用よ

っていうか　笹　食べるの？

<audio>
<source src="audio/17/041.mp3">
</audio><hr>

えぇ　状況しだいでは

まぁ　止めないけど…

あの…　お花代　まだ お支払いしてなかったでしょ？

<audio>
<source src="audio/17/042.mp3">
</audio><hr>

お代はいらないので 仔パンダ　抱っこさせてください！

いいけど…

ちゃんと払うわよ

<audio>
<source src="audio/17/043.mp3">
</audio><hr>

あら…　ごめんなさい

うちの子人見知りで…

幸せです！

<audio>
<source src="audio/17/044.mp3">
</audio><hr>

お花 こちらで　よろしいでしょうか？

厘太郎さん　どうしたのかしら？

傷だらけね

パンダママさんや　妹ちゃんとは 仲よくなれたんだ

<audio>
<source src="audio/17/045.mp3">
</audio><hr>

今度は　パンダお爺ちゃんと 仔パンダちゃんたち…

そして　いずれは…

ねぇ　ねぇ　半田さん

<audio>
<source src="audio/17/046.mp3">
</audio><hr>

今日　帰りにさ…

今日は　ダメ！　用事あるの

ちょっとくらい　いいじゃん

彼女もいないし　暇でしょ？

<audio>
<source src="audio/17/047.mp3">
</audio><hr>

もう…　パンダくんより 女の子に追いかけられたいよ

あ～っ！　ひどい

パンダくんより　だと！？

<audio>
<source src="audio/17/048.mp3">
</audio><hr>

うらやましい！

何か　視線を感じるんだけど…

そう？

<audio>
<source src="audio/17/049.mp3">
</audio><hr>

