---
title: "ペンギンさんのロマンス"
---

<span id="episode-title" data-episode="30">ペンギンさんのロマンス</span>

<audio></audio><hr>


夏ですね

夏だね

今年は蝉がよく泣きますね

<audio></audio><hr>


雄は腹腔内の発音筋と発音膜で音を

出して共鳴室で音を大きく出して雌を呼んでるね

<audio></audio><hr>


情緒のない言い方やめてくれますか

<audio></audio><hr>


どうしたのパンダ君

食べないの　パンダあんぱん

体調悪いの

<audio></audio><hr>


毎日パンじゃなくて　たまには高級フルーツでも買ってきてよ

<audio></audio><hr>


果物屋にはペン子さんがいないじゃない

ペンギンさん

何？　パン食べる

<audio></audio><hr>


いいえ　そうじゃなくて

ペンギンさん　夏にはペン子さんに告白して ドライブって言ってませんでしたっけ

<audio></audio><hr>


もう夏だね

夏とは言ったけど今年のとはいってないでしょう

<audio></audio><hr>


来年かもしれないし　再来年かもしれないし　

十年後の夏かもしれないよ

<audio></audio><hr>


そんな長いスパンの話なんですか

もう　今からチョロっと告白してきなよ

チョロっとって　ちょっと待ってよ

<audio></audio><hr>


いいんじゃないですか　告白してきたら

告白に当たっての心の準備をしないとだね

いやいや　その前に心の準備の用意の前振りをだね

<audio></audio><hr>


でも早く告白しないと　

ペン子さん取られちゃうかもしれないですよ

<audio></audio><hr>


けど　ふられたらどうしよう

大丈夫だよ　まだふられたわけじゃないんだから

<audio></audio><hr>


そうですよ

ちゃんと告白して　ふられようよ

白熊さん

<audio></audio><hr>


そうだね

いつかの夏にと思ってたけど

もう告白してしまおうかな

<audio></audio><hr>


そうですよ

そうだよ　ふられるなら　早いほうがいいよ

<audio></audio><hr>


パンダ君

よし　行くよ

これで　ようやく彼女の名前も分かるしね

<audio></audio><hr>


何？

ペン子さんじゃないの

え？言ってなかった

ペン子さんっていうのは　

僕が彼女に付けた名前だよ

<audio></audio><hr>


まさか　名前知らないんですか

知らないよ

悪い？

<audio></audio><hr>


だって

じゃ　笹子さんは名前も知らない花をきれいだなって思ったことはないですか

<audio></audio><hr>


名前も知らない美味しい魚を食べたことはないですか

名前も知らない曲に心揺さぶれたことはないですか

<audio></audio><hr>


名前も知らない未知の風景に美しいと思ったことはないですか

分かりましたから　もう行ってください

じゃ

<audio></audio><hr>


名前も知らないんですね

大丈夫ですかね

<audio></audio><hr>


ありがとうございました

いらっしゃいませ

あのう

今日はサービス券もらいに来たんじゃないです

<audio></audio><hr>


言わなくていい言葉だった

<audio></audio><hr>


待とう　人がいなくなるのを

またくるわ

ありがとうございました

<audio></audio><hr>


いまだ　今しかない　でも緊張してきた

こういう時どうするんだっけ

<audio></audio><hr>


人という字3回書いて呑むんだ

いや　待ってよ

<audio></audio><hr>


ペンギンの場合は　ペンギンって3回書いて呑む方がいいのかな

ペ－ン－ギ－ン

ペ－ン－ギ－ン

ペ－ン－ギ－ン

<audio></audio><hr>


そんなたくさんの文字呑めるか

あのう

<audio></audio><hr>


すみません　大きいな声出して

いいえ　いつもありがとうございます

<audio></audio><hr>


いえ　そんな大したこと

分かります　すごく好きなんだなって

<audio></audio><hr>


パンが

ありがとうございました

<audio></audio><hr>


あのう

はい

前からあなたの事が好きでした

僕とデートしてください

日曜日駅前で一時にまってます

それじゃ

<audio></audio><hr>


あれからペンギンさん　毎日パン屋さんに行ってデートに誘ってるらしいですよ

今日で四日目ですって

ＯＫもらうまで通うって

<audio></audio><hr>


しつこくない

そんなことないよ

ペンギンさん頑張ってるよね

<audio></audio><hr>


笹子さんは毎日毎日しつこく誘われたらどうなの

え　

<audio></audio><hr>


それは嫌ですけど

<audio></audio><hr>


今日で一週間ですよ

幸せなんじゃないですかね

こんなふうに一途に思われたら

<audio></audio><hr>


そう

そうですよ

笹子さんは一週間　毎日毎日しつこくされるのはどうなの

<audio></audio><hr>


それは嫌ですけど

<audio></audio><hr>


前からあなたの事が好きでした

僕とデートしてください

日曜日駅前で一時にまってます

<audio></audio><hr>


日曜日って明日ですよね

うん　はい　急ですね　すみません

<audio></audio><hr>


分かりました　

え？

<audio></audio><hr>


僕らはね　最初から愛し合っていたんじゃないかな

一週間毎日パン屋さんに行って　告白をしたわけだよ

<audio></audio><hr>


でね　とうとう一週間目のことだよ

それでさ　ペン美ちゃんがね

<audio></audio><hr>


あ　彼女ペン子ちゃんじゃなくて　ペン美ちゃんって名前だったんだけど

ペン美ちゃんがどうしたって聞いてみて

<audio></audio><hr>


もう5回目だよ

聞いたほうがいいんですか

<audio></audio><hr>


だから　ペン美ちゃんがどうしたか聞いてみて

ペン美ちゃんがどうしたんですか？

<audio></audio><hr>


日曜日って明日ですかって聞いてきたの

もう分かったよ

<audio></audio><hr>


きっと僕たちは　愛し合う運命だったんだよ

あ　パン食べて　いいから　遠慮なく食べて

じゃ　

<audio></audio><hr>


また明日～

明日は何回聞けばいいのかな

<audio></audio><hr>


20回くらい

<audio></audio><hr>


ペン美ちゃんまだかな

まだちょっと早かったかな

ペン美ちゃん

<audio></audio><hr>


おい　ペン美ちゃん

え　あたしペン子だけど

<audio></audio><hr>


え

ちょっと　どういうこと？

え！ペン美ちゃんがもう一人

何言ってるの　

<audio></audio><hr>


わたし　ペン花よ

え！

ちょっとあんた　あたしのこと好きだったんじゃないの

<audio></audio><hr>


あれ　君がペン美ちゃん？

ペン奈よ

ペン乃よ

どういうこと？

<audio></audio><hr>


違うんだペン美ちゃん　

ペンジョリナよ

ペンジョリナ

<audio></audio><hr>


ちょっと　ペンギンさん

ごめんペン美ちゃん

これはその

ペンニュエルよ

ペンニュエル！

<audio></audio><hr>


ペンギンさん

はい

あたしがペン美よ

どういうこと？

<audio></audio><hr>


いや　どういう事なんだろ

<audio></audio><hr>


どういうこと？

ペ　ペン美ちゃん

ペ　ペン乃ちゃん

やめて　あ　いたい

ペン美ちゃん　ペン美ちゃん　助けて

<audio></audio><hr>


まさか七人いるなんて思わなかった

毎日違う子に告白してたなんて

<audio></audio><hr>


パン屋さんのシフトのせいだ

<audio></audio><hr>


シフト目

行くよ

もう

気配がするんだよ

<audio></audio><hr>


ペンギンさん　告白できてよかったね

これで　良かったんですかね

笹子さんは　

<audio></audio><hr>


毎日毎日しつこくノロケ話を聞かされるのってどうなの

さあー

<audio></audio><hr>



