---
title: "白熊君張切る"
---

白熊君張切る

<audio controls>
<source src="audio/27/001.mp3">
</audio><hr>

どうしたの　パンダ君　溜息なんかついて

<audio controls>
<source src="audio/27/002.mp3">
</audio><hr>

バイト行きたくないよ

またそれ

本当に何もすることなくて　超退屈なんだもん

<audio controls>
<source src="audio/27/003.mp3">
</audio><hr>

常勤パンダさんとあっち向いてほいとかしても

<audio controls>
<source src="audio/27/004.mp3">
</audio><hr>

十五分ぐらい厭きるし

よく十五分もできるね

十五秒で厭きるよ

<audio controls>
<source src="audio/27/005.mp3">
</audio><hr>

ペンギンさん　時間潰すのって大変だよ

<audio controls>
<source src="audio/27/006.mp3">
</audio><hr>

仕方ないから　いっぱいお昼寝してたら

<audio controls>
<source src="audio/27/007.mp3">
</audio><hr>

寝違えって　首回らなくなっちゃうし

ぶーくりおやつ食べても　ちょっびとの時間しか経たないし

<audio controls>
<source src="audio/27/008.mp3">
</audio><hr>

パンダのバイト始めてから　おやつの食べ過ぎで太っちゃった

また

<audio controls>
<source src="audio/27/009.mp3">
</audio><hr>

バイトのせいだよ

それだけが理由かな

そうだよ

<audio controls>
<source src="audio/27/010.mp3">
</audio><hr>

バイトしてるから太るんだよ

パンダ君のバイトって　週二日だよね

週二日で文句言わないでよ

<audio controls>
<source src="audio/27/011.mp3">
</audio><hr>

むしろ毎日行こうよ

そうだね

そうだよ

週一日にしようかな

<audio controls>
<source src="audio/27/012.mp3">
</audio><hr>

減らすの

いいな　僕は仕事忙しくて　もう少し暇になりたい

そうなの

<audio controls>
<source src="audio/27/013.mp3">
</audio><hr>

偶には気分転換したいね

お店忙しいですもんね

<audio controls>
<source src="audio/27/014.mp3">
</audio><hr>

いいなぁ　忙しいの

パンダ君になってゴロゴロしたい

もう　二人とも ないもの強請りなんだから

<audio controls>
<source src="audio/27/015.mp3">
</audio><hr>

笹子さん　何か言ってやってよ

そう言われても…

<audio controls>
<source src="audio/27/016.mp3">
</audio><hr>

いい事思いついちゃった

何ですか

パンダ君　一日だけ入れ替わってみない？

<audio controls>
<source src="audio/27/017.mp3">
</audio><hr>

僕が動物園へパンダのバイトに行くから

パンダ君は白熊カフェでマスターするの

<audio controls>
<source src="audio/27/018.mp3">
</audio><hr>

いやいや　無理でしょ

いいなぁ

白熊君ってかっこいいから　一回やってみたっかたんだ

<audio controls>
<source src="audio/27/019.mp3">
</audio><hr>

いや　無理でしょ

へぇ　そうかな

白熊君　変なこと言わないでよ

<audio controls>
<source src="audio/27/020.mp3">
</audio><hr>

あ　おはよう　パンダ君

…じゃないですよね

<audio controls>
<source src="audio/27/021.mp3">
</audio><hr>

パンダで~す

<audio controls>
<source src="audio/27/022.mp3">
</audio><hr>

パンダコーナーってこっちだっけ？

ちょっと待ってよ！白熊君でしょ？

あれ　

<audio controls>
<source src="audio/27/023.mp3">
</audio><hr>

ばれちゃった

半田さん　平気平気

お客さんには熊の区別なんてつかないから

<audio controls>
<source src="audio/27/024.mp3">
</audio><hr>

何言ってるの

白熊君なの　物分りだよ　

帰って帰って

<audio controls>
<source src="audio/27/025.mp3">
</audio><hr>

待ってください　先輩

何だ　桐野

今日は　常勤パンダさんが有給休暇で休みですよ

そうなると…

<audio controls>
<source src="audio/27/026.mp3">
</audio><hr>

ママ　パンダさんいないよ

白熊君　パンダ君は？

<audio controls>
<source src="audio/27/027.mp3">
</audio><hr>

今日は来ないよ

今すぐ呼んで！

今から呼んでも間に合わないよ

<audio controls>
<source src="audio/27/028.mp3">
</audio><hr>

大丈夫　任せて

<audio controls>
<source src="audio/27/029.mp3">
</audio><hr>

な…なるべく目立たないように　お願いします

は～い～　頑張ります

<audio controls>
<source src="audio/27/030.mp3">
</audio><hr>

パンダ君　美味しそうな笹が手に入ったから　

差し入れだ…よっ

<audio controls>
<source src="audio/27/031.mp3">
</audio><hr>

パンダで～す

<audio controls>
<source src="audio/27/032.mp3">
</audio><hr>

気になって見に来ちゃったよ

パンダだよ

<audio controls>
<source src="audio/27/033.mp3">
</audio><hr>

何だか熱があるみたいだ

<audio controls>
<source src="audio/27/034.mp3">
</audio><hr>

あれ？可愛くない？

変だなぁ…

やっぱり無理だよ　全然違うよ

あれがパンダ？

<audio controls>
<source src="audio/27/035.mp3">
</audio><hr>

何が違くねぇ？長すぎるっていうか　でか過ぎねぇ？

でも俺ら生パンダ見るの始めてたし　

ああいうのかも

<audio controls>
<source src="audio/27/036.mp3">
</audio><hr>

そうだけどうさぁ…

なんかあのシルエットは白熊じゃねぇ？

おっと　いけない

アイテム装備　

<audio controls>
<source src="audio/27/037.mp3">
</audio><hr>

そうして技を使う

<audio controls>
<source src="audio/27/038.mp3">
</audio><hr>

ほら　やっぱりパンダだよ

あはは　本当だ

パンダさん　

でけぇ

白熊君　グッドジョブ

<audio controls>
<source src="audio/27/039.mp3">
</audio><hr>

かしこまりました

すみません

はい　ただいま

<audio controls>
<source src="audio/27/040.mp3">
</audio><hr>

確かに暇な仕事だ

<audio controls>
<source src="audio/27/041.mp3">
</audio><hr>

あんまり動かないなぁ

パンダだもん　仕方ないよ

おっと　サービス　サービス

<audio controls>
<source src="audio/27/042.mp3">
</audio><hr>

あれ　タイヤでどうやって遊べばいいんだっけ

<audio controls>
<source src="audio/27/043.mp3">
</audio><hr>

困ってねぇ

パンダさんどうしたの

どうしよう　皆怪しんでるよ

<audio controls>
<source src="audio/27/044.mp3">
</audio><hr>

おほ　遊んでる　遊んでる

<audio controls>
<source src="audio/27/045.mp3">
</audio><hr>

何だ　今の

もう　白熊君がありえない動きするから

<audio controls>
<source src="audio/27/046.mp3">
</audio><hr>

生パンダはやっぱ違うなぁ

セーフ

<audio controls>
<source src="audio/27/047.mp3">
</audio><hr>

よし　もっとサービスしよう

<audio controls>
<source src="audio/27/048.mp3">
</audio><hr>

うわっ　白熊だ

<audio controls>
<source src="audio/27/049.mp3">
</audio><hr>

うぉっ　パンダだ

うわっ　白熊だ

<audio controls>
<source src="audio/27/050.mp3">
</audio><hr>

うぉっ　パンダだ

うわっ　白熊だ

うわっ　パンダだ

ちょっちょっちょっ　白熊君

（パンダ　白熊　パンダ　白熊……）

<audio controls>
<source src="audio/27/051.mp3">
</audio><hr>

パンダがいないとまずい

白熊パンダがばれてもやばすぎる

<audio controls>
<source src="audio/27/052.mp3">
</audio><hr>

はぁ…始末書の用意しといたほうがいいかな

半田さん　大変です

<audio controls>
<source src="audio/27/053.mp3">
</audio><hr>

あ！ついに来た！ついにばれた

パンダ君が大人気ですよ

どうしよう！　え？

<audio controls>
<source src="audio/27/054.mp3">
</audio><hr>

よし　

すげぇー　あの距離を沈めたぞ

マスタスでられじゃねぇ？

どうも　どうも

<audio controls>
<source src="audio/27/055.mp3">
</audio><hr>

パンダさん　かっこいい

パンダグッズも飛ぶように売れてます

<audio controls>
<source src="audio/27/056.mp3">
</audio><hr>

このパンダティシャツください

パンダバッグ三色全部

半田さん　

<audio controls>
<source src="audio/27/057.mp3">
</audio><hr>

大成功でしょ

<audio controls>
<source src="audio/27/058.mp3">
</audio><hr>

そういえば　あっちはどうなったかな

<audio controls>
<source src="audio/27/059.mp3">
</audio><hr>

こんにちは

いらっしゃいませ

<audio controls>
<source src="audio/27/060.mp3">
</audio><hr>

なにしようかな　えっと

いや　その　白熊にしてはちょっと小さい

<audio controls>
<source src="audio/27/061.mp3">
</audio><hr>

というか

パンダ君だよね

いいえ　白熊ですよ

<audio controls>
<source src="audio/27/062.mp3">
</audio><hr>

白熊君　どこ行ったの

ここにいますよ

<audio controls>
<source src="audio/27/063.mp3">
</audio><hr>

ばればれだね

ですね

<audio controls>
<source src="audio/27/064.mp3">
</audio><hr>
