---
title: "パンダくんの願い"
---

パンダくんの願い

<audio controls>
<source src="audio/26/001.mp3">
</audio><hr>

ほほう…　半田さんがね

<audio controls>
<source src="audio/26/002.mp3">
</audio><hr>

なんで　はっきり言わないのかな？

半田さんは　奥手だしね

そうなの？

<audio controls>
<source src="audio/26/003.mp3">
</audio><hr>

雑誌なんかで知識は豊富そうだけど

いざとなるとてんで勇気が出ないタイプだね

<audio controls>
<source src="audio/26/004.mp3">
</audio><hr>

あぁ　知ってる

えっと…　たしか耳年寄り？

ツッコみづらい間違え方しないでよ

<audio controls>
<source src="audio/26/005.mp3">
</audio><hr>

半田さんにアドバイスしたいんだけど 何かない？

こっちに振るの？

<audio controls>
<source src="audio/26/006.mp3">
</audio><hr>

だって　常勤パンダさん経験豊富でしょ？　

バツ２だし

勝手に　バツ２にしないでって 言ったでしょ

<audio controls>
<source src="audio/26/007.mp3">
</audio><hr>

でもさ　

僕らってカップルに関しては目が肥えてるよね

あぁ　それは確かにね

<audio controls>
<source src="audio/26/008.mp3">
</audio><hr>

ここに来るお客さんは カップル多いもんね

そうだね

初デートのカップルなんてういういしいよね

<audio controls>
<source src="audio/26/009.mp3">
</audio><hr>

手を繋ぐことも できなかったりしてさ

うん　うん

あとはケンカしてるカップルとかもいるよね

こっちから見てても わかるっていうか

<audio controls>
<source src="audio/26/010.mp3">
</audio><hr>

そう？

ほら！こっちに来る あの２人は

今ちょっと気まずい感じだね

<audio controls>
<source src="audio/26/011.mp3">
</audio><hr>

あぁ　本当だ

でもね　見てなよ

そこで　僕らを見つけると…

<audio controls>
<source src="audio/26/012.mp3">
</audio><hr>

パンダだ

あぁ　行こう

わぁ～！　かわいい

ねっ？

うん

<audio controls>
<source src="audio/26/013.mp3">
</audio><hr>

ねね　次はどこ行こっか

ほら！　仲直りした

常勤パンダさん　すご～い

<audio controls>
<source src="audio/26/014.mp3">
</audio><hr>

そうかな？

さすがは　ラテン系だね

また　そんなキャラ付けする…

<audio controls>
<source src="audio/26/015.mp3">
</audio><hr>

アドバイス　お願いします！

ガテン系の常勤パンダさん

<audio controls>
<source src="audio/26/016.mp3">
</audio><hr>

だから　ツッコミづらいって…

<audio controls>
<source src="audio/26/017.mp3">
</audio><hr>

まぁ　アドバイスとしては

一歩前へ出るのが大事だね

<audio controls>
<source src="audio/26/018.mp3">
</audio><hr>

どすこ～い！

全然　恋の予感がしないよ？

<audio controls>
<source src="audio/26/019.mp3">
</audio><hr>

相撲して どうするの

しないの？

しないよ

なんにしても 恋は積極性が大事だね

<audio controls>
<source src="audio/26/020.mp3">
</audio><hr>

説教くせぇか…

今また　変な想像したよね？

積極性だよ？

<audio controls>
<source src="audio/26/021.mp3">
</audio><hr>

お疲れさまでした

お疲れ～

お疲れさま

<audio controls>
<source src="audio/26/022.mp3">
</audio><hr>

でさ…

恋愛経験豊富な常勤パンダさんが

アドバイスくれたんだよ

えっ　

<audio controls>
<source src="audio/26/023.mp3">
</audio><hr>

そうなの？

気になる？

い…　いや…　別に

<audio controls>
<source src="audio/26/024.mp3">
</audio><hr>

じゃあ　やめとく？

えっ！　せ…　せっかくだから 一応聞くよ

<audio controls>
<source src="audio/26/025.mp3">
</audio><hr>

どうしたの？

<audio controls>
<source src="audio/26/026.mp3">
</audio><hr>

でも　こんなものを飾って

笹子さんに見られたら 恥ずかしいな…

もう…　何悩んでるの？

<audio controls>
<source src="audio/26/027.mp3">
</audio><hr>

ほら！　恋は積極性が大事！

前に出る！

パンダくん！

<audio controls>
<source src="audio/26/028.mp3">
</audio><hr>

こんにちは～

いらっしゃい あ　

パンダくん　半田さん

やっほ～

おじゃまします

<audio controls>
<source src="audio/26/029.mp3">
</audio><hr>

いいタイミングだね

何が？

ちょうど 飾りつけが終わるところだよ

これが　最後ね

<audio controls>
<source src="audio/26/030.mp3">
</audio><hr>

僕が作った飾りだ～

じゃあ　一番上に

<audio controls>
<source src="audio/26/031.mp3">
</audio><hr>

今度は願いごとの短冊を つるしますよ～

皆さ～ん　どうぞ

<audio controls>
<source src="audio/26/032.mp3">
</audio><hr>

何　書いたの？

見る？

Stop 地球温暖化

<audio controls>
<source src="audio/26/033.mp3">
</audio><hr>

切実だからね

僕のは　これ！

ペンこさんから告白されますように

<audio controls>
<source src="audio/26/034.mp3">
</audio><hr>

ずうずうしいね

どうしよう　告白されちゃったら！

困っちゃうよ　困っちゃうよ 困っちゃうよ…　

どっちなの？


<audio controls>
<source src="audio/26/035.mp3">
</audio><hr>

半田さん お願い書いてきました？

あ　いや…

えっと…

いや　

<audio controls>
<source src="audio/26/036.mp3">
</audio><hr>

その…

恋は　積極性が大事

<audio controls>
<source src="audio/26/037.mp3">
</audio><hr>

書いてきました

じゃあ　つるしてください

はい

<audio controls>
<source src="audio/26/038.mp3">
</audio><hr>

半田さん　彼女いないんですか？

はい

そうなんですか

早くできるといいですね

<audio controls>
<source src="audio/26/039.mp3">
</audio><hr>

はい

そろそろ締め切り

<audio controls>
<source src="audio/26/040.mp3">
</audio><hr>

パンダくん　願いごとつるした？

<audio controls>
<source src="audio/26/041.mp3">
</audio><hr>

もう　忘れてたの？

う～ん　どうしよう

<audio controls>
<source src="audio/26/042.mp3">
</audio><hr>

えっと　足が長くなりますように

おこづかいアップ

<audio controls>
<source src="audio/26/043.mp3">
</audio><hr>

テレビ出たい…　

パンダくん

まだ？

<audio controls>
<source src="audio/26/044.mp3">
</audio><hr>

飾るよ

<audio controls>
<source src="audio/26/045.mp3">
</audio><hr>

きれい

<audio controls>
<source src="audio/26/046.mp3">
</audio><hr>

涼しいですね

<audio controls>
<source src="audio/26/047.mp3">
</audio><hr>

七夕　晴れてよかったですね

はい

<audio controls>
<source src="audio/26/048.mp3">
</audio><hr>


