---
title: "パンダくん　張り切る"
---

パンダくん　張り切る

<audio controls>
<source src="audio/09/001.mp3">
</audio><hr>

どうしたの？　パンダくん

元気ないですね

実はさ…　常勤パンダさんが

親戚の結婚式で　しばらく 実家の中国に帰るんだって

<audio controls>
<source src="audio/09/002.mp3">
</audio><hr>

なんで　それで 元気ないの？

それがね…(′；ω；｀)

１週間留守にするからって

代わりにバイト　フルに 入ることになっちゃったんだよ

<audio controls>
<source src="audio/09/003.mp3">
</audio><hr>

動物園のバイト？

そう

でも　たった１週間でしょ？

１週間も　だよ～

<audio controls>
<source src="audio/09/004.mp3">
</audio><hr>

早起きできるかな…　しかも毎日

自信がないよ

大変なのは早起きじゃなくて 満員電車じゃない？

<audio controls>
<source src="audio/09/006.mp3">
</audio><hr>

満員電車？

朝　会社に行く人たちで電車がいっぱいになるのが

満員電車だよ

<audio controls>
<source src="audio/09/007.mp3">
</audio><hr>

僕ら　コウテイペンギンは 慣れてるからいいけど…

え？　ペンギンさんも電車　乗るの？

<audio controls>
<source src="audio/09/008.mp3">
</audio><hr>

違うよ(-_-;)

南極じゃ　みんな集まって 子育てするから

もう　満員電車並みの混雑だよ

<audio controls>
<source src="audio/09/009.mp3">
</audio><hr>

みんな おしくらまんじゅう状態だもんね

おしくらまんじゅう？

<audio controls>
<source src="audio/09/010.mp3">
</audio><hr>

楽しそうだね(#^.^#)

なんだか　楽しみになってきたよ

早く帰って　明日に備えなくちゃ

じゃあ…　ごちそうさま

<audio controls>
<source src="audio/09/011.mp3">
</audio><hr>

大丈夫かな…

<audio controls>
<source src="audio/09/012.mp3">
</audio><hr>

あ…　早く　早く

急がないと 満員電車に乗れないよ

<audio controls>
<source src="audio/09/013.mp3">
</audio><hr>

おはよう　パンダくん

おはようございま～す

バイト？　頑張ってね～

<audio controls>
<source src="audio/09/014.mp3">
</audio><hr>

行ってきま～す

すみませ～ん

いらっしゃいませ

お花　選んでいただけますか？

<audio controls>
<source src="audio/09/015.mp3">
</audio><hr>

おしくらまんじゅうだね～

<audio controls>
<source src="audio/09/016.mp3">
</audio><hr>

ドアが閉まります ご注意ください　ドアが閉まります

<audio controls>
<source src="audio/09/017.mp3">
</audio><hr>

すみません パンダ専用車両はどこですか？

ないと思います…

<audio controls>
<source src="audio/09/018.mp3">
</audio><hr>

ど…　どこか… 空いてるところは…

<audio controls>
<source src="audio/09/019.mp3">
</audio><hr>

きついよ…

この先　揺れますので ご注意ください

<audio controls>
<source src="audio/09/020.mp3">
</audio><hr>

パンダく～ん

ごはんだよ？

そこ　置いといて

<audio controls>
<source src="audio/09/021.mp3">
</audio><hr>


うん…

朝からバイトで大変なのは わかるけどさ

もう少し　お客さんにサービスしてよ

<audio controls>
<source src="audio/09/022.mp3">
</audio><hr>


もう　満員電車やだ…

半田さん　朝代わってよ

やだって言ったって 仕方ないでしょう？

<audio controls>
<source src="audio/09/023.mp3">
</audio><hr>


僕　もう少し遅く来るから 朝だけパンダ代わって

<audio controls>
<source src="audio/09/024.mp3">
</audio><hr>

代われって言われても　無理だし

大丈夫　体型似てるから

<audio controls>
<source src="audio/09/025.mp3">
</audio><hr>

いやいや…

ありえないから 頑張ってよ　約束でしょ

ごはん　ここ置いとくからね

<audio controls>
<source src="audio/09/026.mp3">
</audio><hr>

チェッ

あ～　満員電車のこと考えると

食欲が出ないよ

<audio controls>
<source src="audio/09/027.mp3">
</audio><hr>

パンダくん

パンダくんにお届け物です

花？

<audio controls>
<source src="audio/09/028.mp3">
</audio><hr>

いつも見てます お仕事頑張ってね

あなたのファンより　リンリン

僕のファン！？

<audio controls>
<source src="audio/09/029.mp3">
</audio><hr>

リンリンちゃん

僕　頑張るよ！

ママ　パンダさん立った！

すごいわね

<audio controls>
<source src="audio/09/030.mp3">
</audio><hr>

リンリンちゃん

いってきます！

<audio controls>
<source src="audio/09/031.mp3">
</audio><hr>

もしかして　リンリンちゃん？

もしもし

<audio controls>
<source src="audio/09/032.mp3">
</audio><hr>

リンリンちゃん　僕　頑張るからね！

<audio controls>
<source src="audio/09/033.mp3">
</audio><hr>

リンリンちゃんが 見ててくれるんだから

<audio controls>
<source src="audio/09/034.mp3">
</audio><hr>

きっと…　あのなかに リンリンちゃんが…

ここんとこ 張り切ってるな　パンダくん

でも　どうして？

<audio controls>
<source src="audio/09/035.mp3">
</audio><hr>

お疲れ様

今日　常勤パンダさん 戻って来たんでしょ？

うん

<audio controls>
<source src="audio/09/036.mp3">
</audio><hr>

お土産もらった

パンダくん１日も 遅刻しなかったんだってね

すごいじゃない

<audio controls>
<source src="audio/09/037.mp3">
</audio><hr>

大切な人が見ててくれるから

それにしても なんかすごく疲れてない？

<audio controls>
<source src="audio/09/038.mp3">
</audio><hr>

なんだか　あちこち ボロボロで汚れてるし

頑張りすぎなんじゃない

ゆっくり 休んだほうがいいと思うよ

<audio controls>
<source src="audio/09/039.mp3">
</audio><hr>

うん あの子に こんな格好見せられないし

あの子？

今日はもう帰るね

あ　忘れてるよ　天津甘栗チョコレート！

<audio controls>
<source src="audio/09/040.mp3">
</audio><hr>

昨日もステキ 今日も頑張ってね

リンリンちゃん　１週間　僕頑張ったよ

<audio controls>
<source src="audio/09/041.mp3">
</audio><hr>

急がなくっちゃ

リンリンちゃん　今日も　僕が 朝からいるって思ってないかな

すれ違いになったら大変

<audio controls>
<source src="audio/09/042.mp3">
</audio><hr>

おはよう　パンダくん

おはようございます

今日から　通常勤務じゃないの？

<audio controls>
<source src="audio/09/043.mp3">
</audio><hr>

えっ？　ああ…　うん…

だよね　ドキッとしちゃったよ

僕が選んだ花　気に入ってくれた？

えっ？　ああ　リンリンちゃんのお花？ 

<audio controls>
<source src="audio/09/044.mp3">
</audio><hr>

大切にしてるよ

あっ　そうだ　ちょっと 見せたいものがあるんだ

待ってて

はい

<audio controls>
<source src="audio/09/045.mp3">
</audio><hr>

今日は　リンリンちゃん　来てないの？

ああ　リンリンって　僕のことね

林厘太郎

<audio controls>
<source src="audio/09/046.mp3">
</audio><hr>

パンダ　大好きなんだ

あっ　パンダくんは その中でも別格だよ

<audio controls>
<source src="audio/09/047.mp3">
</audio><hr>

リンリンズ　ベストショットは　これ

<audio controls>
<source src="audio/09/048.mp3">
</audio><hr>

お気に入りだから 大きくしてみたんだ

パンダくんにもあげるね

<audio controls>
<source src="audio/09/049.mp3">
</audio><hr>

いらない…

これ　返す…

なんで？

ウワーン！

あっ　パンダくん！

<audio controls>
<source src="audio/09/050.mp3">
</audio><hr>
