---
title: "ペンギンにも いろいろあるよ"
---

<span id="episode-title" data-episode="37"> ペンギンにも いろいろあるよ </span> 

<audio></audio><hr>

わかった　先に入ってる

笹子さん　なんって？

海が　きれいだって

<audio></audio><hr>

なんで　海にいるの？

久しぶりに電車に乗ったから　方向間違えたって

<audio></audio><hr>

ペンギンさんも遅いね

また　逃げ回ってるんじゃないの？ ペン子さんズから

<audio></audio><hr>

７人もいるから　名前を覚えるだけで 大変だね

<audio></audio><hr>

お待たせ！

誰？

ペン子さん８号？

やめてよ

この子は僕の甥っ子

<audio></audio><hr>

こんにちは

かわいい！

コウテイペンギンのヒナって 本当に　かわいいよね

<audio></audio><hr>

あら　アンタも来てたの？

げっ！？

ペン子さん８号？

しつこいね

<audio></audio><hr>

ペンギンさんのお友達？

まあ　失礼な！！

コウテイペンギンなんかと 仲間にしないでよ！

それはこっちのセリフだよ！

えっ？

<audio></audio><hr>

どっちも コウテイペンギンさんじゃないの？

違うよ！ 違うわよ！

僕が　正真正銘のコウテイペンギン！

私が　正真正銘のキングペンギン！

<audio></audio><hr>

こんな図体がでかいだけのヤツと 一緒にしないでちょうだい！

イタッ！　こっちこそ 一緒にされたくないね

<audio></audio><hr>

ド派手なオレンジ色の キングペンギンなんかと

ド派手じゃなくて　エレガント！！

イタッ！

<audio></audio><hr>

なんか　仲　悪いね

僕らは　平和主義なのに

キングペンギンたちが　やたらと ケンカを売ってくるから

<audio></audio><hr>

原因はアンタたちでしょ

コウテイペンギンのせいで　私たちはいっつも大迷惑しているんだから

<audio></audio><hr>

大迷惑？

そうよ　例えば…

動物園じゃ　キングペンギンのほうが 大活躍しているのに

<audio></audio><hr>

人間たちは 平気で間違うのよ！

ハア…　大迷惑よ

<audio></audio><hr>

ペンギンにも　いろいろあるんだね

まあ　大人同士は 多少　似てるかもしれないけど

キングペンギンのヒナときたら

まるで 汚れたモップみたいなんだから

まあ　

<audio></audio><hr>

失礼ね！！

イタッ！　乱暴しないでよ！！

あれ？　その子は？

<audio></audio><hr>

家の息子よ かわいいでしょ？

かわいいというより…

<audio></audio><hr>

ちょっと　怖いかも

失礼ね！　こういうのが ブスかわいいっていうのよ！！

<audio></audio><hr>

ぼ…　僕… モップとか言って　ごめんね

<audio></audio><hr>

フワフワ…

モコモコ…

フワフワ…

モコモコ…

<audio></audio><hr>

こっちは 仲よくなってるよ

そっちも仲よくしたら？

ま…　まあ 僕は　もともと　平和主義だし…

<audio></audio><hr>

しかたないわね 特別に停戦してあげるわ

よかった

南極平和条約　締結だね

<audio></audio><hr>

おっ　コウテイペンギンだぞ

本当だ！

<audio></audio><hr>

うわぁ～！

プール！　プール！

僕でも余裕の広さだね

<audio></audio><hr>

最近　飲みすぎで　メタボ気味だから

今日は　いっぱい泳ごう

あっ　ペンギンさん　発見！

ペンギンさん　ひどい！ どうして私を誘ってくれないの？

<audio></audio><hr>

さて　ここで問題です

ペンジョリーナさんは 右から何番目でしょう？

それ　難しいね

<audio></audio><hr>

どうして　ここに？

けさ　スマホで つぶやいてたでしょ？

甥っ子をよろしく！

あっ　逃げた！

あ～～～

待ってーー

ペンギンさん　今日は　いっぱい 泳げそうだね

ペンギンさん～～

<audio></audio><hr>

私が　ペン子

私が　ペン美

私が　ペン乃

私が　ペン花

私が　ペン奈

私が　ペンニュエル

私が　ペンジョリーナ

私が…

<audio></audio><hr>

あれ剥製じゃないよね？

話かけようか？

やばいよ！目玉　つつかれるぞ！

<audio></audio><hr>

パンダくん　せっかく プールに来たんだから　泳ごうよ

泳ごうよ！

<audio></audio><hr>

えぇ～？ 僕　涼みに来たんだもん

食っちゃ寝してたら太るよ

太るよ

<audio></audio><hr>

いいも～ん

運動　嫌いだもん

シロクマさん！ 一緒に遊びましょう！

<audio></audio><hr>

いいよ

わぁ　やった！

少しは運動しなよ

はぁ～　極楽　極楽

<audio></audio><hr>

あっ　コウテイペンギンだ！

違うわよ　私は　キングペンギンよ！

あっ　コウテイペンギンだろ？

イテテテ！

もう！　人間たちって　どうして 私たちを間違うのかしらね

なんで　キングとコウテイなの？

<audio></audio><hr>

あんまり言いたくないけど…

昔むかし

人間が　まだ 南極へ行けなかった頃のことよ

<audio></audio><hr>

でかっ！ なんて　でかいペンギンなんだ！

最大のペンギン　まさに王様　キングペンギンと名づけよう

<audio></audio><hr>

当時　人が見たことのある 一番大きなペンギンはあたしたちだったの

へぇ～　かっこいい　それで？

<audio></audio><hr>

その後　人間が南極大陸へ 行けるようになって

そこには　ヤツらがいたのよ！

<audio></audio><hr>

あっ　でかっ！　隊長！ キングペンギンより　でかいっすよ！

名前どうしましょう？

あぁ…　それじゃあ　もう 王様の上の皇帝ってことで

コウテイペンギンにしちゃえ

えっ！？　

<audio></audio><hr>

そんなに簡単に？

そうよ！

適当なネーミングをしたのは 人間なのに

その人間に コウテイと間違われるなんて…

悔しいわ！

<audio></audio><hr>

そんなの気にしなくても 大丈夫だよ

ほら　人生　山あり谷ありって 言うじゃない？

<audio></audio><hr>

山には　竹あり

お腹が空いたら　竹あり笹あり

ピシッ！　ムカつく！

なんか　アンタ　ムカつくのよ！

ピシッ　ピシッ…

あっ　あぁ…　やめて！

<audio></audio><hr>

あっ　パンダくん！

なんか運動してる！

楽しそう！

<audio></audio><hr>

ひぃ～　だぁ～！

待って！

あっ　ペンギンさん！

ペンギンさんも運動してる！

楽しそう！

私が…

<audio></audio><hr>

人気ナンバーワンのパンダに 私の気持なんか　わかんないわ！

こんにちは！

<audio></audio><hr>

また　ペンギン？

南極の恋人 アデリーペンギンです

渋めで地味め アゴヒモペンギンです

オシャレな性格美人 ジェンツーペンギンです

<audio></audio><hr>

３羽合わせて　ピゴセリス属！

決まったね

決まった

<audio></audio><hr>

ピ…　ピゴ？

ピゴセリス！

アンタたちの属性は呼びにくいのよ

お久しぶりです　キングペンギンさん

<audio></audio><hr>

キングペンギンさんのアプテノディテス属のほうが 呼びにくいです

同じく　アプテノディテス属の コウテイペンギンさんとは仲よくしてますか？

<audio></audio><hr>

フン！　アイツのまぎらわしい名前で 迷惑しているわ

それを言うなら 僕らの名前も適当なもんです

<audio></audio><hr>

そうなの？

僕ら　アデリーペンギンなんて　探検家の奥さんの名前なんです

だから　オスでも　アデリーちゃん

<audio></audio><hr>

私たちは アゴヒモをしてることにされて

アゴヒモペンギンに…

<audio></audio><hr>

僕ら　ジェンツーペンギンなんか

頭の白い模様が ターバンに似てるから

ポルトガル語で　異教徒を意味する ジェンツーだなんて！

<audio></audio><hr>

本当に適当だね

アンタたちも　いろいろ　あんのね…

どうです？　パンダくん！

僕たちのこと 覚えてくれました？

<audio></audio><hr>

えっ？

助けて！

ペンギンさん！

助けて！

ペンギン！

助けて！

ペンギン！！

<audio></audio><hr>

覚えてくれました？

ピ…　ピ…

なかなか　覚えられませんよね

しかも　ペンギンは 全部で　１８種類もいるんですよ！

えっ！？

<audio></audio><hr>

でも　大丈夫！

そこで　この…　ペンギンカード！

遊びながら　楽しく覚えられて…

今なら　特別価格の５００円！

何　営業してんのよ！？

<audio></audio><hr>

電車って難しい…

特別快速とか　通勤急行とか いろいろ　ありすぎ

バスみたいに　ボタン押したら 止まってくれればいいのに

<audio></audio><hr>

なんで　コウテイが最強カードなのよ！？

知らないよ…

シロクマさん！　ほいっと

こっち　こっち！

<audio></audio><hr>

泳ごっと！

<audio></audio><hr>



