---
title: "メイメイの王子様"
---

<span id="episode-title" data-episode="42"> メイメイの王子様 </span> 

<audio></audio><hr>

ねぇねぇ お兄ちゃん

何？ メイメイ

私 昨日 お兄ちゃんが バイトしてる動物園へ遊びにいったのね

<audio></audio><hr>

そしたら…

すごい かっこいい人 見つけちゃったの！

えっ？ 動物園の人？

お兄ちゃん 知らない？

<audio></audio><hr>

かっこいい人なんていたかな？

パンダコーナーの近くで見たの

あっ… 桐野くん？

<audio></audio><hr>

あの人は まあまあ かっこいいよね

桐野さんっていうの…

この人でしょ？

<audio></audio><hr>

あら 違うわ もっと かっこよかったもん

あっ！

もしかして リンリン？

<audio></audio><hr>

アイツは ダメ ダメ ロクなヤツじゃないよ

リンリンなら知ってるもん 花屋の人でしょ？

違うもん

え～っ

<audio></audio><hr>

もう わかんないよ

私に優しく声をかけてくれて 竹をくれたのよ

もう ドキドキしちゃって…

それって まさか…

<audio></audio><hr>

この人？

キャーッ！！ この人！！

かっこいい！ 王子！！

お… 王子？ 半田さんが？

半田さんっていうの？ ステキ…

半田さんに伝えておこうか？

<audio></audio><hr>

妹が 王子って呼んでましたって

えっ！？

えぇ 別に彼女になりたいとか思ってるわけじゃないの

<audio></audio><hr>

心の中で思ってるだけでいいの

それだけで胸がいっぱいなの

そうなの？

こんなに かっこいいんだもん

すごくモテるでしょ？

<audio></audio><hr>

それ 半田さんの話だよね？

当たり前でしょ！

かっこよくて すごくモテる王子様が他に どこにいるのよ！

<audio></audio><hr>

ねぇねぇ 半様ってどういう人？

何が好きなのかな？

半様？

<audio></audio><hr>

聞きたいことメモして渡すから 聞いてきてよ お兄ちゃん

えっ？

<audio></audio><hr>

半田さん 半田さん！

何？ パンダくん

ただいま

<audio></audio><hr>

あっ お兄ちゃん！

聞いてきてくれた？

まず好きな食べ物だけど…

うん

玉子焼きのはじっこだって

<audio></audio><hr>

グルメね！ 半様ステキ！

それから？

えっと 趣味ってほどでもないけど ツルツルした小石集めが好きって

<audio></audio><hr>

大人の趣味ね

半様 かっこいい！

かっこいい？

それでそれで？

<audio></audio><hr>

お休みの日の過ごし方は

洗濯したり 掃除したり…

たまったスーパーの袋をきちんと三角に折ったりだって

<audio></audio><hr>

家庭的ね！

半様 ステキ！

知れば知るほど半様って最高ね！

<audio></audio><hr>

メイメイ 笹でも食べて落ち着いたら？

お兄ちゃん わかってないわね

あっ！ 半様の写真 撮ってきてない？

えっ… 

<audio></audio><hr>

撮ってきてないよ

なんで！？

半田さんの写真に興味ないもん

撮ってきて！ 半様のかっこいい写真いっぱい！

<audio></audio><hr>

半田さん 半田さん！

何？ パンダくん

<audio></audio><hr>

うわぁ！

キャー かっこいい！

えぇ！？

どう半田さんを見たら そう思えるの？

この下ぶくれの顔とか

モチッと小太りな体型とか

<audio></audio><hr>

足も短いし

えっ それが？

最高じゃない パンダみたいで！

あぁ！

<audio></audio><hr>

うちの妹が 半様ってパンダみたいだって

んっ？ 半様って誰？

半田さんのことだよ

すごく かっこいいんだって

へぇ モテるんですね 半田さん

<audio></audio><hr>

なんか全然 半田さんに脈ないね

妹は 半様って言ってるのに

<audio></audio><hr>

妹さんと 半田さんの２人が結婚したら

パンダくん 半田さんのお兄さんだね

<audio></audio><hr>

僕が半田さんの お兄さん？

お兄さん 朝食の竹です

お兄さん 昼食の竹です

お兄さん 食後の竹です

お兄さん 真夜中の竹です

<audio></audio><hr>

お腹いっぱいになっちゃうなぁ

何の話？

<audio></audio><hr>

半田さん うちのお母さんと うまくやっていけるかな？

<audio></audio><hr>

お母さん どうも 半田です

竹おかわり

わぁ～ 吸わないで～！

<audio></audio><hr>

婿と姑の関係は 難しいっていうしね

あれ？ 半田さんだ

<audio></audio><hr>

この部屋に 決めちゃおうかしら？

僕も ここがいいと思うよ

新婚さんには お似合いの物件だと思いますよ

えっ！？ や… やだ！ 新婚さんだなんて

<audio></audio><hr>

半田さん… アナグマさんと結婚するの？

あ～ん！

ツルツルだね

<audio></audio><hr>

きれいな三角ね

メイメイには言えないよ…

<audio></audio><hr>

ねぇ ねぇ お兄ちゃん！

今日も半様かっこよかった？

さ… さぁ？ どうかな…

<audio></audio><hr>

え～っ！ すごく楽しみにしてるのに

ほら！今日の半様日記

毎日 つけてるんだよ

そうなんだ…

<audio></audio><hr>

何 書いてるの？

ダメ！中は見ないで

乙女のプライバシーなんだから

見てないのに…

<audio></audio><hr>

私 こっそり動物園に行こうかな

それでね 陰からこっそり見守るの

<audio></audio><hr>

あっ！

あ～ん！

いい天気ね

一緒に帰ろうか

いや…

半田さんの見られたくないところを見ちゃうから

<audio></audio><hr>

見られたくないところ？

とにかく 来ないほうがいいの！

残念…

やっぱり メイメイには言えないよ

<audio></audio><hr>

あっ！ 半田さん

おめでとうございます

えっ？

お似合いですよ

え…

<audio></audio><hr>

職場結婚するんでしょ？ アナグマさんと

えっ！？

パンダくん！

あぁ 半田さん

<audio></audio><hr>

おめでとう

困るよ！

僕が アナグマさんと結婚するだなんて…

そのことだけど 

<audio></audio><hr>

そうなる前にちゃんとひと言 言ってよ

いきなりだと驚くよ

だから なんで そういう話になってるの！？

<audio></audio><hr>

この前 アナグマさんと 新居探しをしてたらしいじゃない

あれは アナグマさんが 新しく 部屋探すから

保証人になってただけです！

えっ？

そうなの？

<audio></audio><hr>

は～い！

どうも こんばんは

半田と申します

パンダくん ぐっすり寝ちゃって 起きなくて

<audio></audio><hr>

よいしょ…

じゃあ 僕はこれで

あっ！あの…

はい？

よ… よかったら お茶でも…

<audio></audio><hr>

ありがとうございます

でも トイレの電球が切れたんで 買って帰らないと

近所のスーパー ９時までなんで

じゃあ失礼します

<audio></audio><hr>

半様って  よく気がつくうえに しっかり者なんだ！

お兄ちゃんは 切れた電球を買って帰るなんて

絶対 できないし！

<audio></audio><hr>

はぁ… あれ？家？

お兄ちゃん 聞いた！？

えっ？ 何？

半様 スーパー ９時までだって！

ステキ！

そう？

あっ！

<audio></audio><hr>

半様 ９時までに スーパーに行く と

それは 書かなくていいんじゃないかな？

<audio></audio><hr>

