---
title: "パンダ君の就職 "
---

パンダ君の就職

<audio controls>
<source src="01/091.mp3">
</audio><hr>

はい、しろくまカフェです




あ　こんにちは　

<audio controls>
<source src="01/092.mp3">
</audio><hr>

先日面接にいった、パンダですよ

ああ　不合格の～

<audio controls>
<source src="01/093.mp3">
</audio><hr>

出前を お願いしたいんです

出前はやってないですが

え？！となりなのに

今忙しいし

<audio controls>
<source src="01/094.mp3">
</audio><hr>


どうすれば出前してくれるの？

<audio controls>
<source src="01/095.mp3">
</audio><hr>

ちょっと

お母さん

またゴロゴロして

<audio controls>
<source src="01/096.mp3">
</audio><hr>

今仕事探してたの

<audio controls>
<source src="01/097.mp3">
</audio><hr>

ねえねえ　家近いんだから、出前してよ

お願い～～～

あああ～～～～　吸わないで～～～

<audio controls>
<source src="01/098.mp3">
</audio><hr>

いらっしゃいませ

こんにちは

<audio controls>
<source src="01/099.mp3">
</audio><hr>

何しますか？

ペンギンさん、何にする？

<audio controls>
<source src="01/100.mp3">
</audio><hr>

そうだね

いつものやつ

うん

いつものやつ

えっ？！

<audio controls>
<source src="01/101.mp3">
</audio><hr>

いつものやつって  言われたんですけど

<audio controls>
<source src="01/102.mp3">
</audio><hr>

任せて

カレーライスです。。。。

<audio controls>
<source src="01/103.mp3">
</audio><hr>

違ったみたいですよ

やっぱりね

ちょっと

<audio controls>
<source src="01/104.mp3">
</audio><hr>

あの、竹か笹はないんですか

ないです

じゃ～アイスコーヒー

<audio controls>
<source src="01/105.mp3">
</audio><hr>

あ、君バイト探してたよね

<audio controls>
<source src="01/106.mp3">
</audio><hr>

こんなのあるよ

マグロ船船員大募集

経験者大歓迎、激しく重労働

どう？

<audio controls>
<source src="01/107.mp3">
</audio><hr>

嫌だよ、僕泳げないし

<audio controls>
<source src="01/108.mp3">
</audio><hr>

こっちのがいいじやない？

動物園  未経験者歓迎

呼び相談におします

<audio controls>
<source src="01/109.mp3">
</audio><hr>

先ずはお電話ください　フリアイ動物園

マグロ船にしなよ

しろくまさん

<audio controls>
<source src="01/110.mp3">
</audio><hr>

動物園か　面白そう

<audio controls>
<source src="01/111.mp3">
</audio><hr>


えっと  週二日の勤務希望ですか？

はい

では、パンダの仕事はどうでしょう？

<audio controls>
<source src="01/112.mp3">
</audio><hr>

常勤パンダさんが一頭いるですが

非常勤でもう一頭募集してるんです

<audio controls>
<source src="01/113.mp3">
</audio><hr>


パンダって　あのパンダですよね

気が進みませんか？

でしたら　月の輪熊とゴリラも募集していますよ

<audio controls>
<source src="01/114.mp3">
</audio><hr>


パンダでいいです

そうですか、では、来週から来てください

<audio controls>
<source src="01/115.mp3">
</audio><hr>


僕、バイト決まったよ

良かったですね

まぐろ船？

違うよ　動物園～

<audio controls>
<source src="01/116.mp3">
</audio><hr>


動物園のバイトって、何やるんですか

えへへ　まだ内緒

なんで照れてんの

<audio controls>
<source src="01/117.mp3">
</audio><hr>


いよいよ今日からバイトか　ドキドキしちゃうなぁ

<audio controls>
<source src="01/118.mp3">
</audio><hr>


改めまして、半田と申します

今日は幼稚園から園児たちが来ます

<audio controls>
<source src="01/119.mp3">
</audio><hr>


少しサービスしてあげてください

はい～～～～～

サービスですね　分かりました

<audio controls>
<source src="01/120.mp3">
</audio><hr>


それ以外の時間はどんな感じで？

自然態でいいです

<audio controls>
<source src="01/121.mp3">
</audio><hr>

ね　しろくま君

パンダ君うまくやってるかなぁ～

きっと大漁だよ、まぐろ船

引っ張るねぇ～

<audio controls>
<source src="01/122.mp3">
</audio><hr>

あっ、カフェモカちょうだい

って、それは  影武者、いいから、そういうの

<audio controls>
<source src="01/123.mp3">
</audio><hr>

え　一週七日も

休みはないんですか？

あたしは常勤パンダですからね

<audio controls>
<source src="01/124.mp3">
</audio><hr>

でも月に二日くらいは休みますよ

非常勤でよかった

ハハハハ　まぁ　今日からよろしくお願いします

<audio controls>
<source src="01/125.mp3">
</audio><hr>

はい～！

あっ　そういえば

どうしました？

半田さんから

自然態でって言われたんです

<audio controls>
<source src="01/126.mp3">
</audio><hr>

こんな感じでしょうか？自然と一体的な？

<audio controls>
<source src="01/127.mp3">
</audio><hr>

多分違うと思う　というか　すごく不自然

まぁ～　難しく考えずに普通にしてれば大丈夫ですよ

あ～～

<audio controls>
<source src="01/128.mp3">
</audio><hr>

パンダさん～～～

はい　皆　パンダさんですよ

あ　園児が来ましたね

さ～　頑張りましょう

はい！

<audio controls>
<source src="01/129.mp3">
</audio><hr>



パンダさんは食べているよ

そうね～

はは～パンダさんは滑り台滑ってるの

そうね～

パンダさんが転がってるよ

そうね～

<audio controls>
<source src="01/130.mp3">
</audio><hr>

これでサービスになってるんですか？

もうちょっとの辛抱ですよ～

あ～　もう一サービスしましょう

は、はい！

<audio controls>
<source src="01/131.mp3">
</audio><hr>

サービス～サービス～～

サービス～サービス～～

皆、次はキリンさんを見ましょう

はい～～～

こっちにしよう

サービス～サービス～～

サービス～サービス～～

サービス～サー～ビス～

<audio controls>
<source src="01/132.mp3">
</audio><hr>

は！爆睡してた！

なんで起こしてくれないんですか、常勤パンダさん、え！

<audio controls>
<source src="01/133.mp3">
</audio><hr>

閉園の時間になりました　またのご来園をお待ちしております

<audio controls>
<source src="01/134.mp3">
</audio><hr>

お疲れ様でした

お先です

<audio controls>
<source src="01/135.mp3">
</audio><hr>

あ～　パンダ君

あれ　皆来てたの

お知り合いなんですか

僕たちも動物園でバイトしてるんですよ

<audio controls>
<source src="01/136.mp3">
</audio><hr>

パンダ君　こっちこっち

今日は園児が可愛かったね

<audio controls>
<source src="01/137.mp3">
</audio><hr>

僕　張り切り過ぎでて  途中で  ばてちゃった

わかります　わかります

<audio controls>
<source src="01/138.mp3">
</audio><hr>

今日は一日真面目に働いたなぁ

そうですね

<audio controls>
<source src="01/139.mp3">
</audio><hr>

すごいやりきった顔だけど　パンダ君途中からずっと寝てたらしいよ

パンダ君の自然態なんだねぇ　きっと

パンダ君って　割りと図々しいよね

<audio controls>
<source src="01/140.mp3">
</audio><hr>

パンダ君　一先何か頼みませんか？

どうしようかな～～～

何にする？

竹！大盛りで

<audio controls>
<source src="01/141.mp3">
</audio><hr>

しろくま君　それは　守宮！

オー　よちよち～

それは　子守！

笹子さんが突っ込みを！

<audio controls>
<source src="01/142.mp3">
</audio><hr>

それは　ハモリ

ね～　早く頂戴～


<audio controls>
<source src="01/143.mp3">
</audio><hr>


