---
title: "みんなのカフェ"
---

みんなのカフェ

<audio>
<source src="audio/03/001.mp3">
</audio><hr>

僕の家の朝は早いです

<audio>
<source src="audio/03/002.mp3">
</audio><hr>

朝起きて一番に　中庭に集まって家族みんなで太極拳をします

<audio>
<source src="audio/03/003.mp3">
</audio><hr>

お爺ちゃんが中国拳法の達人だからです

<audio>
<source src="audio/03/004.mp3">
</audio><hr>

太極拳が終わったら　朝ごはんを食べます

<audio>
<source src="audio/03/005.mp3">
</audio><hr>

いつまで寝てるの

<audio>
<source src="audio/03/006.mp3">
</audio><hr>

今日動物園休みなんだから　寝かせて

<audio>
<source src="audio/03/007.mp3">
</audio><hr>

みんなとっくに起きて太極拳やって　朝ごはん食べてるわよ

<audio>
<source src="audio/03/008.mp3">
</audio><hr>

太極拳でしょう　ベッドの上でやる

<audio>
<source src="audio/03/009.mp3">
</audio><hr>

まったくもう

あ～　す　吸わないで

<audio>
<source src="audio/03/010.mp3">
</audio><hr>

お疲れですか

最近運動不足だから　肩こちゃって

<audio>
<source src="audio/03/011.mp3">
</audio><hr>

笹子さん　ちょっと　肩もんでくれない

<audio>
<source src="audio/03/012.mp3">
</audio><hr>

どうしたの

ちょっと肩が見つからなくて

<audio>
<source src="audio/03/013.mp3">
</audio><hr>

ペンギンさんの肩って　どこにあるんですか

え　ここだよ　わかるでしょう

<audio>
<source src="audio/03/014.mp3">
</audio><hr>

わかりません

じゃ　白熊君　肩揉んでくれる

いいよ

<audio>
<source src="audio/03/015.mp3">
</audio><hr>

刺さってる　刺さってる

<audio>
<source src="audio/03/016.mp3">
</audio><hr>

いらっしゃいませ

いらっしゃい

<audio>
<source src="audio/03/017.mp3">
</audio><hr>

や　パンダ君

ペンギンさん　来てたの

<audio>
<source src="audio/03/018.mp3">
</audio><hr>

動物園のバイト　今日は休み

<audio>
<source src="audio/03/019.mp3">
</audio><hr>

うん　笹子さん　いつもの

はい　竹大盛りね

<audio>
<source src="audio/03/020.mp3">
</audio><hr>

白熊君のお店　今日も人いっぱいだね

コーヒーも食べ物も美味しいよね

<audio>
<source src="audio/03/021.mp3">
</audio><hr>

おしゃれだしね

そうだね

おしゃれな女の子がいっぱいだね

そうだね

<audio>
<source src="audio/03/022.mp3">
</audio><hr>

珍しい動物も来てるよね

そうだね

カフェやってる白熊君って格好よくない

<audio>
<source src="audio/03/023.mp3">
</audio><hr>

そう

まあ　お客でダラダラしてるペンギンさんは

とくには格好よくないね

<audio>
<source src="audio/03/024.mp3">
</audio><hr>

僕と比べるのはやめてくれない

あ　白熊君　カフェモカ頂戴

<audio>
<source src="audio/03/025.mp3">
</audio><hr>

それは卓袱台

それは宿題

それは兄弟

「頂戴～」ね

はい　カフェモカ

<audio>
<source src="audio/03/026.mp3">
</audio><hr>

普通にやってよね

どうぞごゆっくり

<audio>
<source src="audio/03/027.mp3">
</audio><hr>

笹子さん　ちょっと出てくるね

うん　はい　白熊さん　いってらっしゃい

<audio>
<source src="audio/03/028.mp3">
</audio><hr>

そうだ　僕もカフェを開いてみたらどうかな

パンダ君が

パンダカフェ

<audio>
<source src="audio/03/029.mp3">
</audio><hr>

そのまんまだね

どんなカフェにしようかなぁ

<audio>
<source src="audio/03/030.mp3">
</audio><hr>

まったりできる　レトロなカフェがいいな

うん　コンセプトは悪くないね

<audio>
<source src="audio/03/031.mp3">
</audio><hr>

いらっしゃいませ

可愛いな　僕

自分で言わないで

<audio>
<source src="audio/03/032.mp3">
</audio><hr>

それでね

お店に中にね　僕のコレクションも飾ろうかな

パンダ君のコレクションって　パンダグッヅ

そうだよ　可愛いよ

<audio>
<source src="audio/03/033.mp3">
</audio><hr>

何

パンダ推しだね

何か問題ある

いや　いいけど　それから

<audio>
<source src="audio/03/034.mp3">
</audio><hr>

当店のおすすめは日替わり竹ランチです

お品書きはこちらです

<audio>
<source src="audio/03/035.mp3">
</audio><hr>

竹特上

竹上

竹並

若竹煮

竹ずし

竹かまぼこ……

……竹定食　松　竹　梅

<audio>
<source src="audio/03/036.mp3">
</audio><hr>

ちょっと　ちょっと

パンダ君の好物しかおいてないじゃない　そのカフェ

<audio>
<source src="audio/03/037.mp3">
</audio><hr>

僕の好きなものは　皆もきっと好きだよ　

美味しいよ　竹

<audio>
<source src="audio/03/038.mp3">
</audio><hr>

生魚はおいてないの

<audio>
<source src="audio/03/039.mp3">
</audio><hr>

カフェに生魚はおいてないでしょう

カフェに竹なんておいてないでしょう

<audio>
<source src="audio/03/040.mp3">
</audio><hr>

しろくまカフェにはおいてあるよ

頼むのパンダ君だけでしょう

<audio>
<source src="audio/03/041.mp3">
</audio><hr>

僕はやっぱり生魚おいて欲しいね

そう　若竹煮ならあるよ

全然違うジャンルですね

<audio>
<source src="audio/03/042.mp3">
</audio><hr>

だよね

だいたいその竹定食の松　竹　梅って紛らわしいよ

<audio>
<source src="audio/03/043.mp3">
</audio><hr>

そうかな

まあ　竹中心のメニューだと　お客さんはあんまりこないよ

<audio>
<source src="audio/03/044.mp3">
</audio><hr>

え　絶対来るよ

なんでそう思えるの

<audio>
<source src="audio/03/045.mp3">
</audio><hr>

ラマさんはパンダカフェ来てくれるよね

僕竹食べるとお腹痛くなっちゃうんです

<audio>
<source src="audio/03/046.mp3">
</audio><hr>

どうしよう　ペンギンさん

普通の料理も出したら

<audio>
<source src="audio/03/047.mp3">
</audio><hr>

ほら　パスタとかさあ

いいね　竹パスタ

いや　竹忘れよう

<audio>
<source src="audio/03/048.mp3">
</audio><hr>

やってみたいなあ　パンダカフェ

<audio>
<source src="audio/03/049.mp3">
</audio><hr>

悪い予感がするね

いらっしゃい

<audio>
<source src="audio/03/050.mp3">
</audio><hr>

戻してね

はい　竹いっちょう

大盛りもできますよ　どうしますか

戻してね

<audio>
<source src="audio/03/051.mp3">
</audio><hr>

パンダ君じゃダメだね　僕がカフェやるよ

どんなカフェなの

そうだね　ペンギンカフェ

<audio>
<source src="audio/03/052.mp3">
</audio><hr>

そのまんまだね

いやいや　和風のカフェなんだよ

<audio>
<source src="audio/03/053.mp3">
</audio><hr>

メニューは　そうだな

生魚とアルコールが中心から

和風カフェっていうより　お寿司屋さんみたいなメニューだね

<audio>
<source src="audio/03/054.mp3">
</audio><hr>

コンセプトは四季おり売りの新鮮な海の幸を

店主が選んだ　こだわりのお酒でいただけるカフェ

<audio>
<source src="audio/03/055.mp3">
</audio><hr>

それカフェじゃなくて　お寿司屋さんじゃない

違うよ　でね

<audio>
<source src="audio/03/056.mp3">
</audio><hr>

カフェの真ん中には水槽おいてね

水槽の中では魚が泳いでいて

お客さんは自分の選んだ魚を食られるの

<audio>
<source src="audio/03/057.mp3">
</audio><hr>

生け簀があるカフェなんてないよ

カフェっぽさも入れてよ

<audio>
<source src="audio/03/058.mp3">
</audio><hr>

カフェっぽさ　入ってない

ペンギンカフェだよ

<audio>
<source src="audio/03/059.mp3">
</audio><hr>

名前だけでしょう

だったら　コーヒー出したりしたらどうですか

<audio>
<source src="audio/03/060.mp3">
</audio><hr>

でも　市場まで魚の仕入れがあるかな　

そこまで手が回るかな

<audio>
<source src="audio/03/061.mp3">
</audio><hr>

やめちゃえば　カフェ

何言ってるの　やるよ　僕は

<audio>
<source src="audio/03/062.mp3">
</audio><hr>

へ　いらっしゃい

旦那　何しやしょうか

戻してね

<audio>
<source src="audio/03/063.mp3">
</audio><hr>

ラマカフェはどうですか

どんなカフェ

ラマがいるカフェなんですけど

そのまんまだね

<audio>
<source src="audio/03/064.mp3">
</audio><hr>

コーヒー運べるの

バランス次第です

<audio>
<source src="audio/03/065.mp3">
</audio><hr>

コンセプトとしては店内のラマに草をあげたり

毛繕いしたり　自由にかわいがって　いいカフェなんです

<audio>
<source src="audio/03/066.mp3">
</audio><hr>

猫カフェみたいだね

なんだって　毛繕いできるんですよ　すごくないですか

<audio>
<source src="audio/03/067.mp3">
</audio><hr>

そうかな　楽しいのそれ

しかもですね

好きなラマを選んで一緒に外でお散歩できたりするんです

<audio>
<source src="audio/03/068.mp3">
</audio><hr>

じゃ　このラマ

ありがとうございま～～す

<audio>
<source src="audio/03/069.mp3">
</audio><hr>

ちょっと　草食べってかない

少し塩気が足りないね

<audio>
<source src="audio/03/070.mp3">
</audio><hr>

素敵でしょう

楽しいかな　それ

やっぱりパンダカフェが一番だよ

<audio>
<source src="audio/03/071.mp3">
</audio><hr>

ペンギンカフェじゃない

ねえ　白熊君はどう思う

うん　ラマカフェ

<audio>
<source src="audio/03/072.mp3">
</audio><hr>

ほらね

笹子さんは

はい

どのカフェがいいと思う

うん　そうですね

笹子カフェ

<audio>
<source src="audio/03/073.mp3">
</audio><hr>

やっぱりパンダカフェだよね

え　ペンギンカフェでしょう

いえいえ　ラマカフェですよ

<audio>
<source src="audio/03/074.mp3">
</audio><hr>

ちょ　ちょっと　聞いてくださいよ

うん　どんなの

えーと　そうですね

<audio>
<source src="audio/03/075.mp3">
</audio><hr>

パンダっぽい笹子さんがいるんでしょう

え　それじゃパンダカフェと変わらないじゃない

いえいえ　ラマっぽい笹子さんが

<audio>
<source src="audio/03/076.mp3">
</audio><hr>



