---
title: "パンダくんヒマに困る"
---

パンダくんヒマに困る

<audio controls>
<source src="audio/23/001.mp3">
</audio><hr>

どうしたの?パンダくん

バイト行きたくないよ

<audio controls>
<source src="audio/23/002.mp3">
</audio><hr>

梅雨に入ってから お客さんが少なくてさ

ヒマでヒマで超退屈なんだ

<audio controls>
<source src="audio/23/003.mp3">
</audio><hr>

贅沢だな

どうせゴロゴロしてるだけでしょ

ヒマすぎるってつらいんだよ

<audio controls>
<source src="audio/23/004.mp3">
</audio><hr>

それに僕は仕事でゴロゴロしてるの

ただのゴロゴロとは違うんだから

<audio controls>
<source src="audio/23/005.mp3">
</audio><hr>

意味がわからないよ

僕もヒマになってゴロゴロしてみたいね

<audio controls>
<source src="audio/23/006.mp3">
</audio><hr>

ゆっくりオヤツ食べても

１時間しか経ってなかったりするんだよ

<audio controls>
<source src="audio/23/007.mp3">
</audio><hr>

オヤツに１時間ってまるでセレブなマダムだね

<audio controls>
<source src="audio/23/008.mp3">
</audio><hr>

コラ!何してるんですか

だってお客さんいなくて ヒマなんだもん

<audio controls>
<source src="audio/23/009.mp3">
</audio><hr>

もう...ちゃぶ台なんか持ち込んで

いやぁ気づかれないように 持ち込むのが大変で大変で

持ち込んじゃいけません!

<audio controls>
<source src="audio/23/010.mp3">
</audio><hr>

まぁまぁ落ち着いて

健康にいい熊笹茶でも一杯どう?

<audio controls>
<source src="audio/23/011.mp3">
</audio><hr>

えっ?熊笹茶?

熊笹茶に含まれる笹多糖体には

ダイエット効果もあるしね

ホント?

<audio controls>
<source src="audio/23/012.mp3">
</audio><hr>

いや最近メタボ気味でさ

<audio controls>
<source src="audio/23/013.mp3">
</audio><hr>

さっさと片付けなさ～い!

<audio controls>
<source src="audio/23/014.mp3">
</audio><hr>

今何時?

寝てたの?う～んとね

<audio controls>
<source src="audio/23/015.mp3">
</audio><hr>

まだ１０時だね

まだ たったの３０分しか経ってないの?

<audio controls>
<source src="audio/23/016.mp3">
</audio><hr>

夢の中では アイドル歌手としてＣＤデビューして

年末にはヤマアラシさんと年越しカウントダウンライブまでしたのに

<audio controls>
<source src="audio/23/017.mp3">
</audio><hr>

よくそんな都合のいい夢が見られるもんだね

<audio controls>
<source src="audio/23/018.mp3">
</audio><hr>

でヤマアラシって誰?

えっ!?あの国民的アイドルグループを 知らないの?

<audio controls>
<source src="audio/23/019.mp3">
</audio><hr>

一般常識だよ

グサっときた

<audio controls>
<source src="audio/23/020.mp3">
</audio><hr>

パンダくんに一般常識って言われて

今なんかグサっときた

<audio controls>
<source src="audio/23/021.mp3">
</audio><hr>

娘さんが２人もいるんでしょ?

ファンじゃないの?

最近あんまり会話がないしね

<audio controls>
<source src="audio/23/022.mp3">
</audio><hr>

なんか切なくなってきたから

あっち向いてホイでもやろうか

いいよ

<audio controls>
<source src="audio/23/023.mp3">
</audio><hr>

ジャンケンポン!

あっち向いてホイ!

ジャンケンポン!

あっち向いてホイ!

<audio controls>
<source src="audio/23/024.mp3">
</audio><hr>

ジャンケンポン!

あっち向いてホイ!

ホイ!

ホイ!

ホイ!

<audio controls>
<source src="audio/23/025.mp3">
</audio><hr>

もしかして私をバカにしてる?

さっき寝違えてさ

右にしか首が回らなくなっちゃったみたい

<audio controls>
<source src="audio/23/026.mp3">
</audio><hr>

ねぇ何作ってるの?

星銃士ビスマルＡの復刻版だよ

<audio controls>
<source src="audio/23/027.mp3">
</audio><hr>

ふ～ん

ふ～んってうちの奥さんみたいな リアクションしないでよ

<audio controls>
<source src="audio/23/028.mp3">
</audio><hr>

これはね プレミアもので

ネットオークションで落札するのが大変だったんだから

<audio controls>
<source src="audio/23/029.mp3">
</audio><hr>

ふ～ん

だからふ～んはやめて

<audio controls>
<source src="audio/23/030.mp3">
</audio><hr>

常勤パンダさんが モデラーなんて知らなかったよ

プラモは男のロマンだからね

<audio controls>
<source src="audio/23/031.mp3">
</audio><hr>

ねぇ私のコレクション見たい?

えっ!どこにあるの?

<audio controls>
<source src="audio/23/032.mp3">
</audio><hr>

家にもたくさんあるんだけど

狭くなるからって家族に迷惑がられててさ

<audio controls>
<source src="audio/23/033.mp3">
</audio><hr>

娘さんが２人もいるしね

実は...

<audio controls>
<source src="audio/23/034.mp3">
</audio><hr>

えっ!?何?

奥さんのお腹に３人目が...

<audio controls>
<source src="audio/23/035.mp3">
</audio><hr>

４人目も入ってるかもね

やめてよ～

<audio controls>
<source src="audio/23/036.mp3">
</audio><hr>

ヒマだね

<audio controls>
<source src="audio/23/037.mp3">
</audio><hr>

はいしろくまカフェです

シロクマくん?

僕今ヒマだからさ

しりとりやろうよ

<audio controls>
<source src="audio/23/038.mp3">
</audio><hr>

僕はヒマじゃないんだけど

じゃありんご!

合コン

<audio controls>
<source src="audio/23/039.mp3">
</audio><hr>

はいふれあい動物園です

えっ?パンダがいない?

<audio controls>
<source src="audio/23/040.mp3">
</audio><hr>

そう言われましてもね...

パンダだって 休みたいときがありますよ

<audio controls>
<source src="audio/23/041.mp3">
</audio><hr>

すみません! すぐ行かせますので...

<audio controls>
<source src="audio/23/042.mp3">
</audio><hr>

ちゃんと仕事しなさい!

<audio controls>
<source src="audio/23/043.mp3">
</audio><hr>

かわいい!

こっち向いて!

今日のお客さん第１号だからサービスしちゃおう

サービスサービス!

<audio controls>
<source src="audio/23/044.mp3">
</audio><hr>

サービスサービス!

パンダさんが けいれんしてる!

早く飼育員さんに知らせなきゃ!!

<audio controls>
<source src="audio/23/045.mp3">
</audio><hr>

せつないね...

あれやろうか

あれ?

<audio controls>
<source src="audio/23/046.mp3">
</audio><hr>

半田さん 急いでパンダコーナーに来てください

なんだ?これ...

<audio controls>
<source src="audio/23/047.mp3">
</audio><hr>

今度は何やってるんですか?

半田さんマージャンできる?

<audio controls>
<source src="audio/23/048.mp3">
</audio><hr>

できません

大丈夫だよ 僕もルール知らないから

<audio controls>
<source src="audio/23/049.mp3">
</audio><hr>

雨も降ってて お客さんも少ないし

半田さんもどうせヒマでしょ?

<audio controls>
<source src="audio/23/050.mp3">
</audio><hr>

さっさと片づけなさい!

<audio controls>
<source src="audio/23/051.mp3">
</audio><hr>

ありがとうございました

<audio controls>
<source src="audio/23/052.mp3">
</audio><hr>

それでさヒマでヒマですごくつらかったんだ

<audio controls>
<source src="audio/23/053.mp3">
</audio><hr>

まったく共感できないんだけど

今日なんか同じ漫画を３０回も読み返したんだよ

<audio controls>
<source src="audio/23/054.mp3">
</audio><hr>

カフェモカおかわり

シロクマくんいいヒマつぶしの方法ってないかな?

<audio controls>
<source src="audio/23/055.mp3">
</audio><hr>

ヒマつぶし

それはひつまぶし

それはかつおぶし

月が...

それは炭坑節

<audio controls>
<source src="audio/23/056.mp3">
</audio><hr>

シロクマくんって ヒマつぶしに困らなそうだよね

笹子さんは?

<audio controls>
<source src="audio/23/057.mp3">
</audio><hr>

私は目的を決めずに自転車で遠出するとかかな

<audio controls>
<source src="audio/23/058.mp3">
</audio><hr>

あとは地図を眺めて風景を想像しながらの街歩き

<audio controls>
<source src="audio/23/059.mp3">
</audio><hr>

みんなは?

プチプチをひたすら潰します

長い...歴史...小説

<audio controls>
<source src="audio/23/060.mp3">
</audio><hr>

黒ベタのジグソーパズルが難しすぎて時間を忘れられますよ

<audio controls>
<source src="audio/23/061.mp3">
</audio><hr>

みんなうらやましいな

僕なんか１日２０時間は休まないとダメだから

起きてる時間が足りなくて 困って困って...

<audio controls>
<source src="audio/23/062.mp3">
</audio><hr>

僕だって予定表がいっぱいで足りないよ。

ほら!

何?

<audio controls>
<source src="audio/23/063.mp3">
</audio><hr>

ペン子さんって すごい働き者でね

毎日会いにいくのが大変で ヒマなんかないよ

それにね...

<audio controls>
<source src="audio/23/064.mp3">
</audio><hr>

シロクマくん笹をちょうだい

聞いてよ!

<audio controls>
<source src="audio/23/065.mp3">
</audio><hr>

それでさ ペン子さんがサービス券をね...

その話はもう何度も聞いたよ

<audio controls>
<source src="audio/23/066.mp3">
</audio><hr>

まもなく当店は閉店いたします

何やってるの?

一度やってみたくて

<audio controls>
<source src="audio/23/067.mp3">
</audio><hr>

もう閉店か...

しろくまカフェにいると 時間があっという間に過ぎるな

<audio controls>
<source src="audio/23/068.mp3">
</audio><hr>

あっそうだ!

何?

<audio controls>
<source src="audio/23/069.mp3">
</audio><hr>

半田さん 至急パンダコーナーに来てください

<audio controls>
<source src="audio/23/070.mp3">
</audio><hr>

なんですかこれは!

半田さんいつもの

半田さんモーニングセット

<audio controls>
<source src="audio/23/071.mp3">
</audio><hr>

チョコパフェください

僕はミルフィーユ

半田さんココア!

<audio controls>
<source src="audio/23/072.mp3">
</audio><hr>

さっさと片づけなさい!

ここはカフェじゃありませ～ん!

は～ん～だ...

<audio controls>
<source src="audio/23/073.mp3">
</audio><hr>
