---
title: "Shirokuma Cafe 6"
---

目指せ！　ワイルドパンダ

<audio controls>
<source src="06/101.mp3">
</audio><hr>

いらっしゃい

<audio controls>
<source src="06/102.mp3">
</audio><hr>

こんにちは

何してるの　パンダくん

<audio controls>
<source src="06/103.mp3">
</audio><hr>

どうしたの　その格好

悪いヤツな気分になってみたくて

ワルな人って憧れちゃうな

<audio controls>
<source src="06/104.mp3">
</audio><hr>

パンダくん　いつもの？

うん　あ　いや　ストロングコーヒー

えっ　ストロング？　結構　苦いよ

<audio controls>
<source src="06/105.mp3">
</audio><hr>

今日は　ワルの気分だから

はい　ストロング

いただきます

外せば

<audio controls>
<source src="06/106.mp3">
</audio><hr>

ねぇ　ワルのどこに憧れたの？

ほら　僕って優柔不断だから

強気な人が羨ましくって

<audio controls>
<source src="06/107.mp3">
</audio><hr>

それ　ワルとは関係ないでしょ

えっ　そう？

僕に足りないのは ワイルドさだと思うんだ

<audio controls>
<source src="06/108.mp3">
</audio><hr>

ワイルドねぇ…

うわ～　苦っ！

やっぱり…

マイルドなコーヒーね

<audio controls>
<source src="06/109.mp3">
</audio><hr>

いろいろビデオを見て ワイルドなイメージを膨らませてみたの

ビデオ？

うんとね…

<audio controls>
<source src="06/110.mp3">
</audio><hr>


山吹色の お菓子でございます

<audio controls>
<source src="06/111.mp3">
</audio><hr>

越後屋　お主もワルよのう

ノー　ノー！

<audio controls>
<source src="06/112.mp3">
</audio><hr>

微妙に　ズレてない？　それ

イマイチ強気で ワイルドなイメージがつかめなくて

<audio controls>
<source src="06/113.mp3">
</audio><hr>

強気で　ワイルドですか

グリズリーくんとか　そうかも

えっ　誰？　誰？

お店やってるから 夜　行ってみる？

<audio controls>
<source src="06/114.mp3">
</audio><hr>

グリズリーさんのお店って　この辺りなの？

いや　もっと先

<audio controls>
<source src="06/115.mp3">
</audio><hr>

ここを抜けると　すぐそこ

<audio controls>
<source src="06/116.mp3">
</audio><hr>

着いたよ　ここね

<audio controls>
<source src="06/117.mp3">
</audio><hr>

パンダくん　こっち　こっち

<audio controls>
<source src="06/118.mp3">
</audio><hr>

確かに　ワイルドなお店だね

猛獣館って感じ？

<audio controls>
<source src="06/119.mp3">
</audio><hr>

こんばんは　グリズリーくん 

よお　シロクマ 久しぶりじゃねえか

<audio controls>
<source src="06/120.mp3">
</audio><hr>

本当に　ワイルドだ…

相変わらず なまっちろい野郎だぜ　この　シロクマ野郎

<audio controls>
<source src="06/121.mp3">
</audio><hr>

ちょっと焼いてこいよ　日サロで

いや…　行っても たぶん変わらない

今日は　友達を連れてきた

<audio controls>
<source src="06/122.mp3">
</audio><hr>

は…　はじめまして

白いのか　黒いのか はっきりしねえ野郎だな

<audio controls>
<source src="06/123.mp3">
</audio><hr>

パンダだからね

まあ　いいか　座れ

<audio controls>
<source src="06/124.mp3">
</audio><hr>

何にする？

シングルモルト

<audio controls>
<source src="06/125.mp3">
</audio><hr>

おい　パンダ

はい…

お前は？

えっと…　竹　大盛り

悪いな　ヘルシーなものは 置いてないんだ

<audio controls>
<source src="06/126.mp3">
</audio><hr>

じゃ…　じゃあ… アイスコーヒー　お願いします

ソフトドリンクもないね

<audio controls>
<source src="06/127.mp3">
</audio><hr>

じゃあ　笹の入ったパフェを お願いします

ヘルシーなものは ないっつってんだろ！！

<audio controls>
<source src="06/128.mp3">
</audio><hr>

グリズリーくん

しようがねえな

シロクマの友人だ 特別に　コーヒー　いれてやるよ

<audio controls>
<source src="06/129.mp3">
</audio><hr>

ミルクは？

なしで

あっ　いや…　ありで

あっ　やっぱ　なしで

白黒　はっきりしろ！！

<audio controls>
<source src="06/130.mp3">
</audio><hr>

もう…　相変わらず短気だな

まあ　パンダが白黒はっきりしたら

シロクマか ただのクマになっちまうよな

<audio controls>
<source src="06/131.mp3">
</audio><hr>

グリズリーさんって　怖い人だね

そう？

<audio controls>
<source src="06/132.mp3">
</audio><hr>

よう　兄ちゃん

アンタ　丸々と太ってて うまそうだな

<audio controls>
<source src="06/133.mp3">
</audio><hr>

どうやって食べるのがいいかな

丸飲みとか

<audio controls>
<source src="06/134.mp3">
</audio><hr>

ヤシの実とか

バーベキューとか

<audio controls>
<source src="06/135.mp3">
</audio><hr>

もろきゅうとか

活け作りとか

若作りとか

<audio controls>
<source src="06/136.mp3">
</audio><hr>

おい　お前！

あんまり他の客を 怖がらすんじゃねえよ

か…　帰ります！

<audio controls>
<source src="06/137.mp3">
</audio><hr>

おい　パンダ！

悪かったな ほらよ　コーヒーだ

<audio controls>
<source src="06/138.mp3">
</audio><hr>

グリズリーさん　ありがとう！

ねぇ　グリズリーさん

何だ？

<audio controls>
<source src="06/139.mp3">
</audio><hr>

あの写真って グリズリーさんだよね？

うん？　おお　あれか

愛車で　アメリカを 横断したときのやつさ

かっこいい！

<audio controls>
<source src="06/140.mp3">
</audio><hr>

よかったぜ　地平線まで続く道を ぶっ飛ばしてよ

わぁ～　憧れちゃうな

<audio controls>
<source src="06/141.mp3">
</audio><hr>

どうせ　お前らはスローライフとかいって ダラダラ暮らしてやがんだろ？

<audio controls>
<source src="06/142.mp3">
</audio><hr>

ロハスって言ってよ

言い方変えただけだろ

ゆっくりでも そんなに変わらないよ

昔からマイペースだよな　お前は

<audio controls>
<source src="06/143.mp3">
</audio><hr>

人生は　一度きりだぜ

熱く　ぶっ飛ばさなきゃな

<audio controls>
<source src="06/144.mp3">
</audio><hr>

グリズリーさん　すごくかっこいいね

僕　そういうの大好き！

おっ？ シロクマの知り合いにしちゃあ

話のわかるヤツじゃないか

ほら　冷めちまうぞ　飲めよ

うん！

<audio controls>
<source src="06/145.mp3">
</audio><hr>

どうだ？ アイリッシュコーヒーにしてみたんだ

まっ　コーヒーより　ウイスキーのほうが 多かったかもな

えっ？　それは…

<audio controls>
<source src="06/146.mp3">
</audio><hr>

また　ソイツと来いよ

今度は　インスタントじゃないコーヒーを いれてやるから

うん　マイルドで　よろしくね

<audio controls>
<source src="06/147.mp3">
</audio><hr>

あれ？

目が覚めた？

シロクマくん　運んでくれたんだね

うん

ありがとう

<audio controls>
<source src="06/148.mp3">
</audio><hr>

いいよ　別に

それと　もうひとつ　ありがとう

<audio controls>
<source src="06/149.mp3">
</audio><hr>

えっ？

僕　だいぶ　ワイルドってのが わかった気がするよ

そう　それならよかった

<audio controls>
<source src="06/150.mp3">
</audio><hr>

シロクマくん　どう？　これ　

ワイルド？

いやぁ　マイルドかな

じゃあ！

<audio controls>
<source src="06/151.mp3">
</audio><hr>

あれ？　パンダくん　どこ行くの？

ワルは後ろを振り返らない

あっ　そう…

<audio controls>
<source src="06/152.mp3">
</audio><hr>

ペンギンさん　ペンギンさん

どうしたの　パンダ君

ペンギンさんって　どうしてみんなに嫌われてるんだっけ

<audio controls>
<source src="06/153.mp3">
</audio><hr>

そんな事実ないでしょう

人気ものだよ　僕は

どっちでもいいじゃない

次回のしろくまカフェは

<audio controls>
<source src="06/154.mp3">
</audio><hr>

鉛筆書きでお送りします

塗ります

お楽しみに

<audio controls>
<source src="06/155.mp3">
</audio><hr>

