---
title: "みんなのカフェ"
---

みんなのカフェ

<audio controls>
<source src="02/001.mp3">
</audio><hr>

僕の家の朝は早いです

<audio controls>
<source src="02/002.mp3">
</audio><hr>

朝起きて一番に　中庭に集まって家族みんなで太極拳をします

<audio controls>
<source src="02/003.mp3">
</audio><hr>

お爺ちゃんが中国拳法の達人だからです

<audio controls>
<source src="02/004.mp3">
</audio><hr>

太極拳が終わったら　朝ごはんを食べます

<audio controls>
<source src="02/005.mp3">
</audio><hr>

いつまで寝てるの

<audio controls>
<source src="02/006.mp3">
</audio><hr>

今日動物園休みなんだから　寝かせて（　^ω^）

<audio controls>
<source src="02/007.mp3">
</audio><hr>

みんなとっくに起きて太極拳やって　朝ごはん食べてるわよ

<audio controls>
<source src="02/008.mp3">
</audio><hr>

太極拳でしょう　ベッドの上でやる(*￣∇￣)ノ

<audio controls>
<source src="02/009.mp3">
</audio><hr>

まったくもう

あ～　す　吸わないで(⊙﹏⊙)

<audio controls>
<source src="02/010.mp3">
</audio><hr>

お疲れですか

最近運動不足だから　肩こちゃって

<audio controls>
<source src="02/011.mp3">
</audio><hr>

笹子さん　ちょっと　肩もんでくれない

(´･ω･)y--oO○ ｴｰﾄ･･･

<audio controls>
<source src="02/012.mp3">
</audio><hr>

どうしたの

ちょっと肩が見つからなくて

<audio controls>
<source src="02/013.mp3">
</audio><hr>

ペンギンさんの肩って　どこにあるんですか

え　ここだよ　わかるでしょう

<audio controls>
<source src="02/014.mp3">
</audio><hr>

わかりません

じゃ　白熊君　肩揉んでくれる

いいよ

<audio controls>
<source src="02/015.mp3">
</audio><hr>

刺さってる　刺さってるw(ﾟДﾟ)w

<audio controls>
<source src="02/016.mp3">
</audio><hr>

いらっしゃいませ

いらっしゃい

<audio controls>
<source src="02/017.mp3">
</audio><hr>

や　パンダ君

ペンギンさん　来てたの

<audio controls>
<source src="02/018.mp3">
</audio><hr>

動物園のバイト　今日は休み

<audio controls>
<source src="02/019.mp3">
</audio><hr>

うん　笹子さん　いつもの

はい　竹大盛りね

<audio controls>
<source src="02/020.mp3">
</audio><hr>

白熊君のお店　今日も人いっぱいだね

コーヒーも食べ物も美味しいよね

<audio controls>
<source src="02/021.mp3">
</audio><hr>

おしゃれだしね

そうだね

おしゃれな女の子がいっぱいだね

そうだね

<audio controls>
<source src="02/022.mp3">
</audio><hr>

珍しい動物も来てるよね

そうだね

カフェやってる白熊君って格好よくない"o((>ω< ))o"

<audio controls>
<source src="02/023.mp3">
</audio><hr>

そう

まあ　お客でダラダラしてるペンギンさんは

とくには格好よくないね

<audio controls>
<source src="02/024.mp3">
</audio><hr>

僕と比べるのはやめてくれない(*′Д`)

あ　白熊君　カフェモカ頂戴

<audio controls>
<source src="02/025.mp3">
</audio><hr>

それは卓袱台

それは宿題

それは兄弟

「頂戴～」ね

はい　カフェモカ

<audio controls>
<source src="02/026.mp3">
</audio><hr>

普通にやってよね

どうぞごゆっくり

<audio controls>
<source src="02/027.mp3">
</audio><hr>

笹子さん　ちょっと出てくるね

うん　はい　白熊さん　いってらっしゃい

<audio controls>
<source src="02/028.mp3">
</audio><hr>

そうだ　僕もカフェを開いてみたらどうかな

パンダ君が

パンダカフェ

<audio controls>
<source src="02/029.mp3">
</audio><hr>

そのまんまだね

どんなカフェにしようかなぁ

<audio controls>
<source src="02/030.mp3">
</audio><hr>

まったりできる　レトロなカフェがいいな

うん　コンセプトは悪くないね

<audio controls>
<source src="02/031.mp3">
</audio><hr>

いらっしゃいませ

可愛いな　僕＼（≧Д≦）＜

自分で言わないで

<audio controls>
<source src="02/032.mp3">
</audio><hr>

それでね

お店に中にね　僕のコレクションも飾ろうかな

パンダ君のコレクションって　パンダグッヅ

そうだよ　可愛いよ

<audio controls>
<source src="02/033.mp3">
</audio><hr>

何

パンダ推しだね

何か問題ある

いや　いいけど　それから

<audio controls>
<source src="02/034.mp3">
</audio><hr>

当店のおすすめは日替わり竹ランチです

お品書きはこちらです

<audio controls>
<source src="02/035.mp3">
</audio><hr>

竹特上

竹上

竹並

若竹煮

竹ずし

竹かまぼこ……

……竹定食　松　竹　梅

<audio controls>
<source src="02/036.mp3">
</audio><hr>

ちょっと　ちょっと

パンダ君の好物しかおいてないじゃない　そのカフェ

<audio controls>
<source src="02/037.mp3">
</audio><hr>

僕の好きなものは　皆もきっと好きだよ　

美味しいよ　竹o(*￣▽￣*)o

<audio controls>
<source src="02/038.mp3">
</audio><hr>

生魚はおいてないの

<audio controls>
<source src="02/039.mp3">
</audio><hr>

カフェに生魚はおいてないでしょう

カフェに竹なんておいてないでしょう

<audio controls>
<source src="02/040.mp3">
</audio><hr>

しろくまカフェにはおいてあるよ

頼むのパンダ君だけでしょう

<audio controls>
<source src="02/041.mp3">
</audio><hr>

僕はやっぱり生魚おいて欲しいね

そう　若竹煮ならあるよ

全然違うジャンルですね

<audio controls>
<source src="02/042.mp3">
</audio><hr>

だよね

だいたいその竹定食の松　竹　梅って紛らわしいよ

<audio controls>
<source src="02/043.mp3">
</audio><hr>

そうかな

まあ　竹中心のメニューだと　お客さんはあんまりこないよ

<audio controls>
<source src="02/044.mp3">
</audio><hr>

え　絶対来るよ(*￣∇￣)ノ

なんでそう思えるの

<audio controls>
<source src="02/045.mp3">
</audio><hr>

ラマさんはパンダカフェ来てくれるよね

僕竹食べるとお腹痛くなっちゃうんです

<audio controls>
<source src="02/046.mp3">
</audio><hr>

どうしよう　ペンギンさん

普通の料理も出したら

<audio controls>
<source src="02/047.mp3">
</audio><hr>

ほら　パスタとかさあ

いいね　竹パスタ（≧0≦）//

いや　竹忘れよう（′Д`）

<audio controls>
<source src="02/048.mp3">
</audio><hr>

やってみたいなあ　パンダカフェ（～o￣▽￣)～o

<audio controls>
<source src="02/049.mp3">
</audio><hr>

悪い予感がするね  ヽ(´Д`；)ﾉ

いらっしゃい

<audio controls>
<source src="02/050.mp3">
</audio><hr>

戻してね

はい　竹いっちょう

大盛りもできますよ　どうしますか

戻してね

<audio controls>
<source src="02/051.mp3">
</audio><hr>

パンダ君じゃダメだね　僕がカフェやるよ

どんなカフェなの

そうだね　ペンギンカフェ

<audio controls>
<source src="02/052.mp3">
</audio><hr>

そのまんまだね

いやいや　和風のカフェなんだよ

<audio controls>
<source src="02/053.mp3">
</audio><hr>

メニューは　そうだな

生魚とアルコールが中心から

和風カフェっていうより　お寿司屋さんみたいなメニューだね

<audio controls>
<source src="02/054.mp3">
</audio><hr>

コンセプトは四季おり売りの新鮮な海の幸を

店主が選んだ　こだわりのお酒でいただけるカフェ

<audio controls>
<source src="02/055.mp3">
</audio><hr>

それカフェじゃなくて　お寿司屋さんじゃない

違うよ　でね

<audio controls>
<source src="02/056.mp3">
</audio><hr>

カフェの真ん中には水槽おいてね

水槽の中では魚が泳いでいて

お客さんは自分の選んだ魚を食られるの

<audio controls>
<source src="02/057.mp3">
</audio><hr>

生け簀があるカフェなんてないよ

カフェっぽさも入れてよ

<audio controls>
<source src="02/058.mp3">
</audio><hr>

カフェっぽさ　入ってない

ペンギンカフェだよ

<audio controls>
<source src="02/059.mp3">
</audio><hr>

名前だけでしょう

だったら　コーヒー出したりしたらどうですか

<audio controls>
<source src="02/060.mp3">
</audio><hr>

でも　市場まで魚の仕入れがあるかな　

そこまで手が回るかな

<audio controls>
<source src="02/061.mp3">
</audio><hr>

やめちゃえば　カフェ

何言ってるの　やるよ　僕は

<audio controls>
<source src="02/062.mp3">
</audio><hr>

へ　いらっしゃい　o(*≧▽≦)ツ

旦那　何しやしょうか(｀・ω・´)

戻してね／(-_-)＼

<audio controls>
<source src="02/063.mp3">
</audio><hr>

ラマカフェはどうですか

どんなカフェ

ラマがいるカフェなんですけど

そのまんまだね

<audio controls>
<source src="02/064.mp3">
</audio><hr>

コーヒー運べるの

バランス次第です

<audio controls>
<source src="02/065.mp3">
</audio><hr>

コンセプトとしては店内のラマに草をあげたり

毛繕いしたり　自由にかわいがって　いいカフェなんです

<audio controls>
<source src="02/066.mp3">
</audio><hr>

猫カフェみたいだね

なんだって　毛繕いできるんですよ　すごくないですか

<audio controls>
<source src="02/067.mp3">
</audio><hr>

そうかな　楽しいのそれ

しかもですね

好きなラマを選んで一緒に外でお散歩できたりするんです

<audio controls>
<source src="02/068.mp3">
</audio><hr>

じゃ　このラマ

ありがとうございま～～す

<audio controls>
<source src="02/069.mp3">
</audio><hr>

ちょっと　草食べってかない

少し塩気が足りないね

<audio controls>
<source src="02/070.mp3">
</audio><hr>

素敵でしょう

楽しいかな　それ

やっぱりパンダカフェが一番だよ

<audio controls>
<source src="02/071.mp3">
</audio><hr>

ペンギンカフェじゃない

ねえ　白熊君はどう思う

うん　ラマカフェ

<audio controls>
<source src="02/072.mp3">
</audio><hr>

ほらね

笹子さんは

はい

どのカフェがいいと思う

うん　そうですね

笹子カフェ

<audio controls>
<source src="02/073.mp3">
</audio><hr>

やっぱりパンダカフェだよね

え　ペンギンカフェでしょう

いえいえ　ラマカフェですよ

<audio controls>
<source src="02/074.mp3">
</audio><hr>

ちょ　ちょっと　聞いてくださいよ

うん　どんなの

えーと　そうですね

<audio controls>
<source src="02/075.mp3">
</audio><hr>

パンダっぽい笹子さんがいるんでしょう

え　それじゃパンダカフェと変わらないじゃない

いえいえ　ラマっぽい笹子さんが

<audio controls>
<source src="02/076.mp3">
</audio><hr>



