---
title: "パンダの悩み相談室"
---

パンダの悩み相談室

<audio controls>
<source src="audio/24/001.mp3">
</audio><hr>



今日も１日雨ですかね

書けた

読めるけど書けない漢字

<audio controls>
<source src="audio/24/002.mp3">
</audio><hr>

ゆう

うつ

シロクマさんさすがですね

ホント...雨続きで憂鬱ですよね

<audio controls>
<source src="audio/24/003.mp3">
</audio><hr>

もう...

遅刻しないように せっかくケータイ渡してあげたのに

<audio controls>
<source src="audio/24/004.mp3">
</audio><hr>

半田さ～ん

ねぇ半田さ～ん

半田さ～ん遊ぼう!

先輩 あいかわらずモテますね

<audio controls>
<source src="audio/24/005.mp3">
</audio><hr>

動物と子供とお年寄りにはモテるんだ

女性にはさっぱりだけどな

<audio controls>
<source src="audio/24/006.mp3">
</audio><hr>

彼はパンダ飼育員の半田さん

日夜パンダの世話を頑張っています

特技は料理

流行りの弁当男子です

<audio controls>
<source src="audio/24/007.mp3">
</audio><hr>

ちなみに彼女いる歴０年

聞こえてるよ

<audio controls>
<source src="audio/24/008.mp3">
</audio><hr>

彼女いる歴０年

もう!ちゃんと お仕事してください!

<audio controls>
<source src="audio/24/009.mp3">
</audio><hr>

パンダくんは今日も遅刻だし...

何度もモーニングコールしたのに

<audio controls>
<source src="audio/24/010.mp3">
</audio><hr>

半田さんていい人だよね

<audio controls>
<source src="audio/24/011.mp3">
</audio><hr>

パンダのストラップもつけてくれるし

まぁパンダくんはパンダ好きだしね

<audio controls>
<source src="audio/24/012.mp3">
</audio><hr>

じゃなくて ちゃんとお仕事しなさい

<audio controls>
<source src="audio/24/013.mp3">
</audio><hr>

彼女ができない 半田さんのことが

心配で心配で 仕事にならないんだよ

<audio controls>
<source src="audio/24/014.mp3">
</audio><hr>

いいわけしないの!

だって見てよあれ

<audio controls>
<source src="audio/24/015.mp3">
</audio><hr>

お客さんはカップルばかりだよ

そうだね

<audio controls>
<source src="audio/24/016.mp3">
</audio><hr>

相合傘でアツアツだよ

雨の日の動物園は穴場のデートスポットだからね

<audio controls>
<source src="audio/24/017.mp3">
</audio><hr>

彼女もいないのに

まるでデートの達人のようなセリフだね

大きなお世話です!

<audio controls>
<source src="audio/24/018.mp3">
</audio><hr>

デートの特集ばかり読んでないで

ちゃんと仕事しなきゃダメだよ

<audio controls>
<source src="audio/24/019.mp3">
</audio><hr>

そんなの読んでないし

仕事もさぼってないよ

恋人ができれば

仕事に張り合いが出るのに

<audio controls>
<source src="audio/24/020.mp3">
</audio><hr>

僕にとっては

動物園のみんなが恋人みたいなもんさ

<audio controls>
<source src="audio/24/021.mp3">
</audio><hr>

そんな清純派アイドルみたいなセリフは

聞きたくないね

そうだよ 

<audio controls>
<source src="audio/24/022.mp3">
</audio><hr>

私トイレに行きません

なんて  アイドルみたいなセリフは聞きたくないよ

<audio controls>
<source src="audio/24/023.mp3">
</audio><hr>

ホントのアイドルは僕たちのように

ウンチがレモンの香りなんだよ

<audio controls>
<source src="audio/24/024.mp3">
</audio><hr>

パンダくん話がそれてるよ

それに半田さんがいくら動物好きでも

<audio controls>
<source src="audio/24/025.mp3">
</audio><hr>

動物との 結婚生活は難しいと思うよ

何言ってるの?

<audio controls>
<source src="audio/24/026.mp3">
</audio><hr>

いい半田さん

これからバツ２の常勤パンダさんが

恋愛相談してくれるから

<audio controls>
<source src="audio/24/027.mp3">
</audio><hr>

ではお願いします先生

私バツ２じゃないんだけど

<audio controls>
<source src="audio/24/028.mp3">
</audio><hr>

じゃあお願いします

先生じゃなくて愛の狩人

<audio controls>
<source src="audio/24/029.mp3">
</audio><hr>

訂正するのはそこじゃないから

っていうか 変なキャラづけしないで

<audio controls>
<source src="audio/24/030.mp3">
</audio><hr>

ともかく 恋愛相談なんていりません

あんなこと言ってますよ 恋愛番長

<audio controls>
<source src="audio/24/031.mp3">
</audio><hr>

番長もやめて

でも半田さん

一生彼女できなくてもいいの?

<audio controls>
<source src="audio/24/032.mp3">
</audio><hr>

い...一生...

そうなんだよね

<audio controls>
<source src="audio/24/033.mp3">
</audio><hr>

彼女がほしいのはもちろんなんだけど

もう彼女というか お嫁さんがほしい年頃なんだよね

<audio controls>
<source src="audio/24/034.mp3">
</audio><hr>

大丈夫だよ

半田さんいい人だから

パンダくん!

<audio controls>
<source src="audio/24/035.mp3">
</audio><hr>

そしていい人で終わっちゃうタイプだね

ああどうでもいい人

<audio controls>
<source src="audio/24/036.mp3">
</audio><hr>

あごめん

元気出して

半田さんのよさをわかってくれる 女の子がきっといるよ

<audio controls>
<source src="audio/24/037.mp3">
</audio><hr>

そそうかな

いるよ

宇宙に１人くらいは

<audio controls>
<source src="audio/24/038.mp3">
</audio><hr>

宇宙に１人だけ...

１人いれば十分じゃない

<audio controls>
<source src="audio/24/039.mp3">
</audio><hr>

たった１人の運命の人

その人と出会えれば

それだけで幸運でしょ

常勤パンダさん

<audio controls>
<source src="audio/24/040.mp3">
</audio><hr>

だからほら元気出しなよ

僕たちがついてるよ

半田さん

パンダに なぐさめられてていいんすか

<audio controls>
<source src="audio/24/041.mp3">
</audio><hr>

パンダくん ほら もっと食べなよ

もういいよ

じゃあシロクマくん

僕も

<audio controls>
<source src="audio/24/042.mp3">
</audio><hr>

じゃあ...

もういいです

ペンギンさんの買ってくる パンの食べ過ぎで

また太っちゃったよ

<audio controls>
<source src="audio/24/043.mp3">
</audio><hr>

何言ってるの?

もっと食べて

だって...

ほら!

またペン子さんにサービス券をサービスしてもらっちゃったんだ!

<audio controls>
<source src="audio/24/044.mp3">
</audio><hr>

これが握手券だったらもっと嬉しいんだけどな...

ウヒヒヒヒ...

ウヒヒって...

<audio controls>
<source src="audio/24/045.mp3">
</audio><hr>

そんな下品な笑い方してると ペン子さんに嫌われますよ

失礼な!!僕ウヒヒ... なんて笑い方してないよ!

<audio controls>
<source src="audio/24/046.mp3">
</audio><hr>

そうだよ ウヒヒ...なんてしてないよ

だよね?

グヒヒ...だよ

言ってないから...

<audio controls>
<source src="audio/24/047.mp3">
</audio><hr>

先輩この間のコンパの子たちが

また半田さんと 飲みたいって言ってましたよ

<audio controls>
<source src="audio/24/048.mp3">
</audio><hr>

またセッティングしましょうか?

うん...

まあそのうちな

<audio controls>
<source src="audio/24/049.mp3">
</audio><hr>

はいわかりました

じゃあお先に失礼します

ああお疲れさま

<audio controls>
<source src="audio/24/050.mp3">
</audio><hr>

雨ちょっと強いから 気をつけてな

はい先輩もほどほどにして 帰ってくださいね

わかってるよ

<audio controls>
<source src="audio/24/051.mp3">
</audio><hr>

半田さんに借りたケータイ 忘れちゃった

今しろくまカフェにいるから

帰りに届けてくれない?

<audio controls>
<source src="audio/24/052.mp3">
</audio><hr>

もう...パンダくんってば...

<audio controls>
<source src="audio/24/053.mp3">
</audio><hr>

いらっしゃいませ

大変でしたね

カッパお預かりします

ああ...どうも

<audio controls>
<source src="audio/24/054.mp3">
</audio><hr>

はい

今度から忘れないでよ

ありがとう

半田さんって ホントいい人だよね

<audio controls>
<source src="audio/24/055.mp3">
</audio><hr>

もう...

少し休ませてもらっても いいですか?

どうぞ

<audio controls>
<source src="audio/24/056.mp3">
</audio><hr>

でペン子さんがさ...

それさっきも聞いたよ

恋は動物の目を曇らせるんですかね

<audio controls>
<source src="audio/24/057.mp3">
</audio><hr>

いいじゃない聞いてよ

<audio controls>
<source src="audio/24/058.mp3">
</audio><hr>

お目覚めですか?

すみません ついウトウトしちゃって

<audio controls>
<source src="audio/24/059.mp3">
</audio><hr>

お気になさらずに

これ店長からのサービスです

<audio controls>
<source src="audio/24/060.mp3">
</audio><hr>

あったかい

<audio controls>
<source src="audio/24/061.mp3">
</audio><hr>

雨に濡れた緑が鮮やかで

ホントきれいですよね

はい

<audio controls>
<source src="audio/24/062.mp3">
</audio><hr>

