---
title: "ペンギンさんの失恋"
---

ペンギンさんの失恋

<audio controls>
<source src="audio/21/001.mp3">
</audio><hr>

はい

頼んでないよ

新メニューのホットケーキ　味見してみて

<audio controls>
<source src="audio/21/002.mp3">
</audio><hr>

笹が入ってないよ

普通入れないから

<audio controls>
<source src="audio/21/003.mp3">
</audio><hr>

なんか　しょっぱい

シャケ入れてみた

<audio controls>
<source src="audio/21/004.mp3">
</audio><hr>

笹子さんも食べてみてよ

あ…　はい

やっぱり　しょっぱいです

<audio controls>
<source src="audio/21/005.mp3">
</audio><hr>

あれ？ ペンギンさんいつからいたの？

ずっといるでしょ！

<audio controls>
<source src="audio/21/006.mp3">
</audio><hr>

ちゃんと気づいてたよ

でも何か話しかけちゃいけないのかと思って

話しかけてよ！

<audio controls>
<source src="audio/21/007.mp3">
</audio><hr>

シャケ入りホットケーキ　食べる？

<audio controls>
<source src="audio/21/008.mp3">
</audio><hr>

僕は今食欲なんかないの

どうしたんですか？

見てわからない？

<audio controls>
<source src="audio/21/009.mp3">
</audio><hr>

わかんないよ

僕はね…　僕はね…

<audio controls>
<source src="audio/21/010.mp3">
</audio><hr>

失恋したんだよ！

失恋？

<audio controls>
<source src="audio/21/011.mp3">
</audio><hr>

それは　七輪！

それは　一輪車！

それは　三輪車！

<audio controls>
<source src="audio/21/012.mp3">
</audio><hr>

だから　僕は　失恋して ツッコむ気力もないの！

<audio controls>
<source src="audio/21/013.mp3">
</audio><hr>

ツッコんでるじゃない

失恋って　ペン子さん？

決まってるじゃない！

<audio controls>
<source src="audio/21/014.mp3">
</audio><hr>

あ…　あの… なんて言ったらいいか…

何も言わないで　ほっておいてよ

<audio controls>
<source src="audio/21/015.mp3">
</audio><hr>

パンダくん駅前のベーグル屋さんおいしいらしいよ

聞いてよ！

<audio controls>
<source src="audio/21/016.mp3">
</audio><hr>

聞いてほしいんですか？

当たり前じゃない！

話せば楽になるぞ

<audio controls>
<source src="audio/21/017.mp3">
</audio><hr>

刑事さん　実は…

って…　僕は 犯人じゃないから！

で…　どうしたの？

<audio controls>
<source src="audio/21/018.mp3">
</audio><hr>

見ちゃったんだよ

何を？

ペン子さんがデートしてるところ…

<audio controls>
<source src="audio/21/019.mp3">
</audio><hr>

だ…　誰とですか？

それがなんと驚いたことに…

<audio controls>
<source src="audio/21/020.mp3">
</audio><hr>

絶対に　ありえない相手で…

本当に信じられない…

誰なんですか？

まさかと思うくらいの…

<audio controls>
<source src="audio/21/021.mp3">
</audio><hr>

いいから　早く吐け

って…　僕　犯人じゃないから！

さっき　公園で 目撃しちゃったんだ

<audio controls>
<source src="audio/21/022.mp3">
</audio><hr>

ペン子さん！

こんなところで　めぐり会うなんて

運命　感じちゃうな！

<audio controls>
<source src="audio/21/023.mp3">
</audio><hr>

やぁ！　偶然ですねペン…

お待たせ～

じゃあ　行きましょう

<audio controls>
<source src="audio/21/024.mp3">
</audio><hr>

ゾウガメさん？

本当に？

ゾウガメさんが？

そう…　

<audio controls>
<source src="audio/21/025.mp3">
</audio><hr>

ペン子さんと待ち合わせて デートしてたんだ

<audio controls>
<source src="audio/21/026.mp3">
</audio><hr>

ステキなカフェですね

僕…　ここに 甲羅干しに来るんです～

<audio controls>
<source src="audio/21/027.mp3">
</audio><hr>

まぁ！

僕も食べたいな～

はい

<audio controls>
<source src="audio/21/028.mp3">
</audio><hr>

いい天気

だね～

２人で楽しそうにお茶飲んだり

あ～んってしたり ボートに乗ってたんだよ！

<audio controls>
<source src="audio/21/029.mp3">
</audio><hr>

それ　どこで聞いてたの？

そりゃ…

<audio controls>
<source src="audio/21/030.mp3">
</audio><hr>

なんだか涙ぐましいね

<audio controls>
<source src="audio/21/031.mp3">
</audio><hr>

でも　それだけじゃ

恋人同士かどうかわかんないんじゃない？

それが　決定的なことに…

<audio controls>
<source src="audio/21/032.mp3">
</audio><hr>

私…　大好きなんですよね

カ　メ…

<audio controls>
<source src="audio/21/033.mp3">
</audio><hr>

そんな～っ！

知らなかった…　ペン子さん カメが大好きだったなんて…

カメのどこがいいんだろう？

<audio controls>
<source src="audio/21/034.mp3">
</audio><hr>

ねぇどこがいいんだと思う？

はっきり言ってよ！

こ…　

<audio controls>
<source src="audio/21/035.mp3">
</audio><hr>

甲羅があるとこですかね？

首とか手足が引っ込むところも キュートかも

<audio controls>
<source src="audio/21/036.mp3">
</audio><hr>

千年生きるのはすごいよね

ペ…　ペンギンにだって いいとこあるでしょ？

<audio controls>
<source src="audio/21/037.mp3">
</audio><hr>

ないの！？

負けてる…　完璧に負けてるよ

僕はどうして ペンギンに生まれたんだろう

<audio controls>
<source src="audio/21/038.mp3">
</audio><hr>

お母さん！　どうして　僕を カメに生んでくれなかったの！？

<audio controls>
<source src="audio/21/039.mp3">
</audio><hr>

ペンギンさん　あのね

ペンギンからカメは生まれないんだよ

わかってるよ！

あ～あ… こんなことなら思い切って

ペン子さんを ドライブに誘っとくんだった

い…　

<audio controls>
<source src="audio/21/040.mp3">
</audio><hr>

今からでも遅くないですよ

<audio controls>
<source src="audio/21/041.mp3">
</audio><hr>

せっかく免許も取ったんだし…

そ…　そうだよね！

ペン子さんカメ好きなら

速い乗り物は 好きじゃないかもね

<audio controls>
<source src="audio/21/042.mp3">
</audio><hr>

ゆっくりじゃないとダメなのか～！

やっぱ　ダメだ…

もう　きっぱり ペン子さんのことは諦めよう

<audio controls>
<source src="audio/21/043.mp3">
</audio><hr>

そうですね

また　ステキな子が現れるよ

そうだよね　いつまでも 引きずってちゃダメだよね

<audio controls>
<source src="audio/21/044.mp3">
</audio><hr>

そうですよ

やっぱ　諦めちゃダメでしょ！

どっちなの？

<audio controls>
<source src="audio/21/045.mp3">
</audio><hr>

でも　ペン子さんには　ゾウガメさんが…

ペンギンがゾウガメなんかに 負けてたまるか～っ！

<audio controls>
<source src="audio/21/046.mp3">
</audio><hr>

あっ　ゾウガメさん

こんにちは～

ライバル登場だよ

<audio controls>
<source src="audio/21/047.mp3">
</audio><hr>

ペン子さんの彼氏　来た

ダメだよ　そんなこと言っちゃ

これから決闘するの？

<audio controls>
<source src="audio/21/048.mp3">
</audio><hr>

しないよ

えっと　こういうのたしか…

シャバダバ？

修羅場だよ

ちょっと黙っててよ！

<audio controls>
<source src="audio/21/049.mp3">
</audio><hr>

とにかく　ペン子さんと どういうおつきあいなのか

はっきりさせないと

<audio controls>
<source src="audio/21/050.mp3">
</audio><hr>

ゾ…　ゾウガメ君！

なに～？

あ…　いや…

いい天気だね

<audio controls>
<source src="audio/21/051.mp3">
</audio><hr>

ペンギンさん　はっきりさせるんじゃ なかったの？

わかってるよ！

<audio controls>
<source src="audio/21/052.mp3">
</audio><hr>

どうかした～？

あ…　いや…　あのさ！ この間さ　公園で…

<audio controls>
<source src="audio/21/053.mp3">
</audio><hr>

すごくおいしいマイワシを 食べたんだよね～

おいしかった～

<audio controls>
<source src="audio/21/054.mp3">
</audio><hr>

違うでしょ？

わかってるよ！

話には順序ってものが…

<audio controls>
<source src="audio/21/055.mp3">
</audio><hr>

そういえば　あの公園でさ

<audio controls>
<source src="audio/21/056.mp3">
</audio><hr>

女の子のペンギンと 一緒にいたじゃない？

あの公園　気持いいよね

<audio controls>
<source src="audio/21/057.mp3">
</audio><hr>

で　ゾウガメさんとペン子さんは どういう関係？

あからさまに聞かないでよ！

それで　

<audio controls>
<source src="audio/21/058.mp3">
</audio><hr>

ゾウガメさんは どうして一緒に？

笹子さんまで！？

なんで　公園に一緒にいたの？

誘われて～

<audio controls>
<source src="audio/21/059.mp3">
</audio><hr>

ペン子さんに　誘われた！？

好きだって～

カ…　メ…

<audio controls>
<source src="audio/21/060.mp3">
</audio><hr>

ゾウガメさん　ペン子さんとお幸せに！ うわ～ん！

<audio controls>
<source src="audio/21/061.mp3">
</audio><hr>

ラ…

ラ？

<audio controls>
<source src="audio/21/062.mp3">
</audio><hr>

いや待てよ

ペン子さんが そんなにカメ好きなら…

<audio controls>
<source src="audio/21/063.mp3">
</audio><hr>

いらっしゃい

<audio controls>
<source src="audio/21/064.mp3">
</audio><hr>

こんにちは

<audio controls>
<source src="audio/21/065.mp3">
</audio><hr>

何やってるの　ペンギンさん

どこから持ってきたんですか？ その甲羅

<audio controls>
<source src="audio/21/066.mp3">
</audio><hr>

かたい

ペン子さんはカメが大好き

ああ　

<audio controls>
<source src="audio/21/067.mp3">
</audio><hr>

ペン子さんはね

カメじゃなくて

大好きなのは　カメラ

<audio controls>
<source src="audio/21/068.mp3">
</audio><hr>

最近　カメラが趣味らしいよ

ゾウガメさんも同じ趣味みたいで

<audio controls>
<source src="audio/21/069.mp3">
</audio><hr>

大好きなのはね　カメじゃなくてカメラだよ

<audio controls>
<source src="audio/21/070.mp3">
</audio><hr>

出直してきます

<audio controls>
<source src="audio/21/071.mp3">
</audio><hr>

