---
title: "バイセンって　ナンダ！？"
---

<span id="episode-title" data-episode="38"> バイセンって　ナンダ！？ </span> 

<audio></audio><hr>

うま～！

しろくまカフェのパフェって マジ　最高！

<audio></audio><hr>

あれ？　ペンギンさんじゃない

あ…　どうも　俺…

人間くんだよ

シロクマさん… 間違ってはないんすけど

マサキくんだよ

<audio></audio><hr>

パンダくんは　いつものでいい？

うん　コーヒー 今日は　ブラックにする

パンダさん　コーヒーっすか？

渋いっすね

違いのわかるパンダって呼んで

<audio></audio><hr>

ブラックって　苦くて おいしくなくないっすか？

おいしくなくなくないよ

<audio></audio><hr>

違いのわかるパンダだから

え～っ！　でも　苦いんでしょ？

飲んでみる？

しろくまカフェのは　おいしいよ

<audio></audio><hr>

ホントにおいしいじゃん！

そうでしょう？

めっちゃいい香りだし

こんなコーヒー淹れられるなんて すげぇっすね！

<audio></audio><hr>

おいしさの秘密は 焙煎にあるんだよ

バイセン？　それ何？

<audio></audio><hr>

それ　海鮮だし！

それ　対戦だし！

それ　ゲーセンだし！

バイセンってなんだよ！

<audio></audio><hr>

焙煎って コーヒー豆を煎ることですよ

豆を煎る？

うちは　達人が焙煎した豆を 仕入れてるから

達人？

<audio></audio><hr>

へぇ～　知らなかった

会ってみてぇ！

連れていってあげてもいいよ

マジっすか？

<audio></audio><hr>

ちょっと　遠いよ？

え…　外国っすか？ ブラジル？　コロンビア？

<audio></audio><hr>

着いた　着いた

シロクマさん…

何？

めっちゃ　近いじゃないっすか！

うん　だから ちょっとだけ遠い

<audio></audio><hr>

こんにちは

あら　シロクマさん！

エゾリスママさん 達人に用があるんだけど…

<audio></audio><hr>

ごめんなさい 今　手が離せないところなのよ

リスが焙煎してんだ

パートのママさんたちだよ

<audio></audio><hr>

あ…　あの人が？

うん　達人のキノボリカンガルーさん

<audio></audio><hr>

よし

なんの用だ？

キノボリカンガルーさん　このマサキくんが…

弟子になりたいです！

えっ！？

僕も弟子になりたいです！

え？

<audio></audio><hr>

やめときなさいよ

焙煎士なんて地味な仕事よ

私たち　パートだけど…

根気がいるし

力仕事だし

じゃあ　やめときます

<audio></audio><hr>

最初から　やる気ないでしょ

うん

俺は　マジっす

今日 しろくまカフェのコーヒーを飲んで

俺　生まれて初めて ブラックがおいしいと思ったんです

<audio></audio><hr>

あんなおいしいコーヒーを 自分でも作ってみたいんです

ムリよ

弟子を置かない主義らしいから

<audio></audio><hr>

いいだろう

えっ！？

ホントですか！？

あぁ

や…　やった～！

まぁ　しばらく 通ってみればいいさ

頑張ります！

<audio></audio><hr>

達人！　今日から お世話になります　マサキです

あぁ　エゾリスたちに教わるといい

はい！

わぁ…　豆が白いっつうか　薄緑？

カビ生えてるの？

イタッ！

これは　コーヒーの生豆よ！

生豆？

<audio></audio><hr>

これを煎るから茶色になるの

なるほど

じゃあ　まず 豆のよりわけ方から教えるわね

はい

<audio></audio><hr>

コーヒーを焙煎する前に 悪い豆を取り除いておくのよ

１粒ずつ？

混ざると味が悪くなるのよ

うわ～　大変っすね

悪い豆っていうのは こういう虫が食ってるやつ

<audio></audio><hr>

腐ってるやつ

そういう豆は見逃さないで 絶対取らないとダメよ

はい

<audio></audio><hr>

あ　大きい豆も取って

何で？大きいのいいじゃん

アタッ！

大きいと火のとおりに ムラが出るでしょ

<audio></audio><hr>

これ全部やるんすか？

そうよ　今日中よ

マジ？

さぁ　急いで

はい

<audio></audio><hr>

遅いわよ

はい

もっと　チャッチャと

はい

<audio></audio><hr>

もっと　リズミカルに

何だよ　もう！

俺は　キノボリカンガルーさんに 弟子入りしたのに

アタッ！

下っ端が口ごたえしない！

口より手を動かす

<audio></audio><hr>

はい

ほら　チャッチャと

マサキ　手が止まってる！

動かしてるよ

<audio></audio><hr>

マサキくん　どうなりましたかね

誰　それ

えっ？

キミが　すすめたブラックコーヒーに 感動したって人でしょ

<audio></audio><hr>

ああ

ああって

僕　ワルだから 過去は　振り返らないの

カフェモカちょうだい

<audio></audio><hr>

ごちそうさま

<audio></audio><hr>

ねぇ　マサキ

腹ごなしに　バレーボールやらない

いいっすよ

<audio></audio><hr>

できた！

これが　ネットね

何気に　本格的っすね

じゃあ　ゲーム開始よ

いきます！

ほい！ センター！

はい！ アタック！

アタッ！

ナイスコース！

イタッ！　よし　本気出すぞ

ヒューヒュー！

<audio></audio><hr>

ねぇ　あれから ペン子さんたちとはどうなったの？

思い出させないでくれる

カフェモカ　おかわり

<audio></audio><hr>

ペンギンさんも たまには　ブラック飲めば？

これ以上 苦い思いはしたくないよ

はい　ブラック　サービスね

<audio></audio><hr>

苦いんでしょ

あっ　キノボリカンガルーさん

ほい　豆

いつも　お疲れさまです

マサキくん　頑張ってる？

ああ　まぁ　

<audio></audio><hr>

エゾリスたちとは 打ち解けたみたいだな

イタッ！

イエーイ　ストレート勝ち！

やったわ！

もういっちょ！

<audio></audio><hr>

あっ　おいしい

でしょ

まろやかで　あと味　スッキリ

すごく平凡な感想だね

えっ！

だな

えっ！

<audio></audio><hr>

グルメレポーター失格だね

ちょっと待って

ペンギンさん　いつから グルメレポーターになったんですか？

今日から

なってないから！

なってないのに レポーター気取りなの？

<audio></audio><hr>



