---
title: "夏のお祭り"
---

<span id="episode-title" data-episode="40"> 夏のお祭り </span> 

<audio></audio><hr>

今日は　しろくまカフェと グリズリーバーのジョイント企画で

屋台をやりま～す！

いいね

楽しみ！

似合ってるね　笹子さん

<audio></audio><hr>

みんなで盛り上げましょう！

は～い！

祭りなら任せろ！

炎上　炎上！

かっこいい！

<audio></audio><hr>

グリズリーくんは 焼そばを作ってね

おう　ガンガン作ってやるぜ

パンダくんは ソースを塗ったりする担当

任せて！

<audio></audio><hr>

ペンギンさんは　呼び込みで

了解！

あの　僕も何か お手伝いしましょうか？

ああ　お久しぶり！

<audio></audio><hr>

パンダくんの知り合い？

うん　お兄さん！

お兄さん？

みたいな

ど…　どういう関係？

<audio></audio><hr>

名前は同じだけど

種属違いの親戚

うん？

もともと　パンダって呼ばれてたのは 僕たちだったんですよ

へぇ～　そうだったんですか

<audio></audio><hr>

でも　ジャイアントパンダくんが 出てきてから

僕たちは 小さいほうのパンダ　レッサーパンダって 呼ばれるようになったんです

へぇ～

<audio></audio><hr>

今も　笹情報まわしたりとか

親戚づきあいは 続いてるんだよね

笹情報って？

はい　どこの笹が おいしいとか調べたり

僕たちも　笹　大好きなんで

こまめに動くタイプなんです

<audio></audio><hr>

へぇ～！

じゃあ　私は　注文や お客さんをさばいたりするから

お勘定係　お願いしてもいいかな？

はい！

<audio></audio><hr>

すげぇ！

これが　いい！

きれい！

そう　そう… これを立てておこう

<audio></audio><hr>

タイムサービス？

どんなサービスするんだ？

増量か？　値引きか？

別に何も

あぁ？

でも　これを見たら

今買わなきゃって思う

正々堂々とやれ！

<audio></audio><hr>

いらっしゃい　いらっしゃい！

シロクマ風お好み焼と グリズリー焼そばだよ

一度　食べたら　忘れられない味

しかも　めったに食べられないよ

<audio></audio><hr>

え～い！　まどろっこしい！！

おりゃ～！　オラ　オラ！！

グリズリー焼そばの激うまさに驚け！

グリズリーくん　勢いよすぎ

<audio></audio><hr>

焼そば　２つ！

お好み焼　１つと　焼そば　１つ！

は～い

焼そば　３つと　お好み焼　１つ

モダン焼　できる？

<audio></audio><hr>

はい　できますよ

パンダくん　早く　お好み焼　お願い！

う…　うん　今…

あっ！　自分に　ソース塗っちゃった

<audio></audio><hr>

パンダ　急げ！

う…　うん

ぐわっ！　何しやがる！？

あっ！　逆だった

<audio></audio><hr>

笹子に代われ！

<audio></audio><hr>

はい　どうぞ

やった～！

よかったわね

ありがとうございました

うりきれ！　店じまいです

お疲れさまでした

ふぅ…　お疲れ！

お疲れさま

あぁ…　疲れた！

働くのって大変

<audio></audio><hr>

パンダくんは 途中で　クビになったでしょ

他の屋台回ってみようよ

おっ！　いいね

わぁ～！　たくさんあるね

僕　これにする

<audio></audio><hr>

パンダ　イン　パンダ！

変だよ　それ…

じゃあ…

パンダ　アンド　パンダ

なんか　怖いよ…

<audio></audio><hr>

あれ　おもしろそう　やってみたい！

また　そんな ご迷惑なことを…

いいよ　やってみるかい？

やる　やる！

<audio></audio><hr>

別の生きものに なっちゃってるよ

う～ん…　ベロが届かないよ！

<audio></audio><hr>

あぁ～！　惜しい…

もう１回　もう１回！

あっ　今…

銃がよくないよ　おじさん　交換して

また　そんなワガママ言って

<audio></audio><hr>

やった！　ねぇ　ほら！

貸してみろ

おらぁっ！

どうだ！

俺にかかりゃ　こんなもんよ

あ… ほらよ

あ…　ありがとうございます

<audio></audio><hr>

おらぁっ！

細かすぎんだよ

コイツら！ サケやマスなら　一発なのによ！

シロクマさん　すご～い

もう２０匹目ですよ

<audio></audio><hr>

さすがだね

いっそのこと　直に…

お客さん　困ります

<audio></audio><hr>

あれ？　半田さん

あっ　パンダくん

仕事終わって 今　来たところなんだ

笹子さん…　あ　いや　屋台は？

うん　完売で もう　みんな遊んでるよ

<audio></audio><hr>

そ…　そう

何？ それ…

笹子さ…　あ　いや！みんなに差し入れをと思って…

お茶とかジュース

笹子さんなら　あっちにいるよ

<audio></audio><hr>

え？　あ～　そう…

渡しにいこうよ

えっ！

みんなじゃなくて ２人で飲めばいいと思うよ

いや　いや…

あれ？　半田さん？

さ…　笹子さん

こんばんは

<audio></audio><hr>

ど…　ど…　どうも

半田さんが 差し入れにきてくれたよ

ど…　どうぞ

あら…　ありがとうございます

いやいや　つまらないものだから

<audio></audio><hr>

ちょっと…　パンダくん

おう　半田 ありがたくもらうぜ

僕も飲む～！

僕ももらおうかな

もう一本！

<audio></audio><hr>

せっかくなんで いただきます

あ…　どうぞ　どうぞ

半田さん…　間が悪いなぁ

<audio></audio><hr>

わぁ… 花火

始まったみたいですね

<audio></audio><hr>

わぁ…　きれい

私　花火　大好きなんですよ

僕も…　僕も大好きです

いいですよね　花火

は…　はい

<audio></audio><hr>

笹子さんは座ってください

あ…　すみません

ダメだよ　半田さん　遠慮してちゃ

でも　これで 一緒に並んで座れたでしょ？

<audio></audio><hr>

あ…　あの…　最後の１本に なっちゃいましたが

お茶　どうぞ

ありがとうございます

すごく　ノドが渇いてたんですよ

冷たくて気持いい

<audio></audio><hr>

きれ～い！

おぉ～！炎上　炎上！

グリズリーくん　それ違うから

きらめいてます！

もう…　みんな 空気読まないんだから

<audio></audio><hr>



