---
title: "キャンプに行こう！"
---

<span id="episode-title" data-episode="33"> キャンプに行こう！ </span> 

<audio></audio><hr>

荷物　多いね

キャンプだからね

<audio></audio><hr>

キャンプ？

それは　チャンプ

それは　スランプ

それは　バグパイプ

それは　ゴーヤチャンプルー

<audio></audio><hr>

僕　キャンプって　したことないんだよ

キャンプっていうのはね…

<audio></audio><hr>

真っ暗な山の中で　ひっそり寂しく 冷たい地べたの上で寝るんだよ

<audio></audio><hr>

ペンギンさん　真っ暗なところで ひっそり寝るのが好きなの？

好きじゃないよ

キャンプっていうのは大自然のなかでおいしいご飯食べて

テント張ってきれいな星空眺めたりするものでしょ！

<audio></audio><hr>

笹か竹があればいいよ

それじゃ いつもと変わらないじゃない…

<audio></audio><hr>

もうすぐ　グリズリーくんも来るよ

えっ？　それ　誰？

草むしりのとき　来てたよ

草むしり？

<audio></audio><hr>

あぁ！　あの　パーッと来て ピューッて帰ったクマね

<audio></audio><hr>

よう！　シロクマ

おはよう　グリズリーさん

おっ！　パンダも行くのか

このちっちぇえのは　鳥か？

ペンギンだよ！

<audio></audio><hr>

ちっちゃくて わかんなかったぜ

コウテイペンギンは　ペンギン界のなかでは 最大のペンギンだよ！

<audio></audio><hr>

クマより　ちっちぇえのに 変わりはないだろう？

なっ！？

ほら！　行くぞ

<audio></audio><hr>

あのクマ！　失礼しちゃうな

グリズリーさん わりと　ざっくりしてるからね

キミが言わないで

<audio></audio><hr>

涼しいね

さすが　大自然は気持いいね

<audio></audio><hr>

よし！　じゃあ　まず…

キャンプの係を決めようぜ！

ちょっと　ちょっと！ わきから　仕切らないでよ

いいだろ？ 別に　誰が仕切っても

<audio></audio><hr>

お前ら！

何やってんの？

大自然のなかで読書

え～　どうしたの？ あっ！　もう　ご飯の時間？

違うよ！

<audio></audio><hr>

とっとと準備しねえと 日が暮れちまうぞ

きちんと 準備しようよ　ペンギンさん

<audio></audio><hr>

今　その話をしていたんだよ！

まずは係を決めようよ　グリズリーくん

だから　そう言ってんだろ！

<audio></audio><hr>

何から　するの？

まずはテントの設営だな　それから　火起こし　調理飯炊きは分担するか

<audio></audio><hr>

じゃあ…　ご飯ができたら起こして

おい！　パンダくんもやるの！

<audio></audio><hr>

そうなの？

そうなの！

係は　どうする？

そうだね…

テントはみんなで　火起こしはシロクマ

調理が俺で　飯炊きはペンギンだ

ちょっと！ 勝手にどんどん決めないでよ

<audio></audio><hr>

細けぇこと　気にすんなよ　鳥！

と…　鳥！？

ねぇ　僕は？

お前は手伝い係ってとこか？

<audio></audio><hr>

じゃあ　まずはテント張ろう

テントできた！

できてないよ！

それ　テントじゃねえだろ！

<audio></audio><hr>

完成だね

いつもは野暮ったいペンギンさんが 輝いてみえるよ

パンダくん そういう感想はいらないから

<audio></audio><hr>

じゃあ　中に入ってみよう

<audio></audio><hr>

狭いだろ！

これは全員入るのはムリだね

どうすんだよ　シロクマ！

<audio></audio><hr>

名案があるよ

どうするの？

テントをもう一つ持ってきたから 

<audio></audio><hr>

２つ建てよう

あんのかよ！

先に言ってよ！

<audio></audio><hr>

さぁ　夕食の支度するぞ

薪は　どうなった？

それは…

マス！

シロクマくんは　マスじゃなくて 薪を集めてよ！

火起こし係なんだから！

<audio></audio><hr>

みんな　真面目に 自分の係やってほしいよ

まったくだな

<audio></audio><hr>

アチッ！　アチチチ！ うわっ　アチッ！

ちょっと　やめてよ！ 火が　はぜるでしょ！

え～　せっかく　集めてきたのに

<audio></audio><hr>

何やってんだ！

切り株はやめてよ！ むしろ　火が消えちゃうよ

せっかく　集めてきたのに

<audio></audio><hr>

まったく　パンダもシロクマも…

手がかかるよね

<audio></audio><hr>

いいニオイ…

何作ってるの？

カレーだ

キャンプの定番だよね

あっ　そうだ！

<audio></audio><hr>

隠し味～！

入れんなよ！

笹がないカレーなんて…

ないの！　普通は

<audio></audio><hr>

まったく　油断も隙もねえ

シロクマくん！

余計なもん 入れんなって言ってんだろ！

<audio></audio><hr>

シーフードカレーにしようかと…

シーじゃなくて レークになっちゃうでしょ

<audio></audio><hr>

ねぇ 焦げ臭くない？

真っ黒だ…

<audio></audio><hr>

アイツらかまってて　忘れてたな

ごめん…

気にすんな

お～い！　小麦粉　持ってきてるよ

<audio></audio><hr>

カレーだし　ナンでも焼くか

<audio></audio><hr>

おいしいね～

苦労して作った甲斐があるね

シロクマくん　すご～い！

ピザじゃないんだよ！

おもに作ったのは 僕とグリズリーくんだけど…

だよな

<audio></audio><hr>

よし　沸いたな

１ば～ん！

お前は後だ

ペンギン　お前から入れよ

<audio></audio><hr>

お前が　いちばん働いたからな

ありがとう

<audio></audio><hr>

どうだ？　湯かげんは

本当は　あったかいお風呂より 冷たいほうがいいけど…

ちょうどいいよ

<audio></audio><hr>

そうか　ま　あったまれよ

<audio></audio><hr>

いい気持…

<audio></audio><hr>

どう？　湯かげんは

パンダくん　煮えてるよ！

氷風呂もあるよ

シロクマくん　最初から言ってよ！

<audio></audio><hr>

そろそろ寝るか

じゃあ　誰と誰が同じテントになるか　くじ引きしよう

みんな　１本ずつ引いてくれ

<audio></audio><hr>

葉っぱがついてるよ

ひとつは　シロクマとパンダ

もうひとつは俺とお前だな

<audio></audio><hr>

今日はお疲れ

だね

お前も大変だろう

えっ？

ったく　シロクマもパンダも 何もしやしねえどころか

面倒ばかりかけやがるからな

<audio></audio><hr>

そうそう

世話が焼けるよな

でも　何だか

放っとけねえんだよな

<audio></audio><hr>

飲むか　とっておきの 持ってきたんだよ

いいね！

俺たちも苦労するよな

<audio></audio><hr>

なぁ　ペンギン

まったくだよ　面倒見きれないよ！

あ～　叫びたいぜ！

叫ぼう！

<audio></audio><hr>

何やってるんだろう？

騒がしいね

<audio></audio><hr>

こんなところで寝てると 風邪ひくよ

もう　ペンギンさんも グリズリーくんもホントに…

世話が焼けるね

それは…

そっちだ

<audio></audio><hr>



