---
title: "パンダくんのダイエット"
---

パンダくんのダイエット

<audio controls>
<source src="06/001.mp3">
</audio><hr>

いらっしゃいませ　

どうしたの？　元気ないね

<audio controls>
<source src="06/002.mp3">
</audio><hr>

パンダくん　いつもの？

うん

あぁ　いや…　普通盛りで

<audio controls>
<source src="06/003.mp3">
</audio><hr>

えっ！？　大盛りじゃないの？

今日から　ダイエットするの

<audio controls>
<source src="06/004.mp3">
</audio><hr>

ダイエット？

それは　インターネット

それは　イヌイット

それは　カルテット

<audio controls>
<source src="06/005.mp3">
</audio><hr>

どうしたの？　急に

実は　今日　動物園でさ…

<audio controls>
<source src="06/006.mp3">
</audio><hr>

パンダさん！

サービス　サービス

<audio controls>
<source src="06/007.mp3">
</audio><hr>

え～っ！？　ケガしなくて　よかったね

それで　ダイエット？

<audio controls>
<source src="06/008.mp3">
</audio><hr>

まぁ　昔から　

スマートな動物に 生まれたかったなって　思ってたんだよ

<audio controls>
<source src="06/009.mp3">
</audio><hr>

スタイル　気になるの？

うん　だって…

生まれたときから おっさん体型なんだもん

<audio controls>
<source src="06/010.mp3">
</audio><hr>

どうなりたいの？

僕の理想はね…

<audio controls>
<source src="06/011.mp3">
</audio><hr>

もっと　脚が長くて

逆三角形の体型で

顔も逆三角形なの

<audio controls>
<source src="06/012.mp3">
</audio><hr>

ドリームパンダ　ハハハハハ！

それ　かっこいいの？

パンダくん 悪いヤツみたいになっちゃうね

<audio controls>
<source src="06/013.mp3">
</audio><hr>

いいの 僕　ワルに憧れてるから

お待たせ

はい　普通盛りね

<audio controls>
<source src="06/014.mp3">
</audio><hr>

やっぱり　いつもので

大盛りね

ダイエットは？

明日からにするよ

<audio controls>
<source src="06/015.mp3">
</audio><hr>

パンダくん　起きなさい！

たった　週２回のバイトなのに

朝から居眠りしないでよ

はい　パンダだんご

<audio controls>
<source src="06/016.mp3">
</audio><hr>

いらない

えっ！？　どうして？

今日から　ダイエットするの

ダイエット！？

へぇ…　私なんか すっかり　メタボだけど

なんにもしてないな

<audio controls>
<source src="06/017.mp3">
</audio><hr>

昨日は　すべり台を 壊しちゃったしさ…

ごめん　ごめん

あれは　柱が シロアリに食われてたからで

パンダくんのせいじゃないから

<audio controls>
<source src="06/018.mp3">
</audio><hr>

それに　まだ若いのに おっさん体型だし…

でも　それが自然なパンダだし

そもそも パンダの名前の由来を知らないの？

<audio controls>
<source src="06/019.mp3">
</audio><hr>

えっ　何？　かわいいとか？

まぁ　いろんな説があるんだけどさ 

<audio controls>
<source src="06/020.mp3">
</audio><hr>

そのうちの一つは…

むか～しむかし

外国人が　中国を 探検していたときのこと…

<audio controls>
<source src="06/021.mp3">
</audio><hr>

what's the name of that animal?

あ～　パンダ…

ah~ they're called pandas

<audio controls>
<source src="06/022.mp3">
</audio><hr>

こうして　中国語の 「太った」という意味のパンダが

名前として 広まったという説があるんだ

<audio controls>
<source src="06/023.mp3">
</audio><hr>

じゃあ　僕って…

パンダ　パンダ

メタボー　メタボー

なんか　

<audio controls>
<source src="06/024.mp3">
</audio><hr>

すごくへこんできた…

世の中には　知らないほうが 幸せなこともあるよね

<audio controls>
<source src="06/025.mp3">
</audio><hr>

バイトのせいだよ

超ヒマで　

おやつを食べて　お昼寝するしかないから 太っちゃったんだ

<audio controls>
<source src="06/026.mp3">
</audio><hr>

ヒマじゃないでしょう！

ちゃんと お客さんにサービスしなさい！

なんか最近　マンネリでさ…

タイヤやすべり台で遊ぶのも 飽きちゃって…

お仕事でしょ！

ねぇ　フィットネスゲーム持ってきていい？

<audio controls>
<source src="06/027.mp3">
</audio><hr>

ダメ！

ゲルマニウム温浴　作ってよ

ダメです！

エアロビのお姉さんを呼ぼうよ

ダメだってば！

<audio controls>
<source src="06/028.mp3">
</audio><hr>

はぁ～あ… なんか　きっかけさえあれば

もっと　ダイエットやる気になるのにな

まぁ　ダイエットしたいなら しっかりとサービスに励みなさい

は～い　任せて

僕って　やればできる子だから

じゃあ　ちゃんと頼むよ

<audio controls>
<source src="06/029.mp3">
</audio><hr>

パンダさん　起きて～！

パンダさん　かわいい！

<audio controls>
<source src="06/030.mp3">
</audio><hr>

サービス　サービス！

サービス　サービス！

かわいいって言われたときだけ 反応するね

サービス　サービス！

この下膨れ体型が かわいいんだよね

メタボパンダさんだね

<audio controls>
<source src="06/031.mp3">
</audio><hr>

目指せ　ドリームパンダ！

パパンダー　パパンパン　パパンダー

パパンダー　パンパンパン　パパンダー

<audio controls>
<source src="06/032.mp3">
</audio><hr>

ダイエット！

ダイエット

ダイエット…

<audio controls>
<source src="06/033.mp3">
</audio><hr>

パンダさ～ん！

ダイエット　ダイエット！

ダイエット　ダイエット！

ダイエット　ダイエット！

<audio controls>
<source src="06/034.mp3">
</audio><hr>

何だか　ドキドキするね

大丈夫だよ

ここんとこ ずっと頑張ってたんだから

<audio controls>
<source src="06/035.mp3">
</audio><hr>

目標　とりあえず　１３０キロ

<audio controls>
<source src="06/036.mp3">
</audio><hr>

やった！

おめでとう　ダイエット成功だね

僕　もっと頑張って スリムなドリームパンダになるよ

いや～ そこまでしなくていいから

頑張ったパンダくんに ご褒美があるよ

えっ　何？

<audio controls>
<source src="06/037.mp3">
</audio><hr>

楽しく滑れるように 工夫してみたんだ

パンダくんが マンネリって言ってたからね

半田さん　ありがとう

<audio controls>
<source src="06/038.mp3">
</audio><hr>

待ってたよ　一緒に初滑りしよう

うん！

<audio controls>
<source src="06/039.mp3">
</audio><hr>

ワーイ！

あっ！　どうしたんですか？

あ　いや… お腹がつっかえて…(´･ω･)

常勤パンダさん　メタボ

ハァー　作り直しかな…

<audio controls>
<source src="06/040.mp3">
</audio><hr>
