---
title: "カフェの怪談"
---

<span id="episode-title" data-episode="35"> カフェの怪談 </span> 

<audio></audio><hr>

笹子さん 今日の夜　あれやるよ

えっ！？ あれ　ホントに　やるんですか？

何？　あれって…

<audio></audio><hr>

ほら　夏の定番の…

定番？

それは　黒板

<audio></audio><hr>

それは　食パン

それは　海パン

それは　階段

大当たり！

怪談やるよ

<audio></audio><hr>

これでだいたい揃ったかな

僕　帰ってもいいですか？

怖い話 聞きたいっていうから　連れてきたよ

<audio></audio><hr>

苦手だって言ってるのに…

ロウソクは　これでいいですか？

うん

そんなのいらないですよ！

<audio></audio><hr>

ほら～　やっぱり　こうなっちゃう

ムードがあって　いいんじゃない？

しろくまカフェ怪談ナイトにようこそ

<audio></audio><hr>

帰りたいな

帰り道に おばけが出るかもしれないよ

なんでそういうこと言うの！？

わかりましたよ！　いますよ

<audio></audio><hr>

始めようか

じゃあ　僕から

これは　僕が実際に体験した

動物園のラマコーナーで 起こったことなんですけど

<audio></audio><hr>

その夜　ラマコーナーには　残業していた 僕しかいなかったんです

<audio></audio><hr>

僕が　いつものように 草を食べていると

ふと　何かの気配を感じたんです

<audio></audio><hr>

け…　気配？

けど　他のラマたちはいるはずがありません

錯覚だろうと思って 僕はまた草を食べ始めました

<audio></audio><hr>

ところが… やっぱり何かの気配を感じます

<audio></audio><hr>

その気配は どんどん近づいてきて

ついに　僕のすぐ後ろに…

僕は　思い切って振り返ったんです

そこにはいるはずのない

シマウマが…

<audio></audio><hr>

いるはずのない　シマウマの姿は

次の瞬間 跡形もなく消えていました

あぁ～！！

<audio></audio><hr>

あれ？　怖くなかったですか？

シマウマの霊ですよ？

なんか　シマウマの霊って言われても ピンと　こないっていうか…

<audio></audio><hr>

僕は話してるだけで ゾッとしますよ

シマウマ…　シマウマ…

全然　怖くないよ じゃあ

次　僕ね

<audio></audio><hr>

パンダくん？

あっ！　寝てる！

パンダくん！

あっ　暗いと眠くなるね

<audio></audio><hr>

頑張ろうよ

こないだの夜 僕がベッドで寝ようとしたとき…

<audio></audio><hr>

あれ？　何時頃に寝たんだっけ？

いいよ　そこは何時でも　続けて

<audio></audio><hr>

けど　今が眠いよ

頑張ろうよ　パンダくん

わかった！

<audio></audio><hr>

僕が　ベッドで寝てると

枕もとで変な音がしたんだよ

<audio></audio><hr>

変な音っていうのは どんな音かな？

僕に聞かれても困るよ

どんな音だったの？

<audio></audio><hr>

忘れたよ

パンダくん　もういいから… キミ　聞いてて

<audio></audio><hr>

じゃあ　僕が話すよ

去年の夏のことだけど…

やめて！

まだ　何も話してないのに

顔　怖すぎ！

<audio></audio><hr>

じゃあ　僕が…

ゾウガメくん　頼むよ　思いっきり　怖いやつ

動物好きの～　

<audio></audio><hr>

タカシくんは～

ペース　上げられないかな？

わかった～

<audio></audio><hr>

タカシくんが亡くなりました～

お母さんは　毎日　お墓に

タカシくんが好きだった パンの耳を持っていきました～

<audio></audio><hr>

もう　オチ　いこう　終わらないから

うん

ある日　お墓から声が…

<audio></audio><hr>

お母さん… もう　パンの耳は飽きたよ

じゃあ　何がいいの？

それは…

お前の耳だ～

<audio></audio><hr>

あれ？

寝てた～？

遅いんだな 怖がるタイミングを逃しちゃうよ

み　み…　耳！　耳！！

<audio></audio><hr>

半田さん　よく怖がれるね

じゃあ　次は　僕が話すよ

<audio></audio><hr>

あるペンギンが体験した

皆さんの知らない世界の話を お聞かせします

そのペンギンが　あるパン屋に 出かけたときのことです

<audio></audio><hr>

そこには　１人の 看板ペンギンの女の子がいました

彼女に会うため　ペンギンは 毎日　毎日　パン屋に通いました

ところが　ある日

<audio></audio><hr>

１人だと思っていた ペンギンの女の子が

７人いたのです！

<audio></audio><hr>

それは　怖かっただろうね

怖かった…

けど　そういう 怖いのじゃなくて…

怖いのは おばけじゃなくて　ペンギンだよ

<audio></audio><hr>

大変なんだね　ペンギンさん

つらいよ　毎日が

<audio></audio><hr>

実は　僕にもつらくて怖い話があるんだよ

そうなの？

そう

<audio></audio><hr>

あれは…

その昔　僕の毛が まだ　黒かった頃のこと

ちょっと待って！

<audio></audio><hr>

なんだろう？　その話…

待たなくていい？

うん　という答えも待たずに 話は続くんでしょ？

<audio></audio><hr>

ある日　川で 鮭をたくさんとったあと

お腹がいっぱいになって 昼寝していた　僕の耳もとで何か音がした

<audio></audio><hr>

なんと　ネズミが 僕の耳をかじっていた

あまりの恐怖で…

<audio></audio><hr>

こうして　僕の毛は白くなった

だから僕は今でもネズミが怖い…

待って！

別の意味で怖いよ　その話

<audio></audio><hr>

ダメ？

ダメ！

どういう意味？

知らなくていいの

ネ…　ネ…　ネズミ…　ネズミ…

<audio></audio><hr>

半田さん　いいお客だな

じゃあ　次　笹子さん

<audio></audio><hr>

私　あんまりうまくないんですよ

怖い話とか苦手で…

あっ！　ぼ…　僕も同じです

あ…　でも　笹子さんの話 聞いてみたいな

<audio></audio><hr>

じゃあ　ちょっとだけ

<audio></audio><hr>

と　振り返ると…

やめて～っ！

<audio></audio><hr>

怖すぎるね…

もういい！

けど　ここからが怖いんですよ？

ごめん…　もういいから

半田さん！

<audio></audio><hr>

じゃあね　半田さん

もし　おばけ見たら　電話してね

バイバーイ

<audio></audio><hr>

やっぱり　今日は 誰かと一緒に帰ろうかな

<audio></audio><hr>

半田さん

半田さん　１人で帰るの 怖いんじゃないですか？

<audio></audio><hr>

あ…　それは…

でしたら…　私でよかったら 送っていきますよ

<audio></audio><hr>

あ…　じゃ…　じゃあ…

そうですか

僕　半田さんと 方向　一緒ですから

<audio></audio><hr>

それなら 僕が　送っていきますよ

あ…　けど…

気にしないでください

<audio></audio><hr>

それじゃあ ラマさん　半田さん　また

また

また…

<audio></audio><hr>

ねぇ　これでよかったのかな？

よかったんじゃない？ 怖くなく帰れて

<audio></audio><hr>

半田さん　ラクダの霊って 見たことありますか？

えぇ？　ないよ

僕　この前　トイレで見たんですよ

えっ　そうなの！？

<audio></audio><hr>



