---
title: "パンダくんの悩み"
---

パンダくんの悩み

<audio controls>
<source src="audio/06/001.mp3">
</audio><hr>


笹子さん　肉じゃがが好きな男って　どう思う？

<audio controls>
<source src="audio/06/002.mp3">
</audio><hr>

え！？　今　答えなくていいですか？

いいですよ

<audio controls>
<source src="audio/06/003.mp3">
</audio><hr>

つれないなぁ

<audio controls>
<source src="audio/06/004.mp3">
</audio><hr>

ねえ　僕　いまだに　自然体っていうのがわからないの

自然体でいいです

<audio controls>
<source src="audio/06/005.mp3">
</audio><hr>

いくら考えても　答えが出なくて

常勤パンダさん　自然体って何？

寝てる！

<audio controls>
<source src="audio/06/006.mp3">
</audio><hr>

ねえ　半田さん

自然体って何？

言ったでしょ　

<audio controls>
<source src="audio/06/007.mp3">
</audio><hr>

「自然体でいいです」って

自然でいることが　自然体じゃないかな

ちょっと　お手本見せてよ　

えぇ～

<audio controls>
<source src="audio/06/008.mp3">
</audio><hr>

こんな感じだけど

かわいくないo(╯□╰)o

えぇ～～

<audio controls>
<source src="audio/06/009.mp3">
</audio><hr>

う～ん

自然体って　どういうことなの？

こんな表情？

<audio controls>
<source src="audio/06/010.mp3">
</audio><hr>

自然体かどうか　わかんないけど　かわいいね

これは？o(　=∩ω∩=　)m　

かわいい

これは～？n(*≧▽≦*)n　

もう　かわいいのは　わかったよ

<audio controls>
<source src="audio/06/011.mp3">
</audio><hr>

そうなんだよね

かわいい　かわいいって言われても　どうしていいか　わかんなくて

<audio controls>
<source src="audio/06/012.mp3">
</audio><hr>


いいなぁ　僕も　かわいいって　言われてみたいですよ

<audio controls>
<source src="audio/06/013.mp3">
</audio><hr>


ゴロゴロしてるだけなのになぁ

<audio controls>
<source src="audio/06/014.mp3">
</audio><hr>

楽しそうで　うらやましいよ

ラッコさん？

僕さ　お腹で貝割るでしょ？ヾ(≧へ≦)〃

<audio controls>
<source src="audio/06/015.mp3">
</audio><hr>

あれって大変だよ　お腹痛くなる

<audio controls>
<source src="audio/06/016.mp3">
</audio><hr>

お腹に石だよ　笹子さん　

はい？

自分のお腹を石で叩いてみなよ

<audio controls>
<source src="audio/06/017.mp3">
</audio><hr>

痛いでしょ？　

はい…

お腹で割らなければいいのに

<audio controls>
<source src="audio/06/018.mp3">
</audio><hr>

あれをやると　お客が　わくからさ

もうやめたら？　その出し物

出し物っていうか　習性だからね

<audio controls>
<source src="audio/06/019.mp3">
</audio><hr>

かわいいから　いいじゃないですか

かわいいんだけどさ　もう　お腹が限界

かわいいで言ったら　私も　かわいいんですけど

<audio controls>
<source src="audio/06/020.mp3">
</audio><hr>

コアラさん？

ユーカリ？　かわいく食べてますけど　もう　あれ限界です

飽きました（╯－＿－）╯╧╧

<audio controls>
<source src="audio/06/021.mp3">
</audio><hr>

１日それを　１キロくらい食べるんですから

涙目にもなりますよ(　-。-)

<audio controls>
<source src="audio/06/022.mp3">
</audio><hr>

わかる　わかるよ～

コアリクイくんも？

アリクイって　やめて！

<audio controls>
<source src="audio/06/023.mp3">
</audio><hr>

僕だってね　アリばっかり　食べたくないよ！　飽きたよ。

笹子さん　アリばっかり食べる気持わかる？

はい？(　⊙　o　⊙　)？わかりません

<audio controls>
<source src="audio/06/024.mp3">
</audio><hr>

アリクイだからね

しかたないね

確かに　そうだけど　もっと　いろんなもの食べてみたいよ

いろんなもの？

<audio controls>
<source src="audio/06/025.mp3">
</audio><hr>

何食べたいの？

ほら　ラーメンとかさ

チャーシュー食べられないんじゃない？

いいんだよ　細かいところは

<audio controls>
<source src="audio/06/026.mp3">
</audio><hr>

見てくれるだけ　いいじゃないですか

ラマさん？

僕なんて　みんな　ほぼ素通りですよ

<audio controls>
<source src="audio/06/027.mp3">
</audio><hr>

いるの　気づいてます？

そういえば…

<audio controls>
<source src="audio/06/028.mp3">
</audio><hr>

動物園に行ったとき…

みごとに素通りしたね

ほらね　ラマなんて　そんなものですよ

<audio controls>
<source src="audio/06/029.mp3">
</audio><hr>

もっと　じっくり見たり

行列つくって　感想とか言ってほしいですΣ(　￣д￣　)　

<audio controls>
<source src="audio/06/030.mp3">
</audio><hr>

わぁ～い　ラマさん！

おい　見ろよ！　草食ってるぞ！　写真　写真撮れって！

草　食べてるだけ？　

<audio controls>
<source src="audio/06/031.mp3">
</audio><hr>

地味だね

ラマさんって　ロバなの？

だから　ラマです

どっちかというと　ラクダです

<audio controls>
<source src="audio/06/032.mp3">
</audio><hr>

コブは？　

ないです

あの…　何か芸とかないんですか？

草を食べるくらいです

あと　まつ毛が長いです(￣y▽￣)╭　

<audio controls>
<source src="audio/06/033.mp3">
</audio><hr>

できるといいね　行列

見られればいいってもんじゃないよ　

バクさん

<audio controls>
<source src="audio/06/034.mp3">
</audio><hr>

僕なんて　夢を食べる動物って　言われがちだけど

見た人に夢がないなんて　言われてさ

<audio controls>
<source src="audio/06/035.mp3">
</audio><hr>

夢を食べる動物って何？

ハードル上げすぎなんだよ

<audio controls>
<source src="audio/06/036.mp3">
</audio><hr>

まぁまぁ…　ジュゴンさんよりは　いいよ

人魚って　前振りされてるんだから

<audio controls>
<source src="audio/06/037.mp3">
</audio><hr>

ママ！　人魚さん　どこ？

<audio controls>
<source src="audio/06/038.mp3">
</audio><hr>

見た人　みんな黙っちゃうよ

ねぇ？　

私に聞かないでください…

<audio controls>
<source src="audio/06/039.mp3">
</audio><hr>

あぁ　そうだね…

ジュゴンさんに比べたら　僕は　まだ　マシかもね

<audio controls>
<source src="audio/06/040.mp3">
</audio><hr>

僕も…　

ナマケモノくん

動物園とは関係ないけど…

<audio controls>
<source src="audio/06/041.mp3">
</audio><hr>

僕って　一日中　木に　ぶら下がってるイメージあるけど…

<audio controls>
<source src="audio/06/042.mp3">
</audio><hr>

実際　どうなの？

実際　そうだけど…　大変　腕　パンパン

<audio controls>
<source src="audio/06/043.mp3">
</audio><hr>

一日中　木に　ぶら下がったことある？笹子さん

え？(⊙﹏⊙)　ないです

ナマケモノくんって　ナマケモノじゃないな　

頑張り者だね

もっと言って

<audio controls>
<source src="audio/06/044.mp3">
</audio><hr>

みんな悩んでるんだな

僕も悩んでてね　O(￣︶￣)n　

実は　好きなペンギンがいてさ

<audio controls>
<source src="audio/06/045.mp3">
</audio><hr>

誰にも　言わないでほしいんだけどね

あぁ　やっぱり　いろいろと　皆さん悩みが尽きないんですね

<audio controls>
<source src="audio/06/046.mp3">
</audio><hr>

そうだよね

ほんとですね

ちょっと　聞いてよ　

シロクマさんは　悩みはないの？

<audio controls>
<source src="audio/06/047.mp3">
</audio><hr>

あるよ　

え？　そうなの？　意外

アイドルにならないかって　言われてるんだけど

<audio controls>
<source src="audio/06/048.mp3">
</audio><hr>

アイドルと学業の両立がねぇ

また嘘ばっかり

<audio controls>
<source src="audio/06/049.mp3">
</audio><hr>

笹子さんは？

え？　ありません　

ひとつも？　

はい

あ…　

ん？　何？

<audio controls>
<source src="audio/06/050.mp3">
</audio><hr>

雛人形って　燃えるゴミなのか、燃えないゴミなのか　どっちなんだろうって

いいかな？　それは　あとで

<audio controls>
<source src="audio/06/051.mp3">
</audio><hr>

僕なんてさ　パン屋に行くたびに思うよ

<audio controls>
<source src="audio/06/052.mp3">
</audio><hr>

いい？　誰にも言わないでよ

どうやって告白しようか　悩みは尽きないよ

どう思う？　パンダくん

<audio controls>
<source src="audio/06/053.mp3">
</audio><hr>

フフフ…　

ちょっと笑いごとじゃないよ

寝てる！W(ﾟДﾟ)w

<audio controls>
<source src="audio/06/054.mp3">
</audio><hr>

えぇと…

いつから　寝てたんですかね？

チャーシューの話のあとくらいじゃない？

<audio controls>
<source src="audio/06/055.mp3">
</audio><hr>

前半ですね

あっ　シロクマさん

おかわり　お願いします　

<audio controls>
<source src="audio/06/056.mp3">
</audio><hr>

うん

自然体かぁ

どうしたら　いいんだろう…

パンダくん　すっかり自然体だね

そうですね　

<audio controls>
<source src="audio/06/057.mp3">
</audio><hr>

いらっしゃい(　＾?＾）／　＼(　＾?＾）　

はぁ…　今日は疲れちゃった

パンダくん　

<audio controls>
<source src="audio/06/058.mp3">
</audio><hr>

なぁに？

あれから　ずっと考えてたんだけどさ

<audio controls>
<source src="audio/06/059.mp3">
</audio><hr>

パンダくんにとって　自然体っていうのはさ

君が　いちばんリラックスできる場所

<audio controls>
<source src="audio/06/060.mp3">
</audio><hr>

あっ！

つまりさ…　

そんなことより　ペンギンさん

新しいパンダグッズ　買っちゃったんだけど

何入れればいいと思う？O(*≧▽≦)ツ

肉まんでいいんじゃない？

<audio controls>
<source src="audio/06/061.mp3">
</audio><hr>

