---
title: "パンダくんの夜遊び"
---

パンダくんの夜遊び

<audio>
<source src="audio/22/001.mp3">
</audio><hr>

お疲れさまでした

お疲れさま

<audio>
<source src="audio/22/002.mp3">
</audio><hr>

パンダくん　閉店なんだけど

<audio>
<source src="audio/22/003.mp3">
</audio><hr>

パンダくん？

ああ　おはよう

もう　夜だよ

<audio>
<source src="audio/22/004.mp3">
</audio><hr>

グリズリーくん

よう　ちょっと遊びに行こうぜ

いいよ

<audio>
<source src="audio/22/005.mp3">
</audio><hr>

遊びに行くの？

僕も行きたい！

ガキの行くところじゃねぇんだよ

<audio>
<source src="audio/22/006.mp3">
</audio><hr>

大人の夜遊びだ

夜遊び？

なんか　すごくおもしろそう

<audio>
<source src="audio/22/007.mp3">
</audio><hr>

何でついてくるんだよ

グリズリーくんが　誘ったんじゃない

お前じゃねぇよ

<audio>
<source src="audio/22/008.mp3">
</audio><hr>

コイツだよ

どこ行くの？

<audio>
<source src="audio/22/009.mp3">
</audio><hr>

というわけで　パンダくん

今日は残念だけど中止だから帰ろう

残念

<audio>
<source src="audio/22/010.mp3">
</audio><hr>

何でそうなるんだ！

ちょっと待て！

やっぱり行くの？

行くに決まってんだろ！

<audio>
<source src="audio/22/011.mp3">
</audio><hr>

すごい　ここ何？

バッティングセンター

<audio>
<source src="audio/22/012.mp3">
</audio><hr>


来たことねぇのか

何やってんだよ！

ぶら下がって遊ぶとこじゃねぇんだよ！

<audio>
<source src="audio/22/013.mp3">
</audio><hr>


そうなの？

ったく…

<audio>
<source src="audio/22/014.mp3">
</audio><hr>

これ気持いいね

だから　そうじゃねぇんだよ

<audio>
<source src="audio/22/015.mp3">
</audio><hr>

結構　凝りがほぐれるね

お前までやってんじゃねぇ！

<audio>
<source src="audio/22/016.mp3">
</audio><hr>

じゃあ　ここで何して遊ぶの？

向こうから来た球を 打ち返すんだよ

こうやるんだ

<audio>
<source src="audio/22/017.mp3">
</audio><hr>

ナイスキャッチ

シロクマくんすご～い！

ピッチャーライナーだね

<audio>
<source src="audio/22/018.mp3">
</audio><hr>

何やってんだよ！！

僕もやる

やらなくていいんだよ！

<audio>
<source src="audio/22/019.mp3">
</audio><hr>

大当たり！

グリズリーさんやったね！

<audio>
<source src="audio/22/020.mp3">
</audio><hr>

なんかもうやる気なくなったぜ

じゃあ僕がお手本を

さあ　来い！

<audio>
<source src="audio/22/021.mp3">
</audio><hr>

バット　持ちすぎだろう！

じゃあ　改めてお手本を

<audio>
<source src="audio/22/022.mp3">
</audio><hr>

バット　使えよ！

もう　いい… パンダ　とにかく　やってみろ

<audio>
<source src="audio/22/023.mp3">
</audio><hr>

パンダくん　バットを構えて よ～く球を見るんだよ

<audio>
<source src="audio/22/024.mp3">
</audio><hr>

いや　そうじゃなくてな…

ボールを　しっかり見て

じ～～～

こう？

打てよ

<audio>
<source src="audio/22/025.mp3">
</audio><hr>

やっぱり？

やっぱりじゃねぇ！ バットで当てろ！！

<audio>
<source src="audio/22/026.mp3">
</audio><hr>

ナイスショット

やったぁ！

ゴルフじゃねぇ！！

<audio>
<source src="audio/22/027.mp3">
</audio><hr>

積み木じゃねぇ！

ビリヤードじゃねぇ！

<audio>
<source src="audio/22/028.mp3">
</audio><hr>

ああ　おもしろかった

全然　バッティングしてねぇけどな

次　いくぞ

また　どこか行くの？

<audio>
<source src="audio/22/029.mp3">
</audio><hr>

夜はこれからだからな

これからなんだ…

次は　どこかな？

<audio>
<source src="audio/22/030.mp3">
</audio><hr>

風呂だ！

広い！

すごいね！

すげぇだろう？

<audio>
<source src="audio/22/031.mp3">
</audio><hr>

本当だ！

<audio>
<source src="audio/22/032.mp3">
</audio><hr>

すごいよ！！

そういう　すげぇじゃ ねぇんだけどな…

ほら　ほら

まずはちゃんと体洗えよ

<audio>
<source src="audio/22/033.mp3">
</audio><hr>

背中　流してあげようか？

うん　頼むよ

<audio>
<source src="audio/22/034.mp3">
</audio><hr>

背中　流してあげようか？

おう　お前も ちったぁ気が利くじゃねぇか

<audio>
<source src="audio/22/035.mp3">
</audio><hr>

やめろ 何か　こそばゆいぞ

パンダくん もっと強くこするんだよ

<audio>
<source src="audio/22/036.mp3">
</audio><hr>

イテーッ！！　ツメ　立てんな　ツメ！

あっ　ごめん

<audio>
<source src="audio/22/037.mp3">
</audio><hr>

目に染みるよ

早く流せ

グリズリーさん…

誰？

<audio>
<source src="audio/22/038.mp3">
</audio><hr>

ハア…　

すっきり

グリズリーさんも流してあげるよ

おう　頼むぜ

アチーッ！！　熱いじゃねえか！

ごめんなさい…

<audio>
<source src="audio/22/039.mp3">
</audio><hr>

赤いほうを回すとお湯で

青いほうが水だからな

<audio>
<source src="audio/22/040.mp3">
</audio><hr>

わかった

冷てぇ！！　ちゃんと調節しろよ！

ごめんなさい…

<audio>
<source src="audio/22/041.mp3">
</audio><hr>

アチーッ！！

冷てぇ！！

アチーッ！！

冷てぇ！！

<audio>
<source src="audio/22/042.mp3">
</audio><hr>

えっと…　えっと…

パンダ…　もういい　気持だけ　もらっとく

<audio>
<source src="audio/22/043.mp3">
</audio><hr>

いいニオイになったね

何の香りだ？　ここのシャンプー

うん　すごく　おいしそうなニオイ

<audio>
<source src="audio/22/044.mp3">
</audio><hr>

これ

クマザサシャンプーだね

飲めないかな？

飲むんじゃねぇぞ

<audio>
<source src="audio/22/045.mp3">
</audio><hr>

というわけで　パンダくん お風呂に入れてみよう

いいね

よくねぇ　やめろ

<audio>
<source src="audio/22/046.mp3">
</audio><hr>


わ～い！ わ～い　飛んだ飛んだ！

そうそう　うまい　うまい

あれ　どうやるの？

こうだよ

<audio>
<source src="audio/22/047.mp3">
</audio><hr>

やめろ！

ったく！

どこ行くの？

俺は　サウナが好きなんだ

<audio>
<source src="audio/22/048.mp3">
</audio><hr>

それは　魚！

それは　アンテナ！

それは　手品！

サウナって何？

<audio>
<source src="audio/22/049.mp3">
</audio><hr>

ふぅ～　なんかすごい汗出るよ

それがサウナのいいところだ

蒸されてる感じ

<audio>
<source src="audio/22/050.mp3">
</audio><hr>

これが体にいいんだよ！

もう限界…

<audio>
<source src="audio/22/051.mp3">
</audio><hr>

情けねぇな

僕も　もうダメ…

辛抱が足りねぇな

<audio>
<source src="audio/22/052.mp3">
</audio><hr>

今日は　やけに 時間が長く感じるぜ

<audio>
<source src="audio/22/053.mp3">
</audio><hr>

俺も　もう限界…

出よう

<audio>
<source src="audio/22/054.mp3">
</audio><hr>

テメエらの仕業か！

<audio>
<source src="audio/22/055.mp3">
</audio><hr>

おもしろかった！

夜遊びって　おもしろいね

小腹も空いたし 

<audio>
<source src="audio/22/056.mp3">
</audio><hr>

ちょっと一杯やってくか

いいね

えっ？　なになに？

<audio>
<source src="audio/22/057.mp3">
</audio><hr>

へい　らっしゃい！

おや　今日は新顔さんもご一緒で

親父　とりあえず　生２つ

<audio>
<source src="audio/22/058.mp3">
</audio><hr>

あとアイスコーヒーください

カフェじゃねぇんだぞ

<audio>
<source src="audio/22/059.mp3">
</audio><hr>

ああ　おいしそう！

串ごと食うなよ

<audio>
<source src="audio/22/060.mp3">
</audio><hr>

おいしい！

まぁ　ぐいっと！

ああ　すみません

夜遊びって最高だね！

だろ！

人生はな 

<audio>
<source src="audio/22/061.mp3">
</audio><hr>

昼もあれば夜もある

明るいときもあれば 暗いときもある

暗いときにも楽しいことはたくさんあるんだよ

<audio>
<source src="audio/22/062.mp3">
</audio><hr>

どっちもあるから いいんだよね

お客さん　深いね

そうだよね

パンダも白いとこと黒いとこ　両方あるからいいんだもんね

<audio>
<source src="audio/22/063.mp3">
</audio><hr>

おお　そうだな！ そのとおりだ！

だね

<audio>
<source src="audio/22/064.mp3">
</audio><hr>

グリズリーくん

すっかり寝ちゃったね　パンダくん

<audio>
<source src="audio/22/065.mp3">
</audio><hr>

なんで俺がコイツをおぶって 帰んなきゃなんねぇんだよ


<audio>
<source src="audio/22/066.mp3">
</audio><hr>
楽しかった…

楽しかったって

<audio>
<source src="audio/22/067.mp3">
</audio><hr>

まっ　また連れてきてやっても いいかな

<audio>
<source src="audio/22/068.mp3">
</audio><hr>


