---
title: "わくわくドライブレッスン"
---

わくわくドライブレッスン

<audio controls>
<source src="audio/08/001.mp3">
</audio><hr>

はぁ～

どうしたの　ペンギンさん　食あたり？

そんなんじゃないよ

<audio controls>
<source src="audio/08/002.mp3">
</audio><hr>

ペン子さんのことですよね

違うよ　今 教習所に通ってて　それで…

<audio controls>
<source src="audio/08/003.mp3">
</audio><hr>

車の免許取るんだって

どうして急に？

<audio controls>
<source src="audio/08/004.mp3">
</audio><hr>

ペン子さんをドライブに誘いたいみたい

どうして　それを？

<audio controls>
<source src="audio/08/005.mp3">
</audio><hr>

ブログに書いてありましたよ

あ～　ペン子さん　ペン子さん あなたと行きたい海辺のドライブ

僕は通うよ　教習所

<audio controls>
<source src="audio/08/006.mp3">
</audio><hr>

人の日記勝手に読まないでよ！

いや　ブログってそういうものだし

<audio controls>
<source src="audio/08/007.mp3">
</audio><hr>

読まれたくないなら 非公開にした方がいいですよ

<audio controls>
<source src="audio/08/008.mp3">
</audio><hr>

教習所　大変なんですか？

結構

車の運転って　そんなに難しいの？

まあね 

<audio controls>
<source src="audio/08/009.mp3">
</audio><hr>

教えてくれる教官は厳しいし

今日も縦列駐車ができなくってさ

最初は難しいよね　縦列駐車

<audio controls>
<source src="audio/08/010.mp3">
</audio><hr>

だよね

縦列駐車？

<audio controls>
<source src="audio/08/011.mp3">
</audio><hr>

１０列駐車？

１０列注射？

１０列カチューシャ？

１０列チュ～？

<audio controls>
<source src="audio/08/012.mp3">
</audio><hr>

じゃあ　明日１１時に集合ね

もう　聞いてなかったの？

<audio controls>
<source src="audio/08/013.mp3">
</audio><hr>

勉強に行くの

そうなの？

シロクマさんに　ペンギンさんが運転の コツを教えてもらうんですよ

<audio controls>
<source src="audio/08/014.mp3">
</audio><hr>

パンダくん　どうせ暇でしょ？

ゴロゴロするのに忙しいよ

それって暇じゃないの？ 

<audio controls>
<source src="audio/08/015.mp3">
</audio><hr>

まあいいや

じゃあ　やめとく？　ドライブ

え？　ドライブなの？　行くよ

もう

<audio controls>
<source src="audio/08/016.mp3">
</audio><hr>

じゃあ明日　カフェの前ね

うん
 
<audio controls>
<source src="audio/08/017.mp3">
</audio><hr>

パンダくん　まだかな？

呼びに行こうか？

そのうち来るよ

<audio controls>
<source src="audio/08/018.mp3">
</audio><hr>

おはよう

遅いよ　パンダくん　

え？　何　その竹は？

<audio controls>
<source src="audio/08/019.mp3">
</audio><hr>

ドライブに　おやつは必要だよ

みんなの分も持ってきたからね

<audio controls>
<source src="audio/08/020.mp3">
</audio><hr>

いや　いらないから

それ　パンダくんだけのおやつだし

おやつ

<audio controls>
<source src="audio/08/021.mp3">
</audio><hr>

それは　こたつ

それは　脚立

それは　キャベツ

いいから出発しようよ

<audio controls>
<source src="audio/08/022.mp3">
</audio><hr>

ラマさんは？

動物園のバイトだって

じゃあ　シロクマくん　頼むね

<audio controls>
<source src="audio/08/023.mp3">
</audio><hr>

後部座席って微妙だよね

寝っ転がるには狭いしさ

パンダくん　ちゃんと座って

じゃあ　行くよ

<audio controls>
<source src="audio/08/024.mp3">
</audio><hr>

お～　さすが 発車からして上手だね和

それほどでも

ねぇ　コツは？　コツ

そうだね　

<audio controls>
<source src="audio/08/025.mp3">
</audio><hr>

グッときたらピッとして ゴー！　

って感じ

抽象的だな　

<audio controls>
<source src="audio/08/026.mp3">
</audio><hr>

よくわかんないよ

ペンギンさん

 なに？

つるしたタイヤに ジャレるみたいな感じだよ　たぶん

ますます　わかんないから

<audio controls>
<source src="audio/08/027.mp3">
</audio><hr>

で　どこに行く？

山とか？

笹が　いっぱい生えてそうな

その辺でいいよ

<audio controls>
<source src="audio/08/028.mp3">
</audio><hr>

今日は　シロクマくんの運転技術を 僕が勉強するドライブなんだからね


<audio controls>
<source src="audio/08/029.mp3">
</audio><hr>

シロクマくん　免許はいつ取ったの？

大人になってから

いや　そうじゃなくてさ

<audio controls>
<source src="audio/08/030.mp3">
</audio><hr>

終わりました

ご苦労さまでした

笹の葉？

こんにちは　パンダくん

ん？

お出かけ？

おやつ中

<audio controls>
<source src="audio/08/031.mp3">
</audio><hr>

バイバ～イ！

あ～あ なんか　お腹減っちゃったね

今　笹食べてたじゃない

あっ！　あそこ行こうよ！

<audio controls>
<source src="audio/08/032.mp3">
</audio><hr>

いらっしゃいませ ご注文は　お決まりですか？

笹か竹ください

申し訳ありません 当店のメニューにはございません

えぇ～

また来ます

<audio controls>
<source src="audio/08/033.mp3">
</audio><hr>

いらっしゃいませ ご注文は　お決まりですか？

フィッシュバーガー　フィッシュ　生で

申し訳ありません 当店のメニューにはございません

えぇ～

また来ます

<audio controls>
<source src="audio/08/034.mp3">
</audio><hr>

いらっしゃいませ ご注文は　お決まりですか？

いいボケが思いつかないので

また来ます

あの　お客様！

<audio controls>
<source src="audio/08/035.mp3">
</audio><hr>

いらっしゃいませ

だから フィッシュバーガーセットでいいじゃない

レタスバーガーセットがいいよ　

笹じゃないけど葉っぱだし

てりやきバーガーセットがいいよ

よし

じゃあ…

<audio controls>
<source src="audio/08/036.mp3">
</audio><hr>

お決まりですか？

また来ます

あの　グルグル回らず そこで相談なさって かまいませんから！

ご注文を　うけたまわりました

受け渡し窓口まで お進みになって　お待ちください

はい

<audio controls>
<source src="audio/08/037.mp3">
</audio><hr>

はぁ…

うわっ！

ここでいいの？

ドライブスルーで遊ばないでください

<audio controls>
<source src="audio/08/038.mp3">
</audio><hr>

どう？　ペンギンさん　コツは　つかめた？

何の？

ドライブスルーで遊ぶコツ？

僕は　運転のコツを つかみたいんだけどな～

<audio controls>
<source src="audio/08/039.mp3">
</audio><hr>

ねえ　シロクマくん あれは　やらないの？

あれ？

ほら　わらしべ長者

<audio controls>
<source src="audio/08/040.mp3">
</audio><hr>

縦列駐車のこと？

それそれ

全然　違うから

<audio controls>
<source src="audio/08/041.mp3">
</audio><hr>

ペンギンさん　よくわかったね

ねぇ　やってみてよ　シロクマくん

ちゃんと運転のコツ教えてよ

<audio controls>
<source src="audio/08/042.mp3">
</audio><hr>

うん　わかった

よし　ここにしよう

じゃあ　よく見ててね

<audio controls>
<source src="audio/08/043.mp3">
</audio><hr>

うん

周りをよく見て　バックする

よく見て　バックね

<audio controls>
<source src="audio/08/044.mp3">
</audio><hr>

コツはね…

コツは？

こうやって　上からだと見やすい

真似できないから！　もう…

<audio controls>
<source src="audio/08/045.mp3">
</audio><hr>

あっ 何？

大丈夫？　ぶつけた？

お～い！　笹子さ～ん！

<audio controls>
<source src="audio/08/046.mp3">
</audio><hr>

あっ　シロクマさん

今日は皆さんでドライブですか？ どちらまで？

<audio controls>
<source src="audio/08/047.mp3">
</audio><hr>

当てのない旅です

笹子さんは？

家に帰るところです

<audio controls>
<source src="audio/08/048.mp3">
</audio><hr>

あ…　そうだ

これ　おすそ分け

ベーグル？

この先に　おいしいお店があるって 聞いて　買いに行ったんです

<audio controls>
<source src="audio/08/049.mp3">
</audio><hr>

わぁ～　ありがとうO(∩_∩)O

ちょうど　お腹が減ってたんだ

<audio controls>
<source src="audio/08/050.mp3">
</audio><hr>

食べてばっかりだね

育ち盛りだもの

<audio controls>
<source src="audio/08/051.mp3">
</audio><hr>

大丈夫です…　笹は別腹ですから

パンダくん　夢のなかでも まだ食べてるみたいだね

<audio controls>
<source src="audio/08/052.mp3">
</audio><hr>

ペンギンさん？

ねねね…　寝てないよ！

助手席で寝るなんて失礼なこと 僕は　しないよ！

<audio controls>
<source src="audio/08/053.mp3">
</audio><hr>

ペンギンさんって　黙ってると 寝てるか起きてるかわからないね

起きてる！　ほんと　信じて！

<audio controls>
<source src="audio/08/054.mp3">
</audio><hr>

いや　寝てても　かまわないけど

パンダくんと一緒にしないでよ！

僕は運転のコツを学ぶんだから

免許取ったら　車買うの？

<audio controls>
<source src="audio/08/055.mp3">
</audio><hr>

え？　う～ん　どうしようかなぁ

この車みたいなミニバンもいいよね～

<audio controls>
<source src="audio/08/056.mp3">
</audio><hr>

ああいうのも　かっこいいな～

ペン子さん 君に見せたいものがあるんだ

わぁ～　何かしら？

ほら　見てごらん

<audio controls>
<source src="audio/08/058.mp3">
</audio><hr>

あれは？

トビウオさ

まぁ～！

食べ放題ですよ 

すてき…

<audio controls>
<source src="audio/08/059.mp3">
</audio><hr>

ペン子さん…　

笹だらけ…

<audio controls>
<source src="audio/08/060.mp3">
</audio><hr>

ベーグル？

イーグル？

サーベル？

ヨロレ　ヒヒ～！　ヨーデル？

<audio controls>
<source src="audio/08/061.mp3">
</audio><hr>

うん…　ツッコんでくれる 相手がいないとは　寂しいね

<audio controls>
<source src="audio/08/062.mp3">
</audio><hr>

何なに？

これって…

あれだね

<audio controls>
<source src="audio/08/063.mp3">
</audio><hr>

それは　ダンク

それは　インク

それは　ピンク

それは　スカンク

いいね

<audio controls>
<source src="audio/08/064.mp3">
</audio><hr>

何言ってるの？　よくないでしょ

どうするの？　ペンギンさん

そうだなぁ 

<audio controls>
<source src="audio/08/065.mp3">
</audio><hr>

車屋さん呼べばいいのかなぁ

慌てない　慌てない

こういうときはね

<audio controls>
<source src="audio/08/066.mp3">
</audio><hr>

引いて帰ればいいから

なるほどね

コツは　バンパーにツメを引っ掛ける

<audio controls>
<source src="audio/08/067.mp3">
</audio><hr>

いろいろ 教えてもらえてよかったね

絶対　真似はできないけどね

まぁ　でも　おもしろいから 写真撮っておこう

<audio controls>
<source src="audio/08/068.mp3">
</audio><hr>

ペンギンさん　ペンギンさん　何か面白い話して

お～　パンダ君

絵に書いたようなむちゃぶりだね

<audio controls>
<source src="audio/08/069.mp3">
</audio><hr>

じゃ～今日からペンギンさんのこと　忠実な下部と考えていい

ダメ

<audio controls>
<source src="audio/08/070.mp3">
</audio><hr>

ペンギンさんって　絵に書いたようにケチだね

白熊君

さ～て　来週のしろくまカフェは　

ジャン　ケン

ちょっと　やめて　そういうの

お楽しみに

<audio controls>
<source src="audio/08/071.mp3">
</audio><hr>






